import test from 'node:test';import assert from 'node:assert/strict';import{randomUUID,randomBytes}from'node:crypto';import{mkdir,readFile}from'node:fs/promises';import{resolve,join}from'node:path';import initSqlJs from'sql.js';
import{Store}from'../electron/store';import{assertRelationGraph,transferSuggestions,transferContext}from'../electron/connections';import{decrypt,writeEncrypted}from'../electron/vault';import{EXERCISES,estimate}from'../electron/learning';
import type{ProjectInput}from'../shared/connections';
import {dailyPlan} from '../electron/planning';
const wasm=resolve('node_modules/sql.js/dist/sql-wasm.wasm');
test('restaurar no permite repetir el contenido de un trabajo cambiando su identificador de origen',async()=>{
  const {store,a,b,from,to}=await fixture();try{
    const project=store.saveInterdisciplinaryProject(input(a.id,b.id,from.id,to.id)),activity=project.activities[0];
    const submission={subjectId:a.id,conceptId:from.id,statement:'Comprobar una potencia.',answer:'2^3=8',feedback:'',outcome:'ungraded' as const,hints:0,durationSeconds:10};
    const first=store.saveAttempt(submission),second=store.saveAttempt(submission);
    const work=store.addProjectWork({projectId:project.id,activityId:activity.id,source:{kind:'attempt',id:first.id},conceptIds:[from.id],reflection:''});
    assert.throws(()=>store.addProjectWork({projectId:project.id,activityId:activity.id,source:{kind:'attempt',id:second.id},conceptIds:[from.id],reflection:''}),/ya está/);
    const backup=JSON.parse(store.exportData());backup.tables.project_works.push({...work,id:randomUUID(),source:{...work.source,id:second.id},evidenceKey:`attempt:${second.id}`,originalCreatedAt:second.createdAt,createdAt:new Date(Math.max(Date.parse(second.createdAt),Date.parse(work.createdAt))+1).toISOString()});
    assert.throws(()=>store.importData(JSON.stringify(backup)),/repetido/);assert.equal(store.snapshot().projectWorks.length,1);assert.equal(store.snapshot().attempts.length,2);
  }finally{store.close();}
});
test('el plan mantiene el orden de las actividades compartidas cuando coinciden fecha y prioridad',()=>{
  const a=randomUUID(),b=randomUUID(),conceptA=randomUUID(),conceptB=randomUUID(),draft=input(a,b,conceptA,conceptB),first=draft.activities[0];
  first.id='ffffffff-ffff-4fff-8fff-ffffffffffff';first.dueOn='2026-10-02';first.minutes=5;
  draft.activities.push({...first,id:'00000000-0000-4000-8000-000000000001',title:'Aplicar después'}, {...first,id:'00000000-0000-4000-8000-000000000002',title:'Reflexionar al terminar'});
  const project={...draft,id:randomUUID(),subjectId:a,revision:1,createdAt:'2026-10-01T12:00:00.000Z',updatedAt:'2026-10-01T12:00:00.000Z'};
  const plan=dailyPlan(a,[],[],[],[],[],30,new Date('2026-10-02T12:00:00Z'),[],[project],[]);
  assert.deepEqual(plan.items.map(i=>i.title),draft.activities.map(activity=>`${project.title}: ${activity.title}`));
});
async function fixture(){const directory=resolve('.tools/test-data',randomUUID());await mkdir(directory,{recursive:true});const path=join(directory,'history.tutor'),key=randomBytes(32),store=await Store.open(path,key,wasm),a=store.createDemo(),b=store.createSubject({name:'Matemáticas',level:'FP',teacher:'',goals:'',color:'blue'}),from=store.snapshot().concepts.find(c=>c.name==='Potencias de 2')!,to=store.createConcept({subjectId:b.id,name:'Potencias de 2',description:'Aplicación matemática.',prerequisiteIds:[]});return{store,path,key,a,b,from,to};}
function input(a:string,b:string,c:string,d:string):ProjectInput{return{subjectIds:[a,b],title:'Aplicar las potencias',goal:'Comparar y comprobar los dos contextos.',description:'',conceptIds:[c,d],curriculumIds:[],activities:[{id:randomUUID(),title:'Comparar soluciones',instructions:'Conserva un trabajo de cada asignatura y explica la conexión.',subjectIds:[a,b],conceptIds:[c,d],curriculumIds:[],dueOn:null,minutes:30}]};}
test('las coincidencias se proponen sin afirmar equivalencia y las revisiones no cambian el dominio',async()=>{const{store,from,to}=await fixture();try{const before=store.snapshot().estimates;assert.ok(store.snapshot().relationSuggestions.some(r=>r.fromId===from.id&&r.toId===to.id));const link=store.createConceptRelation({fromId:from.id,toId:to.id,kind:'equivalent',reason:'Comparo operaciones de potencias en dos contextos.'});assert.equal(store.snapshot().learningGraph.edges.filter(e=>e.relationId).length,0);const accepted=store.reviewConceptRelation({id:link.id,decision:'accepted',reason:'Los contenidos definidos coinciden.'});assert.equal(store.snapshot().learningGraph.edges.filter(e=>e.relationId===link.id).length,1);store.reviewConceptRelation({id:link.id,decision:'forgotten',reason:'Voy a contrastar una diferencia.'});assert.equal(store.snapshot().relationReviews.at(-1)!.supersedesId,accepted.id);assert.equal(store.snapshot().learningGraph.edges.filter(e=>e.relationId===link.id).length,0);assert.deepEqual(store.snapshot().estimates,before);assert.doesNotThrow(()=>store.importData(store.exportData()));}finally{store.close();}});
test('el grafo rechaza ciclos entre materias y ciclos creados al combinar equivalencias',async()=>{const{store,from,to}=await fixture();try{const later=store.createConcept({subjectId:to.subjectId,name:'Aplicación',description:'',prerequisiteIds:[to.id]});const forward=store.createConceptRelation({fromId:from.id,toId:to.id,kind:'prerequisite',reason:'Fundamento.'});store.reviewConceptRelation({id:forward.id,decision:'accepted',reason:'Se necesita antes.'});const back=store.createConceptRelation({fromId:later.id,toId:from.id,kind:'prerequisite',reason:'Propuesta.'});assert.throws(()=>store.reviewConceptRelation({id:back.id,decision:'accepted',reason:'Crearía un ciclo.'}),/ciclo/);assert.equal(store.snapshot().relationReviews.length,1);const equivalent=store.createConceptRelation({fromId:from.id,toId:later.id,kind:'equivalent',reason:'Propuesta.'});assert.throws(()=>store.reviewConceptRelation({id:equivalent.id,decision:'accepted',reason:'Igual contenido.'}),/equivalencia|ciclo/);assert.doesNotThrow(()=>store.importData(store.exportData()));}finally{store.close();}});
test('la transferencia requiere dominio comprobado, conexión aceptada y repaso no vencido; nunca modifica destino',async()=>{const{store,from,to}=await fixture();try{const relation=store.createConceptRelation({fromId:from.id,toId:to.id,kind:'equivalent',reason:'Misma operación.'});store.reviewConceptRelation({id:relation.id,decision:'accepted',reason:'Contenido equivalente.'});const attempt=store.submitExercise({conceptId:from.id,exerciseId:'Potencias de 2:0',answer:'32',hints:0,durationSeconds:20}),data=store.snapshot(),states=data.estimates.map(s=>s.conceptId===from.id?{...s,status:'consolidated' as const,evidenceIds:[attempt.id]}:s);const suggestions=transferSuggestions(data.concepts,[relation],states,data.attempts,[]);assert.equal(suggestions.length,1);assert.deepEqual(suggestions[0].evidenceIds,[attempt.id]);assert.equal(transferSuggestions(data.concepts,[relation],states,data.attempts,[{conceptId:from.id,nextDate:'2020-01-01',intervalDays:1,reason:'',evidenceIds:[attempt.id]}]).length,0);assert.equal(transferSuggestions(data.concepts,[relation],states,[{...attempt,hints:1}],[]).length,0);assert.equal(data.estimates.find(s=>s.conceptId===to.id)!.status,'unseen');}finally{store.close();}});
test('los proyectos conservan versiones, trabajos originales de ambas asignaturas y revisiones enlazadas',async()=>{const{store,a,b,from,to}=await fixture();try{const project=store.saveInterdisciplinaryProject(input(a.id,b.id,from.id,to.id)),activity=project.activities[0],works=[];for(const [subject,concept]of[[a,from],[b,to]]){const attempt=store.saveAttempt({subjectId:subject.id,conceptId:concept.id,statement:'Aplica una potencia en este contexto.',answer:subject.name+': 2^3=8',outcome:'ungraded',feedback:'',hints:0,durationSeconds:30});works.push(store.addProjectWork({projectId:project.id,activityId:activity.id,source:{kind:'attempt',id:attempt.id},conceptIds:[concept.id],reflection:'He separado regla y aplicación.'}));assert.throws(()=>store.addProjectWork({projectId:project.id,activityId:activity.id,source:{kind:'attempt',id:attempt.id},conceptIds:[concept.id],reflection:''}),/ya está/);}assert.throws(()=>store.reviewProjectActivity({projectId:project.id,activityId:activity.id,completed:true,workIds:[works[0].id],reflection:''}),/cada asignatura/);const review=store.reviewProjectActivity({projectId:project.id,activityId:activity.id,completed:true,workIds:works.map(w=>w.id),reflection:'La regla se mantiene; cambia el problema.'});const reopened=store.reviewProjectActivity({projectId:project.id,activityId:activity.id,completed:false,workIds:works.map(w=>w.id),reflection:'Quiero contrastar el contexto.'});assert.equal(reopened.supersedesId,review.id);const updated=store.saveInterdisciplinaryProject({...input(a.id,b.id,from.id,to.id),id:project.id,title:'Nueva actividad'});assert.equal(updated.revision,2);assert.equal(store.snapshot().projectVersions.length,2);assert.equal(store.snapshot().projectWorks[0].projectRevision,1);assert.doesNotThrow(()=>store.importData(store.exportData()));assert.ok(store.snapshot().estimates.every(e=>e.status==='unseen'));}finally{store.close();}});
test('las copias manipuladas se rechazan antes de reemplazar datos y borrar una materia limpia conexiones y proyectos compartidos',async()=>{const{store,a,b,from,to}=await fixture();try{const relation=store.createConceptRelation({fromId:from.id,toId:to.id,kind:'equivalent',reason:'Comparar.'});store.reviewConceptRelation({id:relation.id,decision:'accepted',reason:'Confirmo.'});const project=store.saveInterdisciplinaryProject(input(a.id,b.id,from.id,to.id)),attempt=store.saveAttempt({subjectId:a.id,conceptId:from.id,statement:'Una potencia.',answer:'2^3=8',outcome:'ungraded',feedback:'',hints:0,durationSeconds:20});store.addProjectWork({projectId:project.id,activityId:project.activities[0].id,source:{kind:'attempt',id:attempt.id},conceptIds:[from.id],reflection:''});const raw=store.exportData();for(const mutate of[(d:any)=>d.tables.project_works[0].text='Copia alterada',(d:any)=>d.tables.project_versions[0].activities[0].instructions='Requisito alterado',(d:any)=>d.tables.relation_reviews[0].supersedesId=randomUUID(),(d:any)=>d.tables.interdisciplinary_projects[0].subjectIds=[a.id,randomUUID()]]){const bad=JSON.parse(raw);mutate(bad);assert.throws(()=>store.importData(JSON.stringify(bad)));assert.equal(store.snapshot().interdisciplinaryProjects[0].id,project.id);}store.deleteSubject(b.id);assert.equal(store.snapshot().conceptRelations.length,0);assert.equal(store.snapshot().interdisciplinaryProjects.length,0);assert.equal(store.snapshot().projectVersions.length,0);assert.equal(store.snapshot().projectWorks.length,0);assert.equal(store.snapshot().attempts[0].id,attempt.id);assert.doesNotThrow(()=>store.importData(store.exportData()));}finally{store.close();}});
test('el grafo contiene asignaturas, conceptos, competencias y evidencias con sus relaciones',async()=>{const{store,from,a}=await fixture();try{const competency=store.saveCurriculum({subjectId:a.id,kind:'competency',code:'C1',title:'Resolver redes',description:'',conceptIds:[from.id],relatedIds:[]}),attempt=store.saveAttempt({subjectId:a.id,conceptId:from.id,statement:'Prueba gráfica.',answer:'Intento.',outcome:'ungraded',feedback:'',hints:0,durationSeconds:1}),graph=store.snapshot().learningGraph;for(const kind of['subject','concept','competency','evidence'])assert.ok(graph.nodes.some(n=>n.kind===kind));assert.ok(graph.edges.some(e=>e.from===`concept:${from.id}`&&e.to===`competency:${competency.id}`));assert.ok(graph.edges.some(e=>e.from===`evidence:${attempt.id}`&&e.to===`concept:${from.id}`));}finally{store.close();}});
test('migrar una base o copia 0.7 conserva el historial y no inventa conexiones ni proyectos',async()=>{const{store,key,path,from}=await fixture();const backup=JSON.parse(store.exportData()),tables=['concept_relations','relation_reviews','interdisciplinary_projects','project_versions','project_works','project_activity_reviews'];backup.version=7;for(const table of tables)delete backup.tables[table];store.importData(JSON.stringify(backup));store.close();const sql=await initSqlJs({locateFile:()=>wasm}),db=new sql.Database(decrypt(await readFile(path),key));for(const table of tables)db.run(`DROP TABLE ${table}`);db.run('PRAGMA user_version=7');writeEncrypted(path,db.export(),key);db.close();const reopened=await Store.open(path,key,wasm);try{assert.equal(reopened.snapshot().concepts.find(c=>c.id===from.id)!.name,from.name);assert.equal(reopened.snapshot().conceptRelations.length,0);assert.equal(reopened.snapshot().interdisciplinaryProjects.length,0);assert.doesNotThrow(()=>reopened.importData(reopened.exportData()));}finally{reopened.close();}});

test('el historial real consolidado activa una transferencia y una dificultad nueva la retira sin calificar destino',async()=>{const{store,from,to}=await fixture();try{const relation=store.createConceptRelation({fromId:from.id,toId:to.id,kind:'equivalent',reason:'Comparar la misma operación.'});store.reviewConceptRelation({id:relation.id,decision:'accepted',reason:'Confirmo la relación.'});for(const[index,question]of EXERCISES[from.name].slice(0,4).entries())store.submitExercise({conceptId:from.id,exerciseId:`${from.name}:${index}`,answer:question.answer,hints:0,durationSeconds:20});const backup=JSON.parse(store.exportData());const dates=new Map<string,string>();backup.tables.attempts.forEach((a:any,index:number)=>{a.createdAt=new Date(Date.now()-index*86400000).toISOString();dates.set(a.id,a.createdAt);});backup.tables.portfolio.filter((p:any)=>p.automatic).forEach((p:any)=>p.createdAt=dates.get(p.evidenceIds[0]));store.importData(JSON.stringify(backup));let data=store.snapshot();assert.equal(data.estimates.find(e=>e.conceptId===from.id)!.status,'consolidated');assert.equal(data.transfers.length,1);assert.ok(data.transfers[0].evidenceIds.every(id=>data.attempts.some(a=>a.id===id&&a.hints===0)));assert.equal(data.estimates.find(e=>e.conceptId===to.id)!.status,'unseen');store.submitExercise({conceptId:from.id,exerciseId:`${from.name}:0`,answer:'999',hints:0,durationSeconds:20});data=store.snapshot();assert.equal(data.transfers.length,0);assert.equal(data.estimates.find(e=>e.conceptId===to.id)!.status,'unseen');}finally{store.close();}});

test('retirar currículo crea una revisión de proyecto y borrar un origen conserva una copia independiente verificable por hash',async()=>{const{store,a,b,from,to}=await fixture();try{const curriculum=store.saveCurriculum({subjectId:a.id,kind:'competency',code:'C1',title:'Aplicar',description:'',conceptIds:[from.id],relatedIds:[]}),draft=input(a.id,b.id,from.id,to.id);draft.curriculumIds=[curriculum.id];draft.activities[0].curriculumIds=[curriculum.id];const project=store.saveInterdisciplinaryProject(draft),portfolio=store.savePortfolio({subjectId:a.id,title:'Trabajo original',kind:'work',content:'Mi texto original.',reflection:'',conceptIds:[from.id],evidenceIds:[]});const work=store.addProjectWork({projectId:project.id,activityId:project.activities[0].id,source:{kind:'portfolio',id:portfolio.id},conceptIds:[from.id],reflection:'Comparo la aplicación.'});store.deletePortfolio(portfolio.id);assert.equal(store.snapshot().projectWorks[0].source.id,null);assert.equal(store.snapshot().projectWorks[0].text,portfolio.content);store.deleteCurriculum(curriculum.id);assert.equal(store.snapshot().interdisciplinaryProjects[0].revision,2);assert.deepEqual(store.snapshot().interdisciplinaryProjects[0].curriculumIds,[]);assert.deepEqual(store.snapshot().projectVersions[0].curriculumIds,[curriculum.id]);assert.equal(store.snapshot().projectWorks[0].id,work.id);assert.doesNotThrow(()=>store.importData(store.exportData()));}finally{store.close();}});

test('el plan prioriza la fecha del proyecto, respeta el tiempo y deja de proponer actividades completadas',async()=>{const{store,a,b,from,to}=await fixture();try{const draft=input(a.id,b.id,from.id,to.id);draft.activities[0].dueOn='2020-01-01';const project=store.saveInterdisciplinaryProject(draft),plan=store.snapshot().plans.find(p=>p.subjectId===a.id)!;assert.equal(plan.items[0].kind,'project');assert.equal(plan.items[0].targetId,project.id);assert.ok(plan.items.reduce((n,i)=>n+i.minutes,0)<=plan.budgetMinutes);const workIds=[];for(const[subject,concept]of[[a,from],[b,to]]){const original=store.saveAttempt({subjectId:subject.id,conceptId:concept.id,statement:`Actividad de ${subject.name}.`,answer:'Un intento.',feedback:'',outcome:'ungraded',hints:0,durationSeconds:10});workIds.push(store.addProjectWork({projectId:project.id,activityId:project.activities[0].id,source:{kind:'attempt',id:original.id},conceptIds:[concept.id],reflection:''}).id);}store.reviewProjectActivity({projectId:project.id,activityId:project.activities[0].id,completed:true,workIds,reflection:'He comparado los dos contextos.'});assert.ok(store.snapshot().plans.every(p=>!p.items.some(i=>i.kind==='project')));}finally{store.close();}});

test('no se consolida ni recomienda con evidencias del futuro y el contexto de transferencia pertenece a la materia destino',async()=>{const{store,a,b,from,to}=await fixture();try{const attempt=store.submitExercise({conceptId:from.id,exerciseId:`${from.name}:0`,answer:'32',hints:0,durationSeconds:10});const future=[0,1,2,3].map(i=>({...attempt,id:randomUUID(),statement:`Pregunta ${i}`,createdAt:new Date(Date.now()+(i+1)*86400000).toISOString()}));assert.equal(estimate(from.id,future).status,'unseen');const data={...store.snapshot(),transfers:[{relationId:randomUUID(),fromId:from.id,toId:to.id,reason:'Fuente comprobada.',evidenceIds:[attempt.id]}]};assert.equal(transferContext(data,a.id,'potencias'),'');const context=transferContext(data,b.id,'potencias');assert.ok(context.length<600);assert.match(context,/dominioDeDestinoNoInferido/);assert.match(context,new RegExp(attempt.id));}finally{store.close();}});

test('el grafo distingue entregas, portfolio y copias de proyecto y conecta sus conceptos sin cambiar el dominio',async()=>{const{store,a,b,from,to}=await fixture();try{const levels=[{id:randomUUID(),title:'Revisar'},{id:randomUUID(),title:'Justificado'}],rubric=store.saveRubric({subjectId:a.id,title:'Justificar',description:'',levels,criteria:[{id:randomUUID(),title:'Operación',description:'',conceptIds:[from.id],curriculumIds:[],descriptors:levels.map(l=>({levelId:l.id,description:l.title}))}]}),submission=store.createRubricSubmission({subjectId:a.id,rubricId:rubric.id,title:'Una explicación',kind:'text',instructions:'Explica la regla.',text:'La regla es duplicar cada paso.',source:null,materialIds:[]}),portfolio=store.savePortfolio({subjectId:b.id,title:'Aplicación',kind:'work',content:'Aplico una potencia al problema.',reflection:'',conceptIds:[to.id],evidenceIds:[]}),project=store.saveInterdisciplinaryProject(input(a.id,b.id,from.id,to.id)),work=store.addProjectWork({projectId:project.id,activityId:project.activities[0].id,source:{kind:'submission',id:submission.id},conceptIds:[from.id],reflection:''}),graph=store.snapshot().learningGraph;for(const[kind,refId,concept]of[['submission',submission.id,from.id],['portfolio',portfolio.id,to.id],['project-work',work.id,from.id]]){const node=graph.nodes.find(n=>n.evidenceKind===kind&&n.refId===refId)!;assert.ok(node);assert.ok(graph.edges.some(e=>e.from===node.id&&e.to===`concept:${concept}`));}assert.ok(store.snapshot().estimates.every(e=>e.status==='unseen'));store.deleteRubricSubmission(submission.id);assert.ok(!store.snapshot().learningGraph.nodes.some(n=>n.evidenceKind==='submission'&&n.refId===submission.id));assert.equal(store.snapshot().projectWorks[0].source.id,null);assert.doesNotThrow(()=>store.importData(store.exportData()));}finally{store.close();}});
