import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdir, readFile } from 'node:fs/promises';
import initSqlJs from 'sql.js';
import { decrypt, writeEncrypted } from '../electron/vault';
import { resolve, join } from 'node:path';
import { Store } from '../electron/store';
import { arithmeticValue, arithmeticSteps, arithmeticVariants } from '../electron/arithmetic';
import { analysisPrompts, parseObservation, pedagogyContext } from '../electron/pedagogy';
import { dayKey, addDays } from '../shared/calendar';
const wasm=resolve('node_modules/sql.js/dist/sql-wasm.wasm');
async function fixture(){const directory=resolve('.tools/test-data',randomUUID());await mkdir(directory,{recursive:true});const key=randomBytes(32),path=join(directory,'history.tutor'),store=await Store.open(path,key,wasm),subject=store.createDemo();const attempt=store.saveAttempt({subjectId:subject.id,conceptId:null,statement:'Calcula el total y resta dos.',answer:'1. 2^4 = 16\n2. 16 - 2 = 13\nHay trece hosts.',feedback:'',outcome:'ungraded',hints:0,durationSeconds:90});return {store,key,path,subject,attempt};}
test('la aritmética es exacta con fracciones, prioridad, exponentes y porcentajes, sin ejecutar texto',()=>{
  assert.equal(arithmeticValue('1/2 + 1/4'),'3/4');assert.equal(arithmeticValue('-2^2'),'-4');assert.equal(arithmeticValue('2^-2'),'1/4');assert.equal(arithmeticValue('2^3^2'),'512');assert.equal(arithmeticValue('0,1 + 0,2'),'3/10');assert.equal(arithmeticValue('20% × 150'),'30');assert.equal(arithmeticValue('(2+1)²'),'9');assert.throws(()=>arithmeticValue('0/0'));assert.throws(()=>arithmeticValue('0^0'));assert.throws(()=>arithmeticValue('10^10000'));assert.throws(()=>arithmeticValue('process.exit()'));assert.throws(()=>arithmeticValue('3+4 m'));assert.equal(new Set(arithmeticVariants('2^4')).size,3);
});
test('se comprueba el primer cálculo incorrecto legible y se dejan desconocidos texto, unidades y álgebra',()=>{
  const text='Paso 1: 2^4 = 16\nPaso 2: 16 − 2 = 13\n3. x + 2 = 5\n4. 3 + 4 = 7 metros';const steps=arithmeticSteps(text);assert.equal(steps.length,2);assert.equal(steps[0].correct,true);assert.equal(steps[1].correct,false);assert.equal(steps[1].line,2);assert.equal(steps[1].value,'14');for(const step of steps)assert.equal(text.slice(step.start,step.end),step.text);assert.equal(arithmeticSteps('El error del ejemplo es: 2+2=5').length,0);
});
test('los análisis no cambian el dominio y sus citas se verifican contra el trabajo original',async()=>{
  const {store,attempt}=await fixture();try{const before=store.snapshot().estimates,a=store.analyzeSteps({kind:'attempt',id:attempt.id});assert.equal(a.observations.length,1);assert.equal(a.steps[1].correct,false);assert.deepEqual(store.snapshot().estimates,before);assert.equal(store.snapshot().skillProfiles.find(p=>p.skill==='calculation')!.state,'unseen');const bad=structuredClone(a);bad.observations[0].quotes[0].text='Cita inventada';assert.throws(()=>store.saveAnalysis(bad),/fragmento/);const raw=store.exportData();store.importData(raw);assert.equal(store.snapshot().learningAnalyses[0].source.hash,a.source.hash);}finally{store.close();}
});
test('las hipótesis se revisan sin sobrescribir y no se fortalecen por repetir el mismo análisis',async()=>{
  const {store,attempt}=await fixture();try{for(let i=0;i<4;i++){const a=store.analyzeSteps({kind:'attempt',id:attempt.id});store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'accepted',reason:'Me equivoqué al restar.'});}const profile=store.snapshot().skillProfiles.find(p=>p.skill==='calculation')!;assert.equal(profile.workCount,1);assert.equal(profile.confidence,'low');const a=store.snapshot().learningAnalyses[0];store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'forgotten',reason:'Ya no la usaré; necesito comprobar un intento nuevo.'});assert.equal(store.snapshot().observationReviews.length,5);assert.equal(store.snapshot().observationReviews.at(-1)!.supersedesId,store.snapshot().observationReviews[0].id);assert.doesNotThrow(()=>store.importData(store.exportData()));}finally{store.close();}
});
test('una hipótesis transversal necesita trabajos, materias y días; una evidencia contraria reduce la conclusión',async()=>{
  const {store,subject}=await fixture();try{const other=store.createSubject({name:'Matemáticas',level:'',teacher:'',goals:'',color:'blue'});for(const [index,subjectId] of [subject.id,other.id,subject.id].entries()){const work=store.saveAttempt({subjectId,conceptId:null,statement:`Calcula ${index+4} + 1.`,answer:`${index+4} + 1 = ${index+4}`,feedback:'',outcome:'ungraded',hints:0,durationSeconds:30});const a=store.analyzeSteps({kind:'attempt',id:work.id});store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'accepted',reason:'Mi operación no coincide.'});}const backup=JSON.parse(store.exportData());backup.tables.attempts.forEach((a:any,index:number)=>{a.createdAt=new Date(Date.now()-index*86400000).toISOString();});store.importData(JSON.stringify(backup));let p=store.snapshot().skillProfiles.find(p=>p.skill==='calculation')!;assert.equal(p.state,'supported-hypothesis');assert.equal(p.confidence,'medium');const work=store.saveAttempt({subjectId:other.id,conceptId:null,statement:'Calcula una suma nueva.',answer:'8+1=9',feedback:'',outcome:'ungraded',hints:0,durationSeconds:30});const a=store.recordObservation({kind:'attempt',id:work.id,skill:'calculation',signal:'strength',error:null,quote:{start:0,end:5,text:'8+1=9'},description:'La suma tiene un resultado correcto.'});store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'accepted',reason:'Este intento me salió bien.'});p=store.snapshot().skillProfiles.find(p=>p.skill==='calculation')!;assert.equal(p.state,'mixed');assert.equal(p.confidence,'low');}finally{store.close();}
});
test('el refuerzo genera variantes, oculta claves y conserva respuestas, ayudas y reflexión; la comprobación espera otro día',async()=>{
  const {store,attempt}=await fixture();try{const a=store.analyzeSteps({kind:'attempt',id:attempt.id}),input={analysisId:a.id,observationId:a.observations[0].id,minutes:10};assert.throws(()=>store.startIntervention(input),/acepta/);store.reviewObservation({...input,decision:'accepted',reason:'Quiero revisar este cálculo.'});const plan=store.startIntervention(input);assert.equal(plan.activities.length,3);assert.ok(plan.activities.every(a=>!('expected'in a)));for(const activity of plan.activities.slice(0,2)){const answer=arithmeticValue(activity.expression!);const response=store.answerIntervention({interventionId:plan.id,activityId:activity.id,answer,hints:0,durationSeconds:20});assert.equal(response.outcome,'correct');assert.throws(()=>store.answerIntervention({interventionId:plan.id,activityId:activity.id,answer,hints:0,durationSeconds:20}),/ya está/);}assert.throws(()=>store.answerIntervention({interventionId:plan.id,activityId:plan.activities[2].id,answer:'100',hints:0,durationSeconds:20}),/otro día/);store.reflectIntervention({interventionId:plan.id,whatHelped:'Separar las operaciones.',reflection:'Resté demasiado rápido.',nextStep:'Volver a comprobar mañana.'});assert.equal(store.snapshot().interventionReviews.length,1);assert.doesNotThrow(()=>store.importData(store.exportData()));assert.equal(store.snapshot().attempts.length,1);}finally{store.close();}
});
test('las copias rechazan correcciones, citas y cruces de materias; borrar análisis limpia su memoria derivada',async()=>{
  const {store,attempt}=await fixture();try{const a=store.analyzeSteps({kind:'attempt',id:attempt.id});store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'accepted',reason:'Mi cálculo no coincide.'});const plan=store.startIntervention({analysisId:a.id,observationId:a.observations[0].id,minutes:10});const mutations=[(b:any)=>b.tables.learning_analyses[0].steps[0].value='99',(b:any)=>b.tables.interventions[0].activities[0].expected='999',(b:any)=>b.tables.observation_reviews[0].observationId=randomUUID(),(b:any)=>b.tables.interventions[0].activities[0].statement='Otra pregunta'];const raw=store.exportData();for(const mutate of mutations){const b=JSON.parse(raw);mutate(b);assert.throws(()=>store.importData(JSON.stringify(b)));assert.equal(store.snapshot().interventions[0].id,plan.id);}store.deleteAnalysis(a.id);assert.equal(store.snapshot().learningAnalyses.length,0);assert.equal(store.snapshot().interventions.length,0);assert.equal(store.snapshot().observationReviews.length,0);assert.equal(store.snapshot().attempts[0].id,attempt.id);}finally{store.close();}
});
test('la IA cubre todos los caracteres de trabajos largos y rechaza fragmentos inventados antes de guardar',async()=>{
  const {store,attempt}=await fixture();try{const work={...store.workContext({kind:'attempt',id:attempt.id}),text:('Un intento completo.\n').repeat(2200)};const prompts=analysisPrompts(work);assert.equal(prompts[0].coverage.start,0);assert.equal(prompts.at(-1)!.coverage.end,work.text.length);assert.equal(prompts.flatMap(p=>p.fragments.map(f=>f.text)).join(''),work.text);assert.ok(prompts.every(p=>p.messages.reduce((n,m)=>n+m.content.length,0)<=6000));const p=prompts[0],raw=JSON.stringify({signal:'difficulty',skill:'writing',error:'writing',quoteIds:[p.fragments[0].index]});assert.ok(parseObservation(raw,p.fragments));assert.throws(()=>parseObservation(JSON.stringify({signal:'difficulty',skill:'writing',error:'writing',quoteIds:[99999]}),p.fragments),/inexistente/);assert.equal(parseObservation(JSON.stringify({signal:'none',skill:'writing',error:'none',quoteIds:[]}),p.fragments),null);}finally{store.close();}
});

test('copiar un trabajo con otro identificador no aumenta las evidencias independientes',async()=>{
  const {store,attempt}=await fixture();try{
    for(let i=0;i<3;i++){const copy=store.saveAttempt({...attempt,id:undefined,answer:attempt.answer+'\n',hints:0});const a=store.analyzeSteps({kind:'attempt',id:copy.id});store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'accepted',reason:'Revisión de una copia.'});}
    assert.equal(store.snapshot().skillProfiles.find(p=>p.skill==='calculation')!.workCount,1);
    assert.equal(store.snapshot().skillProfiles.find(p=>p.skill==='calculation')!.confidence,'low');
  }finally{store.close();}
});

test('el seguimiento de otro día conserva su resultado y permite dejar de usar la hipótesis con esa evidencia',async()=>{
  const {store,attempt}=await fixture();try{
    const a=store.analyzeSteps({kind:'attempt',id:attempt.id});store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'accepted',reason:'Revisaré la resta.'});
    const plan=store.startIntervention({analysisId:a.id,observationId:a.observations[0].id,minutes:20});
    for(const activity of plan.activities.slice(0,2))store.answerIntervention({interventionId:plan.id,activityId:activity.id,answer:arithmeticValue(activity.expression!),hints:1,durationSeconds:30});
    const backup=JSON.parse(store.exportData());for(const table of ['attempts','learning_analyses','observation_reviews','interventions','intervention_responses'])for(const row of backup.tables[table])row.createdAt=new Date(Date.parse(row.createdAt)-2*86400000).toISOString();
    backup.tables.interventions[0].followUpOn=addDays(dayKey(new Date(backup.tables.interventions[0].createdAt)),1);store.importData(JSON.stringify(backup));
    const response=store.answerIntervention({interventionId:plan.id,activityId:plan.activities[2].id,answer:arithmeticValue(plan.activities[2].expression!),hints:0,durationSeconds:18});assert.equal(response.outcome,'correct');
    store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'forgotten',reason:'He comprobado un intento nuevo otro día.',followUpResponseId:response.id});
    assert.equal(store.snapshot().skillProfiles.find(p=>p.skill==='calculation')!.state,'unseen');assert.doesNotThrow(()=>store.importData(store.exportData()));assert.equal(store.snapshot().learningAnalyses.length,1);
    const manipulated=JSON.parse(store.exportData());manipulated.tables.interventions[0].activities[0].expression='999+1';manipulated.tables.interventions[0].activities[0].expected='1000';manipulated.tables.interventions[0].activities[0].statement='Calcula 999+1. Escribe el resultado numérico o una fracción.';manipulated.tables.interventions[0].activities[0].feedback='999+1 = 1000.';assert.throws(()=>store.importData(JSON.stringify(manipulated)),/deriva/);
  }finally{store.close();}
});

test('el contexto del tutor solo incluye observaciones aceptadas de la asignatura y olvida las retiradas',async()=>{
  const {store,attempt,subject}=await fixture();try{const a=store.analyzeSteps({kind:'attempt',id:attempt.id});assert.equal(pedagogyContext(store.snapshot(),subject.id,'resta'),'');store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'accepted',reason:'Comprobaré el cálculo.'});const plan=store.startIntervention({analysisId:a.id,observationId:a.observations[0].id,minutes:30});store.reflectIntervention({interventionId:plan.id,whatHelped:'Separar las operaciones.',reflection:'',nextStep:'Revisar mañana.'});const context=pedagogyContext(store.snapshot(),subject.id,'resta');assert.ok(context.length<600);assert.match(context,/Separar las operaciones/);assert.equal(pedagogyContext(store.snapshot(),randomUUID(),'resta'),'');store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'forgotten',reason:'Ya no la usaré.'});assert.equal(pedagogyContext(store.snapshot(),subject.id,'resta'),'');assert.doesNotThrow(()=>store.importData(store.exportData()));}finally{store.close();}
});

test('bases y copias 0.6 conservan sus datos sin inventar análisis al migrar',async()=>{
  const {store,path,key,attempt,subject}=await fixture();
  const previous=JSON.parse(store.exportData());previous.version=6;const newTables=['learning_analyses','observation_reviews','interventions','intervention_responses','intervention_reviews'];for(const table of newTables)delete previous.tables[table];
  store.importData(JSON.stringify(previous));assert.equal(store.snapshot().learningAnalyses.length,0);assert.equal(store.snapshot().attempts[0].id,attempt.id);store.close();
  const sql=await initSqlJs({locateFile:()=>wasm}),db=new sql.Database(decrypt(await readFile(path),key));for(const table of newTables)db.run(`DROP TABLE ${table}`);db.run('PRAGMA user_version = 6');writeEncrypted(path,db.export(),key);db.close();
  const reopened=await Store.open(path,key,wasm);try{assert.equal(reopened.snapshot().subjects[0].id,subject.id);assert.equal(reopened.snapshot().attempts[0].id,attempt.id);assert.equal(reopened.snapshot().learningAnalyses.length,0);assert.equal(JSON.parse(reopened.exportData()).version, 12);}finally{reopened.close();}
});

test('analizar una copia en rúbrica conserva el origen y borrar la entrega limpia sus refuerzos',async()=>{
  const {store,attempt,subject}=await fixture();try{
    const levels=[{id:randomUUID(),title:'Revisar'},{id:randomUUID(),title:'Correcto'}];const rubric=store.saveRubric({subjectId:subject.id,title:'Cálculo',description:'',levels,criteria:[{id:randomUUID(),title:'Operaciones',description:'',conceptIds:[],curriculumIds:[],descriptors:levels.map(l=>({levelId:l.id,description:l.title}))}]});
    const submission=store.createRubricSubmission({subjectId:subject.id,rubricId:rubric.id,title:'Mi cálculo',kind:'practice',instructions:attempt.statement,text:attempt.answer,source:{kind:'attempt',id:attempt.id},materialIds:[]});
    const original=store.analyzeSteps({kind:'attempt',id:attempt.id}),copy=store.analyzeSteps({kind:'submission',id:submission.id});for(const a of [original,copy])store.reviewObservation({analysisId:a.id,observationId:a.observations[0].id,decision:'accepted',reason:'Reviso el mismo cálculo.'});assert.equal(store.snapshot().skillProfiles.find(p=>p.skill==='calculation')!.workCount,1);
    const plan=store.startIntervention({analysisId:copy.id,observationId:copy.observations[0].id,minutes:10});store.reflectIntervention({interventionId:plan.id,whatHelped:'Comprobar la resta.',reflection:'',nextStep:'Hacer un cálculo nuevo.'});store.deleteRubricSubmission(submission.id);
    assert.equal(store.snapshot().learningAnalyses.length,1);assert.equal(store.snapshot().learningAnalyses[0].id,original.id);assert.equal(store.snapshot().interventions.length,0);assert.equal(store.snapshot().interventionReviews.length,0);assert.equal(store.snapshot().attempts[0].id,attempt.id);assert.doesNotThrow(()=>store.importData(store.exportData()));
  }finally{store.close();}
});

test('la IA conserva el enunciado completo o rechaza el contexto antes de analizar',async()=>{
  const {store,attempt}=await fixture();try{const work={...store.workContext({kind:'attempt',id:attempt.id}),question:'Condición inicial. '+('dato '.repeat(250))+'CONDICIÓN FINAL'};const prompt=analysisPrompts(work)[0];assert.match(prompt.messages[1].content,/CONDICIÓN FINAL/);assert.throws(()=>analysisPrompts({...work,question:'dato '.repeat(1500)}),/enunciado completo/);assert.equal(store.snapshot().learningAnalyses.length,0);}finally{store.close();}
});
