import type { Attempt } from '../shared/types.js';
import type { LearningReport } from '../shared/reports.js';
import { REPORT_STATUS_NAMES } from './reports.js';

const escape = (value: string | number) => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const confidence = { low: 'Baja', medium: 'Media', high: 'Alta' };
const change = { 'first-evidence': 'Primeras evidencias', improved: 'Mejora apoyada en ejercicios nuevos', regressed: 'Dificultad en ejercicios nuevos', stable: 'Sin cambio de estado', 'check-again': 'Conviene comprobar el recuerdo' };
export function reportDocument(r: LearningReport, attempts: Attempt[]): string {
  const ids = [...new Set(r.concepts.flatMap(c => [...c.before.evidenceIds, ...c.after.evidenceIds]))];
  const byId = new Map(attempts.map(a => [a.id, a])), evidence = ids.map(id => byId.get(id)).filter((a): a is Attempt => !!a);
  const reference = (id: string) => `E${ids.indexOf(id) + 1}`;
  const timestamp = (value: string) => new Intl.DateTimeFormat('es', { timeZone: r.timezone, dateStyle: 'short', timeStyle: 'short' }).format(new Date(value));
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline';"><title>${escape(r.title)}</title><style>
  @page{size:A4;margin:19mm 17mm 18mm}*{box-sizing:border-box}body{margin:0;font:10pt/1.5 'Segoe UI',Arial,sans-serif;color:#263b32}h1,h2,h3{overflow-wrap:anywhere}h1{font-size:24pt;line-height:1.18;margin:8pt 0 10pt}h2{font-size:15pt;margin:20pt 0 9pt;break-after:avoid}h3{font-size:12pt;margin:0 0 7pt;break-after:avoid}p{margin:5pt 0 8pt;white-space:pre-wrap;overflow-wrap:anywhere}.eyebrow{font-size:8pt;letter-spacing:2pt;color:#58745e}.muted{color:#5d6a62;font-size:9pt}.intro{border-bottom:2pt solid #375f4b;padding-bottom:13pt}.stats{display:flex;gap:10pt;margin:16pt 0}.stat{background:#eef3e9;padding:9pt 12pt;flex:1;font-size:8pt}.stat strong{display:block;font-size:18pt}.concept,.help,.evidence{border:1pt solid #d8e0d4;border-radius:5pt;padding:12pt;margin:0 0 10pt;break-inside:avoid-page}.concept.long,.evidence.long{break-inside:auto}.state{background:#f2f5ee;padding:7pt 9pt;font-size:9pt}.refs{font-size:8pt;color:#526658;overflow-wrap:anywhere}.notice{padding:9pt 11pt;background:#f8f1df;font-size:9pt}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:9pt}td,th{text-align:left;vertical-align:top;padding:7pt;border-bottom:1pt solid #d8e0d4;overflow-wrap:anywhere}thead{display:table-header-group}th:first-child{width:23%}.identity{font-size:8pt;overflow-wrap:anywhere;margin-top:18pt}a{color:#375f4b;text-decoration:none}code{font:8pt Consolas,monospace;overflow-wrap:anywhere}
  </style></head><body><div class="intro"><div class="eyebrow">TUTOR LOCAL · MI APRENDIZAJE</div><h1>${escape(r.title)}</h1><p>${escape(r.subject.name)} · ${escape(r.subject.course || r.subject.level)}</p><p class="muted">Periodo: ${escape(r.startsOn)} a ${escape(r.endsOn)}. Cierre: ${escape(timestamp(r.asOf))} (${escape(r.timezone)}). Versión ${r.revision}.</p></div>
  <p class="notice">Fotografía del aprendizaje al cerrar el periodo. Las estimaciones usan los ejercicios comprobados enlazados y las pistas registradas. Las autoevaluaciones se conservan como información personal. Este informe orienta el estudio y no constituye una calificación docente.</p>
  ${r.kind === 'transition' ? `<p>Selección personal para ${escape(r.targetCourse)}: ${r.concepts.length} ${r.concepts.length === 1 ? 'concepto' : 'conceptos'} y sus ejercicios de apoyo. Conserva esta información útil y revisa las estimaciones en el nuevo curso.</p>` : ''}
  <div class="stats"><div class="stat"><strong>${r.stats.verified}</strong>${r.kind === 'transition' ? 'Ejercicios de apoyo' : 'Intentos comprobados'}</div><div class="stat"><strong>${r.stats.personal}</strong>Registros personales</div><div class="stat"><strong>${r.stats.correctWithoutHints}</strong>Aciertos sin pistas</div><div class="stat"><strong>${Math.round(r.stats.exerciseSeconds / 60)}</strong>Minutos registrados en ejercicios</div></div>
  ${r.stats.otherActivities ? `<p class="muted">Otros registros del periodo: ${r.stats.otherActivities} (tarjetas, sesiones, tareas, proyectos o refuerzos). Su finalización no modifica el dominio por sí sola.</p>` : ''}
  <h2>Conocimientos, evolución y próximos pasos</h2>${r.concepts.map(c => `<article class="concept ${c.after.reason.length + c.recommendation.reason.length > 700 ? 'long' : ''}"><h3>${escape(c.name)}</h3><p class="state">${escape(REPORT_STATUS_NAMES[c.before.status])} → ${escape(REPORT_STATUS_NAMES[c.after.status])} · Confianza ${escape(confidence[c.after.confidence]).toLowerCase()}</p><p class="muted">${escape(change[c.change])}</p><p>${escape(c.after.reason)}</p><p><strong>Siguiente paso:</strong> ${escape(c.recommendation.reason)}</p>${c.prerequisites.length ? `<p class="muted">Prerrequisitos: ${escape(c.prerequisites.map(p => p.name).join(', '))}. Conviene comprobarlos si la dificultad continúa.</p>` : ''}<p class="refs">Apoyo anterior: ${c.before.evidenceIds.map(id => reference(id)).join(', ') || 'Sin ejercicios comprobados'}. Apoyo al cierre: ${c.after.evidenceIds.map(id => reference(id)).join(', ') || 'Sin ejercicios comprobados'}.</p></article>`).join('')}
  ${r.unit?.curriculum.length ? `<h2>Currículo de la unidad al crear el informe</h2><table><thead><tr><th>Código</th><th>Elemento curricular</th></tr></thead><tbody>${r.unit.curriculum.map(c => `<tr><td>${escape(c.code || c.kind)}</td><td>${escape(c.title)}</td></tr>`).join('')}</tbody></table>` : ''}
  ${r.help.length ? `<h2>Ayudas que elegiste conservar</h2>${r.help.map(h => `<article class="help"><h3>Qué me ayudó</h3><p>${escape(h.whatHelped)}</p><p><strong>Próximo paso:</strong> ${escape(h.nextStep)}</p><p class="refs">Reflexión ${escape(h.reviewId)} · Intervención ${escape(h.interventionId)}. Valoración personal.</p></article>`).join('')}` : ''}
  ${r.reflection ? `<h2>Mi reflexión</h2><p>${escape(r.reflection)}</p>` : ''}
  <h2>Ejercicios que apoyan las estimaciones</h2>${evidence.length ? evidence.map(a => `<article class="evidence ${a.statement.length + Math.min(a.answer.length, 800) > 1800 ? 'long' : ''}"><h3>${reference(a.id)} · ${escape(a.createdAt.slice(0, 10))}</h3><p>${escape(a.statement)}</p><p class="muted">${a.outcome === 'correct' ? 'Correcto' : a.outcome === 'incorrect' ? 'Por revisar' : 'Parcial'} · ${a.hints} pistas · Ejercicio comprobado.</p><p>${a.answer.length > 800 ? 'Respuesta (extracto de los primeros 800 caracteres):' : 'Respuesta:'} ${escape(a.answer.slice(0, 800))}</p><p class="refs">Evidencia: ${escape(a.id)}. La respuesta completa permanece en el historial local.</p></article>`).join('') : '<p>No hay ejercicios comprobados para las estimaciones de esta selección.</p>'}
  <p class="identity">Informe ${escape(r.id)} · Generado ${escape(timestamp(r.createdAt))}. El archivo exportado es legible; guárdalo donde decidas compartirlo.</p></body></html>`;
}
