import { useState, type FormEvent } from 'react';
import { ArrowDown, ArrowUp, CalendarDays, Layers, Link2, PencilLine, Plus, Trash2 } from 'lucide-react';
import type { CurriculumItem, CurriculumKind, DidacticUnit, UnitInput, CurriculumInput } from '../../shared/education';
import { Empty, Modal, PageTitle, Spinner, SubjectRequired, errorMessage, type PageProps } from '../ui';

export const curriculumNames: Record<CurriculumKind, string> = { competency: 'Competencia', criterion: 'Criterio de evaluación', content: 'Saber / contenido', outcome: 'Resultado de aprendizaje (FP)' };
const unitStatuses = { pending: 'Pendiente', current: 'En curso', taught: 'Impartida' };

export default function Curriculum(props: PageProps) {
  const { data, subject, refresh, notify, onNewSubject } = props;
  const [tab, setTab] = useState<'units' | 'curriculum'>('units');
  const [editingUnit, setEditingUnit] = useState<DidacticUnit | 'new'>();
  const [editingItem, setEditingItem] = useState<CurriculumItem | 'new'>();
  const [deleting, setDeleting] = useState<{ kind: 'unit' | 'curriculum'; id: string; title: string }>();
  const [busy, setBusy] = useState(false);
  if (!subject) return <SubjectRequired onNewSubject={onNewSubject} />;
  const units = data.units.filter(u => u.subjectId === subject.id).sort((a, b) => a.position - b.position);
  const items = data.curriculum.filter(c => c.subjectId === subject.id);
  async function change(work: () => Promise<unknown>) {
    if (busy) return; setBusy(true);
    try { await work(); await refresh(); } catch (failure) { notify(errorMessage(failure), true); } finally { setBusy(false); }
  }
  function move(index: number, offset: number) {
    const ids = units.map(u => u.id); [ids[index], ids[index + offset]] = [ids[index + offset], ids[index]];
    void change(() => window.tutor.reorderUnits({ subjectId: subject!.id, ids }));
  }
  return <><PageTitle eyebrow={subject.name} title="Un recorrido para cada aprendizaje." description="Organiza unidades, contenidos y criterios; vincula lo que haces con lo que quieres aprender." action={<button className="button primary" onClick={() => tab === 'units' ? setEditingUnit('new') : setEditingItem('new')}><Plus size={17} />{tab === 'units' ? 'Añadir unidad' : 'Añadir elemento curricular'}</button>} />
    <div className="tabs"><button className={tab === 'units' ? 'selected' : ''} onClick={() => setTab('units')}><Layers size={17} /> Secuencia de unidades <span>{units.length}</span></button><button className={tab === 'curriculum' ? 'selected' : ''} onClick={() => setTab('curriculum')}><Link2 size={17} /> Currículo <span>{items.length}</span></button></div>
    {tab === 'units' ? units.length ? <div className="education-list">{units.map((unit, index) => <article className="education-card" key={unit.id}><div className="education-heading"><span className="plan-step">{String(index + 1).padStart(2, '0')}</span><div><h2>{unit.title}</h2><span className={`badge ${unit.status === 'taught' ? 'green' : unit.status === 'current' ? 'blue' : 'neutral'}`}>{unitStatuses[unit.status]}</span></div><div className="education-actions"><button className="icon-button" aria-label={`Subir ${unit.title}`} disabled={!index || busy} onClick={() => move(index, -1)}><ArrowUp size={16} /></button><button className="icon-button" aria-label={`Bajar ${unit.title}`} disabled={index === units.length - 1 || busy} onClick={() => move(index, 1)}><ArrowDown size={16} /></button><button className="icon-button" aria-label={`Editar ${unit.title}`} onClick={() => setEditingUnit(unit)}><PencilLine size={16} /></button><button className="icon-button danger-hover" aria-label={`Eliminar ${unit.title}`} onClick={() => setDeleting({ kind: 'unit', id: unit.id, title: unit.title })}><Trash2 size={16} /></button></div></div><p>{unit.objectives || 'Sin objetivos específicos registrados.'}</p>{(unit.startsOn || unit.endsOn) && <p className="education-date"><CalendarDays size={14} />{unit.startsOn ?? 'Inicio por definir'} → {unit.endsOn ?? 'Final por definir'}</p>}<div className="education-tags">{unit.conceptIds.map(id => <span className="prerequisite-chip" key={id}>{data.concepts.find(c => c.id === id)?.name}</span>)}</div>{unit.prerequisiteIds.length > 0 && <p className="bank-help">Antes: {unit.prerequisiteIds.map(id => units.find(u => u.id === id)?.title).join(', ')}</p>}{unit.curriculumIds.length > 0 && <details><summary>Currículo relacionado ({unit.curriculumIds.length})</summary>{unit.curriculumIds.map(id => { const row = items.find(c => c.id === id); return <p key={id}>{row?.code} · {row?.title}</p>; })}</details>}{unit.materialIds.length > 0 && <p className="bank-help">Materiales: {unit.materialIds.map(id => { const material = data.materials.find(m => m.id === id); return `${material?.name} · v${material?.version}`; }).join(', ')}</p>}<p className="bank-help">{data.tasks.filter(t => t.unitId === unit.id).length} tareas vinculadas. Impartida describe la secuencia docente; el dominio se comprueba en Mi aprendizaje.</p></article>)}</div> : <Empty icon={<Layers size={28} />} title="Dale orden a esta asignatura" action={<button className="button primary" onClick={() => setEditingUnit('new')}>Añadir mi primera unidad</button>}>Cada unidad puede incluir conceptos, materiales, currículo, fechas y prerrequisitos.</Empty>
    : items.length ? <div className="concept-grid">{items.map(item => <article className="education-card" key={item.id}><div className="education-heading"><span className="eyebrow">{curriculumNames[item.kind]}</span><div className="education-actions"><button className="icon-button" aria-label={`Editar ${item.title}`} onClick={() => setEditingItem(item)}><PencilLine size={16} /></button><button className="icon-button danger-hover" aria-label={`Eliminar ${item.title}`} onClick={() => setDeleting({ kind: 'curriculum', id: item.id, title: item.title })}><Trash2 size={16} /></button></div></div>{item.code && <span className="curriculum-code">{item.code}</span>}<h3>{item.title}</h3><p>{item.description}</p><div className="education-tags">{item.conceptIds.map(id => <span className="prerequisite-chip" key={id}>{data.concepts.find(c => c.id === id)?.name}</span>)}</div>{item.relatedIds.length > 0 && <p className="bank-help">Relacionado con: {item.relatedIds.map(id => items.find(c => c.id === id)?.title).join(', ')}</p>}<p className="bank-help">{data.tasks.filter(t => t.curriculumIds?.includes(item.id)).length} tareas vinculadas.</p></article>)}</div> : <Empty icon={<Link2 size={28} />} title="Relaciona tus actividades con el currículo" action={<button className="button primary" onClick={() => setEditingItem('new')}>Añadir elemento curricular</button>}>Añade competencias, criterios de evaluación, saberes y resultados de aprendizaje de FP. Puedes enlazarlos con conceptos, unidades y tareas.</Empty>}
    {editingUnit && <UnitEditor {...props} unit={editingUnit === 'new' ? undefined : editingUnit} onClose={() => setEditingUnit(undefined)} />}
    {editingItem && <CurriculumEditor {...props} item={editingItem === 'new' ? undefined : editingItem} onClose={() => setEditingItem(undefined)} />}
    {deleting && <Modal title="¿Eliminar este elemento?" onClose={() => { if (!busy) setDeleting(undefined); }}><p className="modal-intro">Se retirará «{deleting.title}» y se limpiarán sus enlaces en unidades y tareas. Tus ejercicios se conservarán.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={() => setDeleting(undefined)}>Cancelar</button><button className="button danger" disabled={busy} onClick={() => { void change(async () => { if (deleting.kind === 'unit') await window.tutor.deleteUnit(deleting.id); else await window.tutor.deleteCurriculum(deleting.id); setDeleting(undefined); }); }}>Eliminar</button></div></Modal>}
  </>;
}

export function CheckReferences({ name, legend, rows, selected = [] }: { name: string; legend: string; rows: { id: string; label: string }[]; selected?: string[] }) {
  if (!rows.length) return null;
  return <fieldset className="prerequisite-options"><legend>{legend}</legend>{rows.map(row => <label key={row.id}><input type="checkbox" name={name} value={row.id} defaultChecked={selected.includes(row.id)} />{row.label}</label>)}</fieldset>;
}

function CurriculumEditor({ data, subject, item, refresh, notify, onClose }: PageProps & { item?: CurriculumItem; onClose(): void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    const input: CurriculumInput = { subjectId: subject!.id, kind: String(form.get('kind')) as CurriculumKind, code: String(form.get('code')), title: String(form.get('title')), description: String(form.get('description')), conceptIds: form.getAll('concepts').map(String), relatedIds: form.getAll('related').map(String) };
    try { await window.tutor.saveCurriculum({ ...input, id: item?.id }); await refresh(); onClose(); notify('Elemento curricular guardado.'); } catch (failure) { setError(errorMessage(failure)); } finally { setBusy(false); }
  }
  return <Modal title={item ? 'Editar elemento curricular' : 'Añadir elemento curricular'} onClose={() => { if (!busy) onClose(); }}><form className="form-stack" onSubmit={submit}><div className="form-row"><label>Tipo<select aria-label="Tipo" name="kind" defaultValue={item?.kind ?? 'competency'}>{Object.entries(curriculumNames).map(([kind, label]) => <option key={kind} value={kind}>{label}</option>)}</select></label><label>Código<input name="code" defaultValue={item?.code ?? ''} maxLength={50} placeholder="Ej. RA1, CE1.2" /></label></div><label>Título curricular<input name="title" autoFocus defaultValue={item?.title ?? ''} required maxLength={120} /></label><label>Descripción<textarea name="description" rows={3} defaultValue={item?.description ?? ''} maxLength={4000} /></label><CheckReferences name="concepts" legend="Conceptos" rows={data.concepts.filter(c => c.subjectId === subject!.id).map(c => ({ id: c.id, label: c.name }))} selected={item?.conceptIds} /><CheckReferences name="related" legend="Relación con otros elementos curriculares" rows={data.curriculum.filter(c => c.subjectId === subject!.id && c.id !== item?.id).map(c => ({ id: c.id, label: `${c.code ? `${c.code} · ` : ''}${c.title}` }))} selected={item?.relatedIds} />{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? <Spinner /> : 'Guardar currículo'}</button></div></form></Modal>;
}

function UnitEditor({ data, subject, unit, refresh, notify, onClose }: PageProps & { unit?: DidacticUnit; onClose(): void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const owned = data.units.filter(u => u.subjectId === subject!.id).sort((a, b) => a.position - b.position);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    const input: UnitInput = { subjectId: subject!.id, title: String(form.get('title')), objectives: String(form.get('objectives')), startsOn: String(form.get('start')) || null, endsOn: String(form.get('end')) || null, status: String(form.get('status')) as UnitInput['status'], prerequisiteIds: form.getAll('prerequisites').map(String), conceptIds: form.getAll('concepts').map(String), curriculumIds: form.getAll('curriculum').map(String), materialIds: form.getAll('materials').map(String) };
    try { await window.tutor.saveUnit({ ...input, id: unit?.id }); await refresh(); onClose(); notify('Unidad guardada en tu secuencia.'); } catch (failure) { setError(errorMessage(failure)); } finally { setBusy(false); }
  }
  return <Modal title={unit ? 'Editar unidad' : 'Añadir unidad'} wide onClose={() => { if (!busy) onClose(); }}><form className="form-stack" onSubmit={submit}><label>Título de la unidad<input name="title" autoFocus defaultValue={unit?.title ?? ''} required maxLength={120} /></label><label>Objetivos de la unidad<textarea name="objectives" rows={3} maxLength={4000} defaultValue={unit?.objectives ?? ''} /></label><div className="form-row"><label>Inicio previsto<input name="start" type="date" min="2000-01-01" max="2100-12-31" defaultValue={unit?.startsOn ?? ''} /></label><label>Final previsto<input name="end" type="date" min="2000-01-01" max="2100-12-31" defaultValue={unit?.endsOn ?? ''} /></label><label>Estado de la unidad<select name="status" defaultValue={unit?.status ?? 'pending'}>{Object.entries(unitStatuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><CheckReferences name="prerequisites" legend="Unidades previas necesarias" rows={owned.filter(u => u.position < (unit?.position ?? owned.length)).map(u => ({ id: u.id, label: u.title }))} selected={unit?.prerequisiteIds} /><CheckReferences name="concepts" legend="Conceptos de esta unidad" rows={data.concepts.filter(c => c.subjectId === subject!.id).map(c => ({ id: c.id, label: c.name }))} selected={unit?.conceptIds} /><CheckReferences name="curriculum" legend="Currículo relacionado" rows={data.curriculum.filter(c => c.subjectId === subject!.id).map(c => ({ id: c.id, label: `${c.code} · ${c.title}` }))} selected={unit?.curriculumIds} /><CheckReferences name="materials" legend="Materiales y versiones" rows={data.materials.filter(m => m.subjectId === subject!.id).map(m => ({ id: m.id, label: `${m.name} · v${m.version}` }))} selected={unit?.materialIds} />{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? <Spinner /> : 'Guardar unidad'}</button></div></form></Modal>;
}
