import { useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, Check, FileText, GalleryVerticalEnd, Lightbulb, PencilLine, Plus, RotateCcw, Sparkles, Trash2 } from 'lucide-react';
import type { Flashcard, RecallRating } from '../../shared/education';
import { dayKey } from '../../shared/calendar';
import { Empty, Modal, PageTitle, Spinner, SubjectRequired, dateLabel, errorMessage, type PageProps } from '../ui';

const origins = { manual: 'Creada por ti', material: 'Desde un material', attempt: 'Desde un error comprobado' };
export default function Flashcards(props: PageProps) {
  const { data, subject, refresh, notify, onNewSubject } = props;
  const [tab, setTab] = useState<'study' | 'drafts' | 'library'>('study');
  const [editing, setEditing] = useState<Flashcard | 'new'>();
  const [generating, setGenerating] = useState(false);
  const [deleting, setDeleting] = useState<Flashcard>();
  const [sourceCard, setSourceCard] = useState<Flashcard>();
  const [historyCard, setHistoryCard] = useState<Flashcard>();
  const [query, setQuery] = useState('');
  const [currentId, setCurrentId] = useState('');
  const [revealed, setRevealed] = useState(false);
  const [busy, setBusy] = useState(false);
  const cards = data.flashcards.filter(c => c.subjectId === subject?.id);
  const today = dayKey();
  const due = cards.filter(c => c.approved && (data.cardSchedules.find(s => s.cardId === c.id)?.dueDate ?? today) <= today);
  const drafts = cards.filter(c => !c.approved);
  const current = due.find(c => c.id === currentId) ?? due[0];
  useEffect(() => { setRevealed(false); }, [current?.id, current?.revision]);
  if (!subject) return <SubjectRequired onNewSubject={onNewSubject} />;
  async function action(work: () => Promise<unknown>, message?: string) {
    if (busy) return; setBusy(true);
    try { await work(); await refresh(); if (message) notify(message); } catch (failure) { notify(errorMessage(failure), true); } finally { setBusy(false); }
  }
  async function rate(rating: RecallRating) {
    if (!current || !revealed) return;
    const next = due.find(c => c.id !== current.id)?.id ?? '';
    await action(() => window.tutor.reviewFlashcard({ id: current.id, rating })); setCurrentId(next); setRevealed(false);
  }
  const shown = (tab === 'drafts' ? drafts : cards).filter(c => `${c.front} ${c.back}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));
  return <><PageTitle eyebrow={subject.name} title="Recordar también se practica." description="Tarjetas con fuentes, repaso espaciado y una valoración honesta de lo que recuerdas." action={<div className="data-actions"><button className="button secondary" onClick={() => setGenerating(true)}><Sparkles size={16} /> Generar tarjetas</button><button className="button primary" onClick={() => setEditing('new')}><Plus size={16} /> Crear tarjeta</button></div>} />
    <div className="tabs"><button className={tab === 'study' ? 'selected' : ''} onClick={() => setTab('study')}><RotateCcw size={17} /> Repasar <span>{due.length}</span></button><button className={tab === 'drafts' ? 'selected' : ''} onClick={() => setTab('drafts')}><Lightbulb size={17} /> Por revisar <span>{drafts.length}</span></button><button className={tab === 'library' ? 'selected' : ''} onClick={() => setTab('library')}><GalleryVerticalEnd size={17} /> Todas <span>{cards.length}</span></button></div>
    {tab === 'study' ? current ? <div className="flashcard-study"><section className="recall-card"><div className="recall-heading"><span className="eyebrow">{origins[current.origin]}</span><span>{due.length} pendientes hoy</span></div><h2>{current.front}</h2>{revealed ? <><div className="recall-answer" aria-label="Respuesta de la tarjeta">{current.back}</div><p className="bank-help">Compara lo que recordabas con la respuesta y elige tu valoración.</p><div className="recall-ratings">{([['again', 'Otra vez'], ['hard', 'Me costó'], ['good', 'Lo recordaba'], ['easy', 'Muy fácil']] as const).map(([rating, label]) => <button key={rating} className={`button ${rating === 'again' ? 'secondary danger-text' : 'secondary'}`} disabled={busy} onClick={() => { void rate(rating); }}>{label}</button>)}</div></> : <><p className="diagnostic-description">Intenta recordarlo antes de mirar. Puedes responder en voz alta o escribirlo en una hoja.</p><button className="button primary" onClick={() => setRevealed(true)}>Mostrar respuesta <ArrowRight size={16} /></button></>}<div className="recall-footer"><span>{current.conceptId ? data.concepts.find(c => c.id === current.conceptId)?.name : 'Sin concepto vinculado'} · v{current.revision}</span>{(current.source || current.evidenceIds.length > 0) && <button className="text-button" onClick={() => setSourceCard(current)}>Consultar fuente</button>}</div></section><aside className="context-tip"><h3>Recuerdo y dominio tienen evidencias distintas.</h3><p>Esta valoración organiza el repaso de la tarjeta. Para estimar dominio usamos tus ejercicios comprobados.</p><p>Una nueva versión de la tarjeta comienza un nuevo calendario y conserva las revisiones anteriores.</p></aside></div> : <Empty icon={<GalleryVerticalEnd size={29} />} title={cards.some(c => c.approved) ? 'Las tarjetas aprobadas ya tienen su siguiente fecha' : 'Prepara tus primeras tarjetas'} action={<div className="empty-actions"><button className="button primary" onClick={() => cards.length ? setTab('drafts') : setGenerating(true)}>{cards.length ? 'Revisar borradores' : 'Generar desde mis materiales'}</button><button className="button secondary" onClick={() => setEditing('new')}>Crear una tarjeta</button></div>}>{cards.some(c => c.approved) ? 'Puedes consultar tu biblioteca o generar tarjetas para otro contenido.' : 'Genera propuestas desde tus apuntes o errores y revísalas antes de estudiar.'}</Empty>
    : <><label className="search-field history-search"><input aria-label="Buscar tarjetas" placeholder="Buscar una pregunta o idea…" value={query} onChange={event => setQuery(event.target.value)} /></label>{shown.length ? <div className="card-library">{shown.map(card => { const schedule = data.cardSchedules.find(s => s.cardId === card.id); return <article className="education-card" key={card.id}><div className="education-heading"><span className="eyebrow">{origins[card.origin]} · v{card.revision}</span><div className="education-actions"><button className="icon-button" aria-label={`Editar tarjeta ${card.front}`} onClick={() => setEditing(card)}><PencilLine size={16} /></button><button className="icon-button danger-hover" aria-label={`Eliminar tarjeta ${card.front}`} onClick={() => setDeleting(card)}><Trash2 size={16} /></button></div></div><h3>{card.front}</h3><p className="card-back-preview">{card.back}</p><div className="education-tags"><span className={`badge ${card.approved ? 'green' : 'orange'}`}>{card.approved ? 'Aprobada' : 'Revisar antes de estudiar'}</span>{schedule && <span className="bank-help">Próximo repaso: {schedule.dueDate}</span>}</div><div className="education-actions"><button className="text-button" onClick={() => setHistoryCard(card)}>Ver versiones y repasos</button>{(card.source || card.evidenceIds.length > 0) && <button className="text-button" onClick={() => setSourceCard(card)}><FileText size={14} /> Ver fuente</button>}{!card.approved && <button className="button secondary" disabled={busy} onClick={() => { void action(() => window.tutor.approveFlashcard({ id: card.id, approved: true }), 'Tarjeta aprobada. Ya puedes practicarla.'); }}><Check size={15} /> Aprobar tarjeta</button>}</div></article>; })}</div> : <Empty icon={<Lightbulb size={28} />} title={tab === 'drafts' ? 'No hay borradores pendientes' : 'No hay tarjetas con esa búsqueda'}>{tab === 'drafts' ? 'Las propuestas generadas aparecerán aquí para que compruebes su contenido y su fuente.' : 'Prueba con otra palabra o crea una tarjeta nueva.'}</Empty>}</>}
    {generating && <GenerateCards {...props} onClose={() => setGenerating(false)} />}
    {editing && <CardEditor {...props} card={editing === 'new' ? undefined : editing} onClose={() => setEditing(undefined)} />}
    {historyCard && <Modal title="Versiones y repasos de la tarjeta" onClose={() => setHistoryCard(undefined)} wide><p className="modal-intro">Cada versión mantiene su contenido y sus propias valoraciones. Estas valoraciones son autoevaluaciones del recuerdo.</p><div className="recall-history">{data.cardRevisions.filter(r => r.cardId === historyCard.id).slice().reverse().map(revision => <article key={revision.id}><strong>Versión {revision.revision} · {dateLabel(revision.createdAt)}</strong><h3>{revision.front}</h3><p>{revision.back}</p>{revision.source && <p>Origen: {data.materials.find(m => m.id === revision.source!.materialId)?.name} · v{revision.source.materialVersion} · página {revision.source.page}</p>}<p>{data.cardReviews.filter(r => r.cardId === historyCard.id && r.revision === revision.revision).length} repasos registrados</p>{data.cardReviews.filter(r => r.cardId === historyCard.id && r.revision === revision.revision).map(review => <p key={review.id}>{dateLabel(review.createdAt)} · {{ again: 'Otra vez', hard: 'Me costó', good: 'Lo recordaba', easy: 'Muy fácil' }[review.rating]}</p>)}</article>)}</div></Modal>}
    {sourceCard && <Modal title="La fuente de esta tarjeta" onClose={() => setSourceCard(undefined)} wide>{sourceCard.source && <><p className="modal-intro">{data.materials.find(m => m.id === sourceCard.source!.materialId)?.name} · v{sourceCard.source.materialVersion} · página {sourceCard.source.page}</p><blockquote className="source-quote">{sourceCard.source.quote}</blockquote></>}{sourceCard.evidenceIds.map(id => { const attempt = data.attempts.find(a => a.id === id); return attempt && <article className="evidence-card" key={id}><h3>{attempt.statement}</h3><p>Tu respuesta: {attempt.answer}</p><p>{attempt.feedback}</p><p className="history-meta">{dateLabel(attempt.createdAt)} · Evidencia {attempt.id.slice(0, 8)}</p></article>; })}</Modal>}
    {deleting && <Modal title="¿Eliminar esta tarjeta?" onClose={() => { if (!busy) setDeleting(undefined); }}><p className="modal-intro">Se borrarán la tarjeta, sus versiones y sus revisiones. El material o ejercicio de origen se conservará.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={() => setDeleting(undefined)}>Cancelar</button><button className="button danger" disabled={busy} onClick={() => { void action(async () => { await window.tutor.deleteFlashcard(deleting.id); setDeleting(undefined); }); }}>Eliminar tarjeta</button></div></Modal>}
  </>;
}

function GenerateCards({ data, subject, refresh, notify, onClose }: PageProps & { onClose(): void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const materials = data.materials.filter(m => m.subjectId === subject!.id).filter(m => !data.materials.some(newer => newer.subjectId === m.subjectId && newer.name === m.name && newer.version > m.version));
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    try { const count = await window.tutor.generateFlashcards({ subjectId: subject!.id, materialId: String(form.get('material')) || undefined, fromErrors: Boolean(form.get('errors')) }); await refresh(); onClose(); notify(`${count} propuestas nuevas. Revísalas en «Por revisar».`); } catch (failure) { setError(errorMessage(failure)); } finally { setBusy(false); }
  }
  return <Modal title="Generar tarjetas con tus fuentes" onClose={() => { if (!busy) onClose(); }}><p className="modal-intro">Se proponen preguntas de recuerdo y fragmentos literales de tus materiales. Las respuestas correctas de ejercicios fallados también pueden convertirse en tarjetas. Comprueba cada propuesta antes de aprobarla.</p><form className="form-stack" onSubmit={submit}><label>Material de origen<select name="material" defaultValue={materials[0]?.id ?? ''}><option value="">No usar un material</option>{materials.map(m => <option key={m.id} value={m.id}>{m.name} · v{m.version}</option>)}</select></label><label className="inline-check"><input type="checkbox" name="errors" />Incluir mis errores comprobados</label><p className="bank-help">Hasta 20 propuestas por origen. La generación y la detección de duplicados se realizan en este ordenador.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? <Spinner /> : 'Generar propuestas'}</button></div></form></Modal>;
}

function CardEditor({ data, subject, card, refresh, notify, onClose }: PageProps & { card?: Flashcard; onClose(): void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    const input = { subjectId: subject!.id, front: String(form.get('front')), back: String(form.get('back')), conceptId: String(form.get('concept')) || null };
    try { if (card) { await window.tutor.editFlashcard({ id: card.id, front: input.front, back: input.back, conceptId: input.conceptId }); if (form.get('approve')) await window.tutor.approveFlashcard({ id: card.id, approved: true }); } else await window.tutor.createFlashcard(input); await refresh(); onClose(); notify('Tarjeta guardada.'); } catch (failure) { setError(errorMessage(failure)); } finally { setBusy(false); }
  }
  return <Modal title={card ? 'Editar tarjeta' : 'Crear tarjeta'} onClose={() => { if (!busy) onClose(); }}><form className="form-stack" onSubmit={submit}><label>Pregunta o idea a recordar<textarea autoFocus name="front" rows={3} required maxLength={2000} defaultValue={card?.front ?? ''} /></label><label>Respuesta de referencia<textarea name="back" rows={5} required maxLength={10000} defaultValue={card?.back ?? ''} /></label><label>Concepto de la tarjeta<select name="concept" defaultValue={card?.conceptId ?? ''}><option value="">Sin concepto vinculado</option>{data.concepts.filter(c => c.subjectId === subject!.id).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{card && <><label className="inline-check"><input type="checkbox" name="approve" defaultChecked />Aprobar después de guardar</label><p className="bank-help">Editar el contenido crea una versión propia y reinicia su calendario. Las revisiones anteriores se conservan.</p></>}{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? <Spinner /> : 'Guardar tarjeta'}</button></div></form></Modal>;
}
