import { useState, type FormEvent } from 'react';
import { Target, Plus, PencilLine, Trash2, ArrowRight, Sprout, CheckCircle2 } from 'lucide-react';
import type { PersonalGoal, GoalInput, GoalReview, LearningAlert, LearningHabit } from '../../shared/goals';
import { dayKey, addDays } from '../../shared/calendar';
import { Badge, Empty, Modal, PageTitle, SubjectRequired, Spinner, confidenceNames, errorMessage, outcomeName, type PageProps } from '../ui';

export const goalKinds = { improve: 'Mejorar un bloque', exam: 'Preparar una prueba', recover: 'Recuperar una materia', advance: 'Profundizar' };
const statusNames = { active: 'En marcha', paused: 'En pausa', achieved: 'Alcanzada por ti', abandoned: 'Dejada de seguir' };
const actions = { progress: 'Revisar mi progreso', paused: 'Poner en pausa', resumed: 'Retomar la meta', achieved: 'Considerarla alcanzada', abandoned: 'Dejar de seguirla' };
const reviewStatus = (id: string, reviews: GoalReview[]) => { const action = reviews.filter(r => r.goalId === id && r.action !== 'progress').at(-1)?.action; return action === 'paused' || action === 'achieved' || action === 'abandoned' ? action : 'active'; };

export function Habit({ habit, compact = false }: { habit?: LearningHabit; compact?: boolean }) {
  if (!habit) return null;
  return <section className={`habit-card ${compact ? 'compact' : ''}`}><div className="goal-section-head"><span className="eyebrow"><Sprout size={16} /> UN RITMO QUE TE AYUDA</span><strong>{habit.currentStreak} {habit.currentStreak === 1 ? 'día seguido' : 'días seguidos'}</strong></div><p>Cuenta días con ejercicios, tarjetas o sesiones revisadas de al menos dos minutos. Repetir acciones en un día no multiplica la racha.</p><div className="habit-calendar" aria-label="Actividad registrada en los últimos 28 días">{habit.recentDays.map(day => <span className={day.active ? 'active' : ''} key={day.date} title={`${day.date}: ${day.active ? 'actividad registrada' : 'sin actividad registrada'}`} aria-label={`${day.date}: ${day.active ? 'actividad registrada' : 'sin actividad registrada'}`} />)}</div><div className="habit-foot"><span>{habit.totalDays} días con actividad · Mayor racha: {habit.longestStreak}</span><span>Últimas cuatro semanas</span></div><p className="subtle-note">La racha no es una nota ni demuestra dominio. Puedes retomar cuando te venga bien; tus evidencias se conservan.</p></section>;
}
export function OriginalEvidence({ ids, props, onClose }: { ids: string[]; props: PageProps; onClose(): void }) {
  return <Modal title="Ejercicios que apoyan esta selección" onClose={onClose} wide>{ids.length ? ids.map(id => { const a = props.data.attempts.find(a => a.id === id); return a && <article className="evidence-card" key={id}><div><CheckCircle2 size={16} /><strong>{outcomeName(a.outcome)}</strong><span>{new Date(a.createdAt).toLocaleDateString('es')} · {a.hints} pistas · {a.source === 'verified' ? 'Comprobado' : 'Registro personal'}</span></div><h3>{a.statement}</h3><p className="goal-original">{a.answer}</p><p>{a.feedback}</p><small>Evidencia {a.id}</small></article>; }) : <p>No hay ejercicios enlazados a esta selección. La ausencia de registros no demuestra una dificultad; puedes haber estudiado fuera de la aplicación.</p>}<div className="modal-actions"><button className="button secondary" onClick={onClose}>Cerrar</button></div></Modal>;
}
export default function Goals(props: PageProps) {
  const { data, subject, refresh, notify } = props;
  const [editor, setEditor] = useState<PersonalGoal | 'new'>(), [reviewing, setReviewing] = useState<PersonalGoal>(), [alert, setAlert] = useState<LearningAlert>(), [deleting, setDeleting] = useState<PersonalGoal>();
  const [history, setHistory] = useState(false), [evidence, setEvidence] = useState<string[]>(), [busy, setBusy] = useState(false);
  if (!subject) return <SubjectRequired onNewSubject={props.onNewSubject} />;
  const owned = data.personalGoals.filter(g => g.subjectId === subject.id), latest = owned.filter(g => !owned.some(n => n.supersedesId === g.id)), alerts = data.learningAlerts.filter(a => a.subjectId === subject.id);
  async function remove() { setBusy(true); try { await window.tutor.deleteGoal(deleting!.id); await refresh(); setDeleting(undefined); notify('Meta y versiones eliminadas. Los ejercicios se conservan.'); } catch (e) { notify(errorMessage(e), true); } finally { setBusy(false); } }
  return <><PageTitle eyebrow={subject.name} title="Una meta que tenga sentido para ti." description="Elige qué quieres mejorar, conserva tus intentos y revisa la estrategia." action={<button className="button primary" onClick={() => setEditor('new')}><Plus size={17} /> Nueva meta</button>} />
    <Habit habit={data.learningHabits.find(h => h.subjectId === subject.id)} />
    <div className="section-heading"><h2>Mis metas</h2><label className="goal-check"><input type="checkbox" checked={history} onChange={e => setHistory(e.target.checked)} /> Mostrar versiones anteriores</label></div>
    {(history ? owned : latest).length ? <div className="personal-goals">{(history ? owned : latest).slice().reverse().map(g => { const progress = data.goalProgress.find(p => p.goalId === g.id), status = progress?.status ?? reviewStatus(g.id, data.goalReviews), current = latest.some(l => l.id === g.id), reviews = data.goalReviews.filter(r => r.goalId === g.id); return <article className="personal-goal" key={g.id}><div className="goal-section-head"><span className="eyebrow">{goalKinds[g.kind]} · VERSIÓN {g.revision}</span><span className={`goal-status ${status}`}>{current ? statusNames[status] : 'Versión histórica'}</span></div><h2>{g.title}</h2>{g.description && <p className="goal-original">{g.description}</p>}<p className="goal-period">Desde el {g.startsOn}{g.dueOn ? ` · Fecha prevista: ${g.dueOn}` : ' · Sin fecha límite'}{progress?.overdue && status === 'active' ? ' · Revisa la fecha si lo necesitas' : ''}</p>{progress && <><div className="goal-progress-track" role="progressbar" aria-label="Días de práctica de la meta" aria-valuemin={0} aria-valuemax={g.targetDays} aria-valuenow={Math.min(progress.practiceDays, g.targetDays)}><span style={{ width: `${Math.min(100, progress.practiceDays / g.targetDays * 100)}%` }} /></div><p>{progress.reason}</p>{progress.targetMet && <p className="goal-target-met">Has alcanzado el ritmo de práctica previsto. Revisa qué has aprendido antes de decidir si alcanzaste la meta.</p>}<div className="goal-concepts">{progress.estimates.map(e => <div key={e.conceptId}><strong>{data.concepts.find(c => c.id === e.conceptId)?.name}</strong><Badge status={e.status} /><span>Confianza {confidenceNames[e.confidence].toLowerCase()}</span><button className="text-button" onClick={() => setEvidence(e.evidenceIds)}>Ver evidencias</button></div>)}</div></>}
      {current && <div className="goal-actions"><button className="button primary" onClick={() => setReviewing(g)}>Revisar meta</button>{status === 'active' && <button className="button secondary" onClick={() => props.navigate('practice', g.conceptIds[0])}>Practicar <ArrowRight size={16} /></button>}<button className="button secondary" onClick={() => setEditor(g)}><PencilLine size={16} /> Nueva versión</button><button className="icon-button" aria-label={`Eliminar meta ${g.title}`} onClick={() => setDeleting(g)}><Trash2 size={17} /></button></div>}
      {reviews.length > 0 && <details className="goal-reviews"><summary>Mis reflexiones: {reviews.length}</summary>{reviews.map(r => <article key={r.id}><strong>{actions[r.action]} · {new Date(r.createdAt).toLocaleDateString('es')}</strong><p className="goal-original">{r.reflection}</p>{r.evidenceIds.length > 0 && <button className="text-button" onClick={() => setEvidence(r.evidenceIds)}>Ver trabajos seleccionados</button>}</article>)}</details>}</article>; })}</div> : <Empty icon={<Target size={28} />} title="Empieza con algo concreto" action={<button className="button primary" onClick={() => setEditor('new')}>Crear una meta</button>}>Mejorar un bloque, preparar una prueba, recuperar una materia o profundizar. Tú decides cuándo revisar lo que funciona.</Empty>}
    <div className="section-heading"><h2>Avisos para decidir el siguiente paso</h2><span>{alerts.filter(a => !a.reviewed).length} por revisar</span></div><p>Son señales del historial local, sin diagnóstico ni calificación. Los cambios de estado no sustituyen tu reflexión ni la evaluación del profesor.</p><div className="learning-alerts">{alerts.map(a => <article className={`learning-alert ${a.reviewed ? 'reviewed' : ''}`} key={a.key}><div className="goal-section-head"><h3>{a.title}</h3><span>{a.reviewed ? 'Revisado por ti' : 'Por revisar'}</span></div><p>{a.reason}</p><div className="goal-actions">{a.evidenceIds.length > 0 && <button className="button secondary" onClick={() => setEvidence(a.evidenceIds)}>Ver ejercicios de apoyo</button>}{a.conceptId && <button className="text-button" onClick={() => props.navigate('practice', a.conceptId!)}>Comprobar ahora <ArrowRight size={15} /></button>}<button className="button secondary" disabled={a.reviewed} onClick={() => setAlert(a)}>Guardar mi reflexión</button></div>{a.reviewed && <p className="goal-original">{data.alertReviews.find(r => r.alertKey === a.key)?.reflection}</p>}</article>)}</div>{!alerts.length && <p className="inline-placeholder">No hay avisos que cumplan las reglas actuales. Esto no demuestra que todo esté consolidado; revisa también los conceptos sin evidencias.</p>}
    <p className="subtle-note">Las metas, pausas y decisiones son personales. No modifican las estimaciones de dominio ni notas de Moodle.</p>
    {editor && <GoalEditor {...props} goal={editor === 'new' ? undefined : editor} onClose={() => setEditor(undefined)} />}
    {reviewing && <GoalReflection {...props} goal={reviewing} onClose={() => setReviewing(undefined)} />}
    {alert && <AlertReflection {...props} alert={alert} onClose={() => setAlert(undefined)} />}
    {evidence && <OriginalEvidence ids={evidence} props={props} onClose={() => setEvidence(undefined)} />}
    {deleting && <Modal title="Eliminar meta y versiones" onClose={() => { if (!busy) setDeleting(undefined); }}><p>Se eliminarán «{deleting.title}», sus versiones y reflexiones. Los ejercicios originales se conservan.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={() => setDeleting(undefined)}>Cancelar</button><button className="button danger" disabled={busy} onClick={() => { void remove(); }}>Eliminar meta</button></div></Modal>}
  </>;
}
function GoalEditor(props: PageProps & { goal?: PersonalGoal; onClose(): void }) {
  const { goal, data, subject } = props, concepts = data.concepts.filter(c => c.subjectId === subject!.id);
  const [form, setForm] = useState<GoalInput>(() => ({ subjectId: subject!.id, title: goal?.title ?? '', kind: goal?.kind ?? 'improve', description: goal?.description ?? '', conceptIds: goal?.conceptIds ?? [], targetDays: goal?.targetDays ?? 3, startsOn: goal?.startsOn ?? dayKey(), dueOn: goal?.dueOn ?? null, supersedesId: goal?.id ?? null }));
  const [busy, setBusy] = useState(false), [error, setError] = useState(''); const patch = (v: Partial<GoalInput>) => setForm(f => ({ ...f, ...v }));
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { await window.tutor.saveGoal(form); await props.refresh(); props.onClose(); props.notify('Meta guardada con su versión.'); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title={goal ? 'Nueva versión de la meta' : 'Mi nueva meta'} onClose={() => { if (!busy) props.onClose(); }} wide><form className="form-stack" onSubmit={submit}>{goal && <p>La versión anterior y sus reflexiones se conservan. Esta definición empieza en marcha; revisa sus criterios de nuevo.</p>}<label>Título<input aria-label="Título de la meta" value={form.title} onChange={e => patch({ title: e.target.value })} required maxLength={160} autoFocus /></label><label>Qué quiero lograr<select aria-label="Tipo de meta" value={form.kind} onChange={e => patch({ kind: e.target.value as GoalInput['kind'] })}>{Object.entries(goalKinds).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Cómo sabré que he avanzado<textarea aria-label="Criterio personal de la meta" rows={3} value={form.description} onChange={e => patch({ description: e.target.value })} maxLength={4000} placeholder="Qué podré explicar o hacer, en qué situación y cómo lo comprobaré…" /></label><div className="form-row"><label>Desde cuándo<input aria-label="Inicio de la meta" type="date" value={form.startsOn} required onChange={e => patch({ startsOn: e.target.value })} /></label><label>Fecha prevista, opcional<input aria-label="Fecha prevista de la meta" type="date" min={form.startsOn} value={form.dueOn ?? ''} onChange={e => patch({ dueOn: e.target.value || null })} /></label></div><label>Días de práctica sin pistas que me propongo<input aria-label="Días de práctica previstos" type="number" min={1} max={60} value={form.targetDays} required onChange={e => patch({ targetDays: Number(e.target.value) })} /></label><p>Un día cuenta una vez, con ejercicios comprobados de los conceptos elegidos. También cuenta un intento incorrecto sin pistas: practicar y dominar son cosas distintas.</p><fieldset className="goal-selection"><legend>Conceptos de la meta</legend>{concepts.map(c => <label key={c.id}><input type="checkbox" checked={form.conceptIds.includes(c.id)} onChange={e => patch({ conceptIds: e.target.checked ? [...form.conceptIds, c.id] : form.conceptIds.filter(id => id !== c.id) })} />{c.name}</label>)}</fieldset>{!concepts.length && <p>Añade antes los conceptos de esta asignatura en Mi aprendizaje.</p>}{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={props.onClose}>Cancelar</button><button className="button primary" disabled={busy || !form.conceptIds.length}>{busy ? <Spinner label="Guardando…" /> : 'Guardar meta'}</button></div></form></Modal>;
}
function GoalReflection(props: PageProps & { goal: PersonalGoal; onClose(): void }) {
  const { goal, data } = props, status = data.goalProgress.find(p => p.goalId === goal.id)!.status;
  const [action, setAction] = useState<GoalReview['action']>('progress'), [reflection, setReflection] = useState(''), [ids, setIds] = useState<string[]>([]), [page, setPage] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const attempts = data.attempts.filter(a => a.subjectId === goal.subjectId && !!a.conceptId && goal.conceptIds.includes(a.conceptId) && a.createdAt <= new Date().toISOString()).slice().reverse(), visible = attempts.slice(page * 20, (page + 1) * 20);
  const available: GoalReview['action'][] = status === 'active' ? ['progress', 'paused', 'achieved', 'abandoned'] : status === 'paused' ? ['progress', 'resumed', 'abandoned'] : ['progress', 'resumed'];
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { await window.tutor.reviewGoal({ goalId: goal.id, action, reflection, evidenceIds: ids }); await props.refresh(); props.onClose(); props.notify('Reflexión y decisión guardadas.'); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title={`Revisar meta: ${goal.title}`} onClose={() => { if (!busy) props.onClose(); }} wide><form className="form-stack" onSubmit={submit}><label>Mi decisión<select aria-label="Decisión sobre la meta" value={action} onChange={e => setAction(e.target.value as GoalReview['action'])}>{available.map(a => <option value={a} key={a}>{actions[a]}</option>)}</select></label><label>Qué funcionó y qué haré ahora<textarea aria-label="Reflexión sobre la meta" value={reflection} onChange={e => setReflection(e.target.value)} required maxLength={4000} rows={4} /></label><p>Considerar una meta alcanzada es tu decisión personal. Se conserva junto a los trabajos elegidos y no modifica el dominio de conceptos.</p><fieldset className="goal-selection"><legend>Trabajos que quiero enlazar, opcional</legend>{visible.map(a => <label key={a.id}><input type="checkbox" checked={ids.includes(a.id)} onChange={e => setIds(e.target.checked ? [...ids, a.id] : ids.filter(id => id !== a.id))} /><span>{a.statement}<small>{new Date(a.createdAt).toLocaleDateString('es')} · {a.source === 'verified' ? 'Comprobado' : 'Registro personal'} · {outcomeName(a.outcome)}</small></span></label>)}</fieldset>{attempts.length > 20 && <div className="goal-actions"><button type="button" className="button secondary" disabled={page === 0} onClick={() => setPage(p => p - 1)}>Anteriores</button><span>{page * 20 + 1}–{Math.min(attempts.length, (page + 1) * 20)} de {attempts.length}</span><button type="button" className="button secondary" disabled={(page + 1) * 20 >= attempts.length} onClick={() => setPage(p => p + 1)}>Siguientes</button></div>}{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={props.onClose}>Cancelar</button><button className="button primary" disabled={busy}>Guardar reflexión</button></div></form></Modal>;
}
function AlertReflection(props: PageProps & { alert: LearningAlert; onClose(): void }) {
  const [reflection, setReflection] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { await window.tutor.reviewAlert({ key: props.alert.key, reflection }); await props.refresh(); props.onClose(); props.notify('Reflexión del aviso guardada.'); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title="Mi respuesta al aviso" onClose={() => { if (!busy) props.onClose(); }}><form className="form-stack" onSubmit={submit}><p>{props.alert.reason}</p><label>Qué comprobaré o qué estrategia cambiaré<textarea aria-label="Reflexión sobre el aviso" value={reflection} onChange={e => setReflection(e.target.value)} required rows={4} maxLength={4000} /></label><p>El aviso se conserva como revisado. Nuevas evidencias pueden generar otra señal; tu reflexión no altera los ejercicios.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={props.onClose}>Cancelar</button><button className="button primary" disabled={busy}>Guardar reflexión del aviso</button></div></form></Modal>;
}
