import { useEffect, useState, type FormEvent } from 'react';
import { Check, ClipboardCheck, GitCompareArrows, Lightbulb, Sparkles, Trash2 } from 'lucide-react';
import type { LearningAnalysis, LearningObservation, ObservationReview, Intervention, PracticeActivity, LearningSkill, ErrorKind, WorkInput } from '../../shared/pedagogy';
import { SKILLS } from '../../shared/pedagogy';
import { dayKey } from '../../shared/calendar';
import { Empty, Modal, PageTitle, Spinner, SubjectRequired, dateLabel, errorMessage, type PageProps } from '../ui';
const names: Record<LearningSkill,string> = { reading:'Comprensión lectora',graphs:'Interpretación de gráficas','problem-solving':'Resolución de problemas',writing:'Expresión escrita',calculation:'Cálculo',logic:'Pensamiento lógico' };
const errors: Record<ErrorKind,string> = { conceptual:'Conceptual',procedure:'Procedimiento',calculation:'Cálculo',reading:'Comprensión',writing:'Expresión' };
const sourceWork = (data:PageProps['data'], source:WorkInput) => source.kind==='attempt' ? { title:data.attempts.find(a=>a.id===source.id)?.statement??'Ejercicio',text:data.attempts.find(a=>a.id===source.id)?.answer??'' } : {title:data.rubricSubmissions.find(a=>a.id===source.id)?.title??'Entrega',text:data.rubricSubmissions.find(a=>a.id===source.id)?.text??''};
export default function Pedagogy(props:PageProps){
  const {data,subject,refresh,notify,onNewSubject}=props;
  const [tab,setTab]=useState<'work'|'profile'|'reinforcement'>('work'),[source,setSource]=useState(''),[busy,setBusy]=useState('');
  const [selected,setSelected]=useState<{analysis:LearningAnalysis;observation:LearningObservation;decision:ObservationReview['decision']}>(),[record,setRecord]=useState(false),[deleting,setDeleting]=useState<LearningAnalysis>();
  const [focused,setFocused]=useState('');
  useEffect(()=>{setSource('');setFocused('');setSelected(undefined);setRecord(false);},[subject?.id]);
  if(!subject)return <SubjectRequired onNewSubject={onNewSubject}/>;
  const workOptions=[...data.attempts.filter(a=>a.subjectId===subject.id).map(a=>({key:`attempt:${a.id}`,title:a.statement})),...data.rubricSubmissions.filter(a=>a.subjectId===subject.id).map(a=>({key:`submission:${a.id}`,title:a.title}))];
  const ref:WorkInput|undefined=source?{kind:source.split(':')[0] as WorkInput['kind'],id:source.split(':')[1]}:undefined;
  const work=ref?sourceWork(data,ref):undefined;
  const analyses=data.learningAnalyses.filter(a=>a.subjectId===subject.id&&(!ref||(a.source.kind===ref.kind&&a.source.id===ref.id))).slice().reverse();
  const latest=(id:string)=>data.observationReviews.filter(r=>r.observationId===id).at(-1);
  async function action(key:string, operation:()=>Promise<unknown>,message?:string){setBusy(key);try{await operation();await refresh();if(message)notify(message);}catch(error){notify(errorMessage(error),true);}finally{setBusy('');}}
  const plans=data.interventions.filter(i=>i.subjectId===subject.id).slice().reverse();const plan=plans.find(i=>i.id===focused)??plans[0];
  return <><PageTitle eyebrow={subject.name} title="Entender cómo aprendes." description="Del trabajo concreto a una hipótesis que puedes comprobar."/>
    <div className="tabs"><button className={tab==='work'?'selected':''} onClick={()=>setTab('work')}><ClipboardCheck size={17}/> Revisar un trabajo</button><button className={tab==='profile'?'selected':''} onClick={()=>setTab('profile')}><GitCompareArrows size={17}/> Entre asignaturas</button><button className={tab==='reinforcement'?'selected':''} onClick={()=>setTab('reinforcement')}><Lightbulb size={17}/> Mis refuerzos <span>{plans.length}</span></button></div>
    {tab==='work'?<><section className="pedagogy-panel"><label className="form-stack">Trabajo a revisar<select aria-label="Trabajo a revisar" value={source} disabled={Boolean(busy)} onChange={e=>setSource(e.target.value)}><option value="">Todos los análisis · selecciona un trabajo para revisar</option>{workOptions.map(o=><option key={o.key} value={o.key}>{o.key.startsWith('attempt:')?'Ejercicio':'Entrega'} · {o.title.slice(0,130)}</option>)}</select></label>{work&&<><h2>{work.title}</h2><label className="form-stack">Trabajo original<textarea aria-label="Trabajo original" readOnly value={work.text} rows={6}/></label><div className="pedagogy-actions"><button className="button secondary" disabled={Boolean(busy)||!work.text.trim()} onClick={()=>{void action('steps',()=>window.tutor.analyzeSteps(ref!), 'Igualdades numéricas comprobadas.');}}>Comprobar cálculos por pasos</button><button className="button secondary" disabled={Boolean(busy)||!work.text.trim()||!['ready','running'].includes(data.model.state)} onClick={()=>{void action('ai',()=>window.tutor.analyzeWorkLocally(ref!), 'Propuestas guardadas para que las revises.');}}><Sparkles size={15}/> Proponer hipótesis con IA local</button><button className="text-button" disabled={Boolean(busy)||!work.text.trim()} onClick={()=>setRecord(true)}>Anotar una observación</button>{busy==='ai'&&<button className="text-button" onClick={()=>{void window.tutor.cancelChat();}}>Cancelar análisis</button>}{busy&&<Spinner label={busy==='ai'?'Analizando en este ordenador…':'Guardando…'}/>}</div><p className="subtle-note">La comprobación numérica revisa igualdades escritas con operaciones. Deja sin corregir texto, unidades y pasos que no interpreta. La IA propone hipótesis para contrastar; el resultado no cambia tu dominio de conceptos.</p></>}</section>
      {!workOptions.length&&<Empty icon={<ClipboardCheck size={29}/>} title="Empieza por conservar tu intento">Registra un ejercicio o una entrega con rúbrica. Después podrás revisar sus pasos y enlazar observaciones con el texto original.</Empty>}
      <div className="pedagogy-list">{analyses.map(analysis=><article className="pedagogy-panel" key={analysis.id}><div className="pedagogy-heading"><div><span className="eyebrow">{analysis.engine==='arithmetic'?'COMPROBACIÓN NUMÉRICA':analysis.engine==='local-ai'?'HIPÓTESIS DE IA LOCAL':'OBSERVACIÓN PERSONAL'}</span><h2>{sourceWork(data,analysis.source).title}</h2><p>{dateLabel(analysis.createdAt)}</p></div><button className="icon-button danger-hover" aria-label="Borrar análisis" onClick={()=>setDeleting(analysis)}><Trash2 size={17}/></button></div>{analysis.steps.length>0&&<details className="pedagogy-steps" open><summary>{analysis.steps.length} pasos numéricos comprobados</summary>{analysis.steps.map((step,index)=><p key={index}><span className={`badge ${step.correct?'green':'orange'}`}>{step.correct?'Coincide':'Revisar'}</span> Paso {step.line}: <code>{step.text}</code>{!step.correct&&<> · Valor calculado: {step.value}</>}</p>)}<p>Primer cálculo incorrecto comprobable: {analysis.steps.find(s=>!s.correct)?.line??'ninguno'}. Otros tipos de pasos pueden necesitar revisión.</p></details>}{analysis.observations.length?analysis.observations.map(observation=>{const review=latest(observation.id);return <section className="pedagogy-observation" key={observation.id}><div className="pedagogy-heading"><h3>{names[observation.skill]}{observation.error&&` · ${errors[observation.error]}`}</h3><span className="badge neutral">{review?({accepted:'Aceptada por ti',rejected:'Descartada',forgotten:'Dejada de usar'})[review.decision]:'Sin confirmar'}</span></div><p>{observation.description}</p>{observation.quotes.map((q,index)=><blockquote key={index}>{q.text}</blockquote>)}{review&&<p className="subtle-note">Tu revisión: {review.reason}</p>}<div className="pedagogy-actions"><button className="text-button" disabled={Boolean(busy)} onClick={()=>setSelected({analysis,observation,decision:'accepted'})}>Me representa</button><button className="text-button" disabled={Boolean(busy)} onClick={()=>setSelected({analysis,observation,decision:'rejected'})}>No me representa</button>{review?.decision==='accepted'&&<button className="text-button" disabled={Boolean(busy)} onClick={()=>setSelected({analysis,observation,decision:'forgotten'})}>Dejar de usar esta hipótesis</button>}{review?.decision==='accepted'&&observation.signal==='difficulty'&&<button className="button secondary" disabled={Boolean(busy)} onClick={()=>{void action('refuerzo',async()=>{const created=await window.tutor.startIntervention({analysisId:analysis.id,observationId:observation.id,minutes:10});setFocused(created.id);setTab('reinforcement');});}}>Probar un refuerzo</button>}</div></section>; }):<p className="subtle-note">No se han encontrado observaciones suficientes en este análisis. Eso no demuestra que el trabajo sea correcto ni que exista una dificultad.</p>}</article>)}</div>
    </>:tab==='profile'?<><section className="import-banner"><span className="import-banner-icon"><GitCompareArrows size={28}/></span><div><h2>Un perfil compartido por tus asignaturas.</h2><p>Solo usa observaciones que has aceptado. Repetir el análisis de un mismo trabajo no añade evidencias independientes. Se requieren varios trabajos, asignaturas y días para apoyar una hipótesis.</p></div></section><div className="pedagogy-profile">{data.skillProfiles.map(profile=><article className="pedagogy-panel" key={profile.skill}><h2>{names[profile.skill]}</h2><span className="badge neutral">{({unseen:'Sin observaciones','to-check':'Por comprobar','supported-hypothesis':'Hipótesis apoyada',mixed:'Evidencias diferentes',positive:'Observaciones positivas'})[profile.state]}</span><p>{profile.reason}</p><p>{profile.workCount} trabajos · {profile.dayCount} días · {profile.subjectIds.length} asignaturas · Confianza {profile.confidence==='medium'?'media':'baja'}</p>{profile.subjectIds.length>0&&<p>{profile.subjectIds.map(id=>data.subjects.find(s=>s.id===id)?.name).join(' · ')}</p>}<details><summary>Ver las evidencias</summary>{profile.analysisIds.map(id=>{const a=data.learningAnalyses.find(a=>a.id===id)!;return <section key={id}><h3>{data.subjects.find(s=>s.id===a.subjectId)?.name} · {sourceWork(data,a.source).title}</h3>{a.observations.filter(o=>profile.observationIds.includes(o.id)).map(o=><blockquote key={o.id}>{o.quotes.map(q=>q.text).join('\n')}</blockquote>)}</section>;})}</details></article>)}</div></>:<>{plan?<><label className="form-stack">Refuerzo<select aria-label="Refuerzo a consultar" value={plan.id} onChange={e=>setFocused(e.target.value)}>{plans.map(i=><option key={i.id} value={i.id}>{names[i.skill]} · {dateLabel(i.createdAt)}</option>)}</select></label><InterventionPanel key={plan.id} plan={plan} {...props}/></>:<Empty icon={<Lightbulb size={29}/>} title="Un refuerzo con una razón concreta">Revisa una observación y acepta una dificultad que quieras comprobar. Después podrás probar un refuerzo con práctica y una comprobación posterior.</Empty>}</>}
    {selected&&<ReviewDialog {...props} selected={selected} onClose={()=>setSelected(undefined)}/>}
    {record&&ref&&work&&<ObservationDialog {...props} source={ref} text={work.text} onClose={()=>setRecord(false)}/>}
    {deleting&&<Modal title="Borrar este análisis" onClose={()=>setDeleting(undefined)}><p className="modal-intro">Se borrarán sus observaciones, revisiones y refuerzos vinculados. El trabajo original se conserva.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setDeleting(undefined)}>Cancelar</button><button className="button danger" disabled={Boolean(busy)} onClick={()=>{void action('delete',async()=>{await window.tutor.deleteAnalysis(deleting.id);setDeleting(undefined);});}}>Borrar análisis y refuerzos</button></div></Modal>}
  </>;
}
function ReviewDialog({selected,data,refresh,notify,onClose}:{selected:{analysis:LearningAnalysis;observation:LearningObservation;decision:ObservationReview['decision']};onClose():void}&PageProps){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const responses=data.interventionResponses.filter(r=>data.interventions.find(i=>i.id===r.interventionId)?.observationId===selected.observation.id);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);setBusy(true);try{await window.tutor.reviewObservation({analysisId:selected.analysis.id,observationId:selected.observation.id,decision:selected.decision,reason:String(f.get('reason')),followUpResponseId:String(f.get('followup')??'')||null});await refresh();onClose();notify('Revisión guardada sin sobrescribir la anterior.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <Modal title="Contrastar la observación" onClose={()=>{if(!busy)onClose();}}><form className="form-stack" onSubmit={submit}><p>{selected.observation.description}</p><label>¿Por qué la aceptas o dejas de usarla?<textarea name="reason" required maxLength={2000} rows={4} placeholder="Qué ocurrió, qué estrategia usarías ahora o qué evidencia contradice la hipótesis…"/></label>{responses.length>0&&<label>Comprobación posterior<select aria-label="Comprobación posterior" name="followup"><option value="">Sin comprobación vinculada</option>{responses.map(r=><option key={r.id} value={r.id}>{dateLabel(r.createdAt)} · {r.answer} · {r.outcome==='correct'?'Resultado correcto':r.outcome==='incorrect'?'Por revisar':'Sin corrección automática'}</option>)}</select></label>}<p className="subtle-note">Tu revisión expresa una reflexión personal. La hipótesis y su historial se conservan; no cambian las notas ni el dominio del concepto.</p>{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy}><Check size={16}/> Guardar revisión</button></form></Modal>;
}
function ObservationDialog({source,text,refresh,notify,onClose}:{source:WorkInput;text:string;onClose():void}&PageProps){
  const [range,setRange]=useState({start:0,end:0}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);setBusy(true);try{await window.tutor.recordObservation({...source,skill:String(f.get('skill')) as LearningSkill,signal:String(f.get('signal')) as 'difficulty'|'strength',error:String(f.get('error')) as ErrorKind||null,quote:{...range,text:text.slice(range.start,range.end)},description:String(f.get('description'))});await refresh();onClose();notify('Observación enlazada con tu trabajo.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <Modal title="Una observación con evidencia" onClose={()=>{if(!busy)onClose();}} wide><form className="form-stack" onSubmit={submit}><label>Selecciona el fragmento que la justifica<textarea aria-label="Seleccionar evidencia" readOnly value={text} rows={8} onSelect={e=>setRange({start:e.currentTarget.selectionStart,end:e.currentTarget.selectionEnd})}/></label><p>{range.end-range.start} caracteres seleccionados</p><label>Habilidad<select aria-label="Habilidad de la observación" name="skill">{SKILLS.map(s=><option key={s} value={s}>{names[s]}</option>)}</select></label><div className="form-row"><label>Señal<select name="signal"><option value="difficulty">Dificultad por comprobar</option><option value="strength">Posible fortaleza</option></select></label><label>Tipo de error<select name="error"><option value="">Sin tipo de error</option>{Object.entries(errors).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label></div><label>¿Qué observas?<textarea name="description" required maxLength={1500} rows={3}/></label>{error&&<p role="alert">{error}</p>}<button className="button primary" disabled={busy||range.end<=range.start}>Guardar observación</button></form></Modal>;
}
function InterventionPanel({plan,data,refresh,notify}:{plan:Intervention}&PageProps){
  const responses=data.interventionResponses.filter(r=>r.interventionId===plan.id), initial=responses.filter(r=>!plan.activities.find(a=>a.id===r.activityId)?.followUp), followup=responses.find(r=>plan.activities.find(a=>a.id===r.activityId)?.followUp);
  const [busy,setBusy]=useState(false);
  async function reflect(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);setBusy(true);try{await window.tutor.reflectIntervention({interventionId:plan.id,whatHelped:String(f.get('help')),reflection:String(f.get('reflection')),nextStep:String(f.get('next'))});await refresh();notify('Reflexión conservada con el refuerzo.');}catch(e){notify(errorMessage(e),true);}finally{setBusy(false);}}
  return <><section className="pedagogy-panel"><h2>Practicar {names[plan.skill].toLowerCase()}</h2><p>{plan.explanation}</p><div className="hint"><Lightbulb size={18}/><p>{plan.help}</p></div><p>Tiempo previsto: {plan.minutes} minutos · Comprobación posterior: {plan.followUpOn}</p><p>{followup?followup.outcome==='correct'?'La comprobación posterior tiene un resultado correcto. Revisa si cambia tu hipótesis; un solo refuerzo no demuestra consolidación.':'La comprobación posterior se conserva para revisar la estrategia.':initial.length===2?initial.every(r=>r.outcome==='correct')?'La práctica inicial tiene resultados correctos. Falta comprobarlo en otro día.':'La práctica inicial necesita reflexión. Revisa la ayuda y vuelve a contrastar la hipótesis.':'Empieza por las dos actividades de práctica.'}</p></section><div className="pedagogy-list">{plan.activities.map(activity=><ActivityCard key={activity.id} activity={activity} plan={plan} response={responses.find(r=>r.activityId===activity.id)} locked={activity.followUp&&(dayKey()<plan.followUpOn||initial.length<2)} refresh={refresh} notify={notify}/>)}</div><section className="pedagogy-panel"><h2>Qué ayuda funcionó</h2><form className="form-stack" onSubmit={reflect}><label>¿Qué explicación o estrategia te ayudó?<textarea name="help" required maxLength={2000} rows={2}/></label><label>¿Por qué fallaste y qué harías ahora?<textarea name="reflection" maxLength={2000} rows={3}/></label><label>Siguiente paso<input name="next" required maxLength={2000}/></label><button className="button secondary" disabled={busy}>Guardar reflexión</button></form>{data.interventionReviews.filter(r=>r.interventionId===plan.id).map(r=><blockquote key={r.id}><strong>{dateLabel(r.createdAt)} · {r.whatHelped}</strong><p>{r.reflection}</p><p>Siguiente paso: {r.nextStep}</p></blockquote>)}</section></>;
}
function ActivityCard({activity,plan,response,locked,refresh,notify}:{activity:PracticeActivity;plan:Intervention;response:PageProps['data']['interventionResponses'][number]|undefined;locked:boolean;refresh():Promise<void>;notify:PageProps['notify']}){
  const [answer,setAnswer]=useState(''),[hint,setHint]=useState(false),[busy,setBusy]=useState(false),[started]=useState(Date.now());
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);try{await window.tutor.answerIntervention({interventionId:plan.id,activityId:activity.id,answer,hints:hint?1:0,durationSeconds:Math.min(86400,Math.max(0,Math.floor((Date.now()-started)/1000)))});await refresh();}catch(e){notify(errorMessage(e),true);}finally{setBusy(false);}}
  return <article className="pedagogy-panel"><span className="eyebrow">{activity.followUp?'COMPROBACIÓN EN OTRO DÍA':'PRÁCTICA ESPECÍFICA'}</span><h3>{activity.statement}</h3>{response?<><p className="pedagogy-original">Tu respuesta: {response.answer}</p><span className={`badge ${response.outcome==='correct'?'green':'neutral'}`}>{response.outcome==='correct'?'Correcto':response.outcome==='incorrect'?'Revisar':'Sin corregir automáticamente'}</span><p>{response.feedback}</p><p>{response.hints} pistas · {response.durationSeconds} segundos · {dateLabel(response.createdAt)}</p></>:locked?<p className="subtle-note">Disponible desde {plan.followUpOn}, después de completar las dos prácticas. Esta espera permite comprobar qué recuerdas.</p>:<form className="form-stack" onSubmit={submit}><label>Tu respuesta<textarea aria-label={`Respuesta al refuerzo ${activity.id}`} value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={20000} required rows={activity.kind==='open'?4:2}/></label>{hint&&<div className="hint"><Lightbulb size={18}/><p>{activity.hint}</p></div>}<div className="pedagogy-actions"><button type="button" className="text-button" disabled={hint} onClick={()=>setHint(true)}>Pedir una pista</button><button className="button primary" disabled={busy||!answer.trim()}>Guardar y comprobar</button></div></form>}</article>;
}
