import { useState, type FormEvent } from 'react';
import { ArrowRight, CalendarDays, Check, CheckCircle2, Clock3, Compass, Info, ListChecks, PencilLine, Plus, RotateCcw, Trash2 } from 'lucide-react';
import type { PlanItem, StudyTask, TaskInput } from '../../shared/types';
import { dayKey } from '../../shared/calendar';
import { Empty, Modal, PageTitle, Spinner, SubjectRequired, dateLabel, errorMessage, type PageProps } from '../ui';
import { outcomeName } from './Practice';
import { CheckReferences } from './Curriculum';

function calendarLabel(value: string | null) {
  if (!value) return 'Sin fecha prevista';
  const [year, month, day] = value.split('-').map(Number);
  return new Intl.DateTimeFormat('es', { day: 'numeric', month: 'short' }).format(new Date(year, month - 1, day, 12));
}

export default function Plan(props: PageProps) {
  const { data, subject, refresh, notify, navigate, onNewSubject } = props;
  const [tab, setTab] = useState<'today' | 'reviews' | 'tasks'>('today');
  const [editing, setEditing] = useState<StudyTask | 'new'>();
  const [deleting, setDeleting] = useState<StudyTask>();
  const [evidence, setEvidence] = useState<{ title: string; reason: string; ids: string[] }>();
  const [busy, setBusy] = useState(false);
  const [taskQuery, setTaskQuery] = useState<'pending' | 'completed' | 'all'>('pending');
  if (!subject) return <SubjectRequired onNewSubject={onNewSubject} />;
  const today = dayKey();
  const plan = data.plans.find(p => p.subjectId === subject.id);
  const concepts = data.concepts.filter(c => c.subjectId === subject.id);
  const reviews = data.reviews.filter(r => concepts.some(c => c.id === r.conceptId)).slice().sort((a, b) => a.nextDate.localeCompare(b.nextDate));
  const tasks = data.tasks.filter(t => t.subjectId === subject.id).slice().sort((a, b) => (a.dueDate ?? '9999').localeCompare(b.dueDate ?? '9999'));
  const pending = tasks.filter(t => t.status === 'pending');
  const due = reviews.filter(r => r.nextDate <= today);
  async function action(work: () => Promise<unknown>, message?: string) {
    if (busy) return; setBusy(true);
    try { await work(); await refresh(); if (message) notify(message); }
    catch (failure) { notify(errorMessage(failure), true); } finally { setBusy(false); }
  }
  function open(item: PlanItem) {
    if (item.kind === 'task') { setTab('tasks'); setTaskQuery('pending'); setEditing(tasks.find(t => t.id === item.targetId)); }
    else if (item.kind === 'session') navigate('sessions');
    else if (item.kind === 'diagnostic') navigate('diagnostic');
    else if(item.kind==='project')navigate('connections',item.targetId);
    else navigate('practice', item.targetId);
  }
  return <><PageTitle eyebrow={subject.name} title="Un plan que tenga sentido para ti." description="Prioriza tus tareas, comprueba lo que recuerdas y reserva un rato para practicar." action={<button className="button secondary" onClick={() => setEditing('new')}><Plus size={17} /> Añadir tarea</button>} />
    <div className="tabs plan-tabs"><button className={tab === 'today' ? 'selected' : ''} onClick={() => setTab('today')}><CalendarDays size={17} /> Hoy</button><button className={tab === 'reviews' ? 'selected' : ''} onClick={() => setTab('reviews')}><RotateCcw size={17} /> Repasos <span>{due.length}</span></button><button className={tab === 'tasks' ? 'selected' : ''} onClick={() => setTab('tasks')}><ListChecks size={17} /> Mis tareas <span>{pending.length}</span></button></div>
    {tab === 'today' ? <div className="plan-layout"><section className="daily-plan"><div className="section-heading"><h2>{new Intl.DateTimeFormat('es', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</h2><span className="time-chip"><Clock3 size={14} /> {plan?.items.reduce((sum, item) => sum + item.minutes, 0) ?? 0} min propuestos</span></div>{plan?.items.length ? plan.items.map((item, index) => <article className="plan-item" key={item.id}><span className="plan-step">{String(index + 1).padStart(2, '0')}</span><div className="plan-item-content"><div className="plan-item-heading"><span className="eyebrow">{item.kind === 'task' ? 'TAREA PRÓXIMA' : item.kind==='project'?'PROYECTO COMPARTIDO':item.kind === 'diagnostic' ? 'EVALUACIÓN INICIAL' : 'PRÁCTICA Y REPASO'}</span><span><Clock3 size={13} /> {item.minutes} min</span></div><h3>{item.title}</h3><p>{item.reason}</p><div className="plan-item-actions"><button className="button primary" onClick={() => open(item)}>{item.kind === 'task' ? 'Revisar tarea' : 'Empezar'}<ArrowRight size={15} /></button>{item.evidenceIds.length > 0 && <button className="text-button" onClick={() => setEvidence({ title: item.title, reason: item.reason, ids: item.evidenceIds })}>Ver {item.evidenceIds.length} evidencias</button>}</div></div></article>) : <Empty icon={<CalendarDays size={28} />} title="Hoy puedes elegir tu siguiente objetivo" action={<div className="empty-actions"><button className="button primary" onClick={() => navigate('progress')}>Revisar conceptos</button><button className="button secondary" onClick={() => setEditing('new')}>Añadir una tarea</button></div>}>No hay repasos vencidos ni tareas próximas que priorizar. Puedes seguir practicando o añadir un objetivo con fecha.</Empty>}</section><aside><section className="plan-budget"><span className="feature-icon sage"><Clock3 size={23} /></span><h3>Tu tiempo disponible</h3><p>El plan se ajusta al tiempo que elijas. Una tarea larga puede repartirse entre varias sesiones.</p><label>Minutos de estudio<select aria-label="Minutos de estudio diarios" disabled={busy} value={data.settings.dailyMinutes} onChange={event => { const minutes = Number(event.target.value); void action(() => window.tutor.updateSettings({ dailyMinutes: minutes })); }}>{Array.from(new Set([10, 20, 30, 45, 60, data.settings.dailyMinutes])).sort((a, b) => a - b).map(minutes => <option key={minutes} value={minutes}>{minutes} minutos</option>)}</select></label><div className="plan-counts"><span><strong>{due.length}</strong> repasos para comprobar</span><span><strong>{pending.length}</strong> tareas pendientes</span></div></section><div className="context-tip"><Info size={20} /><h3>El porqué está a la vista.</h3><p>Las fechas organizan las tareas. Los ejercicios comprobados orientan los repasos y el refuerzo. La falta de evidencias se presenta como algo que comprobar.</p></div></aside></div>
    : tab === 'reviews' ? <><div className="review-intro"><RotateCcw size={21} /><div><h2>Volver a recordar, sin mirar la solución.</h2><p>Los intervalos iniciales son de 1, 3, 7, 14 y 30 días. Se amplían con aciertos sin pistas en días distintos y vuelven a un día cuando aparece una dificultad.</p></div></div>{reviews.length ? <div className="review-list">{reviews.map(review => { const concept = concepts.find(c => c.id === review.conceptId)!; const isDue = review.nextDate <= today; return <article className={`review-card ${isDue ? 'is-due' : ''}`} key={review.conceptId}><span className={`feature-icon ${isDue ? 'amber' : 'sage'}`}><RotateCcw size={21} /></span><div className="review-card-content"><div className="review-card-heading"><h3>{concept.name}</h3><span className={`badge ${isDue ? 'orange' : 'neutral'}`}>{isDue ? 'Toca comprobar' : `Próximo: ${calendarLabel(review.nextDate)}`}</span></div><p>{review.reason}</p><span className="review-date">{isDue ? `Previsto: ${calendarLabel(review.nextDate)}` : 'Puedes repasar antes si lo necesitas.'} · Intervalo: {review.intervalDays} días</span><button className="text-button" onClick={() => setEvidence({ title: `Repaso · ${concept.name}`, reason: review.reason, ids: review.evidenceIds })}>Ver el porqué <ArrowRight size={14} /></button></div><button className="button secondary" onClick={() => navigate('practice', concept.id)}>Repasar <ArrowRight size={15} /></button></article>; })}</div> : <Empty icon={<RotateCcw size={29} />} title="Tu primer intento pondrá en marcha el repaso" action={<button className="button primary" onClick={() => navigate('practice')}>Empezar a practicar</button>}>Los ejercicios comprobados permiten programar la siguiente comprobación. Las autoevaluaciones quedan en el historial y no amplían los intervalos.</Empty>}<p className="subtle-note"><Info size={15} /> La fecha propone una nueva comprobación. Un repaso pendiente no demuestra que hayas olvidado el concepto.</p></>
    : <><div className="task-toolbar"><h2>Tareas de {subject.name}</h2><label>Mostrar<select aria-label="Filtrar tareas" value={taskQuery} onChange={event => setTaskQuery(event.target.value as typeof taskQuery)}><option value="pending">Pendientes</option><option value="completed">Terminadas</option><option value="all">Todas</option></select></label></div><div className="task-list">{tasks.filter(t => taskQuery === 'all' || t.status === taskQuery).map(task => <article className={`task-card ${task.status === 'completed' ? 'completed' : ''}`} key={task.id}><button className="task-check" aria-label={task.status === 'completed' ? `Reabrir ${task.title}` : `Marcar terminada ${task.title}`} disabled={busy} onClick={() => { void action(() => window.tutor.completeTask({ id: task.id, completed: task.status !== 'completed' })); }}>{task.status === 'completed' ? <CheckCircle2 size={22} /> : <span />}</button><div className="task-content"><h3>{task.title}</h3>{task.lms && <span className="badge neutral">Moodle{data.lmsItems.find(i => i.id === task.lms!.itemId)?.active === false ? " · Retirada" : ""}</span>}{task.notes && <p>{task.notes}</p>}<div className="task-meta"><span><CalendarDays size={13} />{calendarLabel(task.dueDate)}</span><span><Clock3 size={13} />{task.estimatedMinutes} min previstos</span>{task.status === 'pending' && task.dueDate !== null && task.dueDate < today && <span className="overdue-label">Revisar fecha</span>}{task.status === 'completed' && <span>Terminada {dateLabel(task.completedAt!)}</span>}</div>{task.conceptIds.length > 0 && <div className="task-concepts">{task.conceptIds.map(id => <span className="prerequisite-chip" key={id}>{concepts.find(c => c.id === id)?.name}</span>)}</div>}</div><div className="task-actions"><button className="icon-button" aria-label={`Editar ${task.title}`} onClick={() => setEditing(task)}><PencilLine size={17} /></button><button className="icon-button danger-hover" aria-label={`Eliminar ${task.title}`} onClick={() => setDeleting(task)}><Trash2 size={17} /></button></div></article>)}</div>{!tasks.some(t => taskQuery === 'all' || t.status === taskQuery) && <Empty icon={<ListChecks size={29} />} title={taskQuery === 'completed' ? 'Todavía no hay tareas terminadas' : 'Un objetivo concreto ayuda a empezar'} action={<button className="button primary" onClick={() => setEditing('new')}><Plus size={17} /> Añadir tarea</button>}>Añade una entrega, una prueba o un objetivo personal. Tú decides su fecha y cuándo marcarlo como terminado.</Empty>}<p className="subtle-note"><Info size={15} /> Las tareas pueden venir de Moodle o ser objetivos personales. Marcarlas como terminadas no demuestra dominio ni modifica una nota.</p></>}
    {editing && <TaskEditor {...props} task={editing === 'new' ? undefined : editing} onClose={() => setEditing(undefined)} />}
    {deleting && <Modal title="¿Eliminar esta tarea?" onClose={() => { if (!busy) setDeleting(undefined); }}><p className="modal-intro">«{deleting.title}» dejará de aparecer en el plan. Los ejercicios vinculados se conservarán.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={() => setDeleting(undefined)}>Cancelar</button><button className="button danger" disabled={busy} onClick={() => { void action(async () => { await window.tutor.deleteTask(deleting.id); setDeleting(undefined); }, 'Tarea eliminada del plan.'); }}>Eliminar tarea</button></div></Modal>}
    {evidence && <Modal title={`Evidencias · ${evidence.title}`} onClose={() => setEvidence(undefined)} wide><p className="modal-intro">{evidence.reason}</p>{evidence.ids.map(id => { const attempt = data.attempts.find(a => a.id === id); return attempt && <article className="evidence-card" key={id}><div><CheckCircle2 size={17} /><strong>{outcomeName(attempt.outcome)}</strong><span>{dateLabel(attempt.createdAt)} · {attempt.hints} pistas</span></div><h3>{attempt.statement}</h3><p>Tu respuesta: {attempt.answer}</p><p>{attempt.feedback}</p><p className="history-meta">Evidencia {attempt.id.slice(0, 8)}</p></article>; })}</Modal>}
  </>;
}

function TaskEditor({ data, subject, task, refresh, notify, onClose }: PageProps & { task?: StudyTask; onClose(): void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    const input: TaskInput = { subjectId: subject!.id, title: String(form.get('title')), notes: String(form.get('notes')), dueDate: String(form.get('date')) || null, estimatedMinutes: Number(form.get('minutes')), conceptIds: form.getAll('concepts').map(String), unitId: String(form.get('unit')) || null, curriculumIds: form.getAll('curriculum').map(String) };
    try { if (task) await window.tutor.updateTask({ ...input, id: task.id }); else await window.tutor.createTask(input); await refresh(); notify(task ? 'Tarea actualizada.' : 'Tarea añadida a tu plan.'); onClose(); }
    catch (failure) { setError(errorMessage(failure)); } finally { setBusy(false); }
  }
  const concepts = data.concepts.filter(c => c.subjectId === subject!.id);
  return <Modal title={task ? 'Editar tarea' : 'Una tarea para tu plan'} onClose={() => { if (!busy) onClose(); }}><form className="form-stack" onSubmit={submit}><label>Título de la tarea<input name="title" autoFocus required maxLength={120} defaultValue={task?.title ?? ''} placeholder="Ej. Preparar la prueba de la unidad 2" /></label><div className="form-row"><label>Fecha prevista<input name="date" type="date" min="2000-01-01" max="2100-12-31" defaultValue={task ? task.dueDate ?? '' : dayKey()} /></label><label>Tiempo previsto (minutos)<input name="minutes" type="number" required min={5} max={120} step={1} defaultValue={task?.estimatedMinutes ?? 20} /></label></div><label>¿Qué necesitas hacer?<textarea name="notes" rows={3} maxLength={4000} defaultValue={task?.notes ?? ''} placeholder="Los pasos que quieres completar, el material que necesitas…" /></label>{concepts.length > 0 && <fieldset className="prerequisite-options"><legend>Conceptos relacionados <span className="optional">opcional</span></legend>{concepts.map(c => <label key={c.id}><input type="checkbox" name="concepts" value={c.id} defaultChecked={task?.conceptIds.includes(c.id)} />{c.name}</label>)}</fieldset>}<label>Unidad relacionada<select name="unit" defaultValue={task?.unitId ?? ''}><option value="">Sin unidad vinculada</option>{data.units.filter(u => u.subjectId === subject!.id).sort((a, b) => a.position - b.position).map(u => <option key={u.id} value={u.id}>{u.title}</option>)}</select></label><CheckReferences name="curriculum" legend="Currículo relacionado" rows={data.curriculum.filter(c => c.subjectId === subject!.id).map(c => ({ id: c.id, label: `${c.code ? `${c.code} · ` : ''}${c.title}` }))} selected={task?.curriculumIds} />{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? <Spinner label="Guardando…" /> : <><Check size={16} /> Guardar tarea</>}</button></div></form></Modal>;
}
