import { useState, type FormEvent } from 'react';
import { BookOpen, FolderHeart, Plus, Trash2 } from 'lucide-react';
import type { PortfolioEntry, PortfolioInput } from '../../shared/education';
import { Empty, Modal, PageTitle, Spinner, SubjectRequired, dateLabel, errorMessage, type PageProps } from '../ui';
import { CheckReferences } from './Curriculum';

const kinds = { work: 'Trabajo', project: 'Proyecto', reflection: 'Reflexión', attempt: 'Ejercicio' };
export default function Portfolio(props: PageProps) {
  const { data, subject, refresh, notify, onNewSubject } = props;
  const [adding, setAdding] = useState(false); const [selected, setSelected] = useState<PortfolioEntry>(); const [deleting, setDeleting] = useState<PortfolioEntry>(); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false);
  if (!subject) return <SubjectRequired onNewSubject={onNewSubject} />;
  const entries = data.portfolio.filter(p => p.subjectId === subject.id && `${p.title} ${p.content} ${p.reflection}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))).slice().reverse();
  return <><PageTitle eyebrow={subject.name} title="Trabajos que cuentan tu progreso." description="Conserva proyectos, reflexiones y ejercicios que has resuelto por ti mismo." action={<button className="button primary" onClick={() => setAdding(true)}><Plus size={17} /> Añadir al portfolio</button>} />
    <section className="review-intro"><FolderHeart size={24} /><div><h2>Un acierto autónomo puede convertirse en evidencia.</h2><p>Los ejercicios comprobados correctos sin pistas se guardan automáticamente, una vez por enunciado y concepto. También puedes añadir trabajos y proyectos con las evidencias que elijas.</p></div></section><label className="search-field history-search"><input aria-label="Buscar en el portfolio" placeholder="Buscar un proyecto, una reflexión o un ejercicio…" value={query} onChange={event => setQuery(event.target.value)} /></label>
    {entries.length ? <div className="card-library">{entries.map(entry => <article className="education-card" key={entry.id}><div className="education-heading"><span className="eyebrow">{kinds[entry.kind]} · {entry.automatic ? 'Guardado automático' : 'Selección personal'}</span><button className="icon-button danger-hover" aria-label={`Eliminar del portfolio ${entry.title}`} onClick={() => setDeleting(entry)}><Trash2 size={16} /></button></div><h3>{entry.title}</h3><p>{entry.content.slice(0, 250)}{entry.content.length > 250 ? '…' : ''}</p>{entry.reflection && <p className="portfolio-reflection">{entry.reflection}</p>}<div className="education-tags">{entry.conceptIds.map(id => <span className="prerequisite-chip" key={id}>{data.concepts.find(c => c.id === id)?.name}</span>)}</div><p className="bank-help">{dateLabel(entry.createdAt)} · {entry.evidenceIds.length} evidencias</p><button className="text-button" onClick={() => setSelected(entry)}><BookOpen size={15} /> Leer trabajo y evidencias</button></article>)}</div> : <Empty icon={<FolderHeart size={28} />} title="Tu portfolio empieza con una evidencia" action={<button className="button primary" onClick={() => setAdding(true)}>Añadir un trabajo</button>}>Aquí aparecerán tus ejercicios autónomos y los trabajos que quieras conservar. Todas las entradas se incluyen en tu copia cifrada.</Empty>}
    {adding && <PortfolioEditor {...props} onClose={() => setAdding(false)} />}
    {selected && <Modal title={selected.title} onClose={() => setSelected(undefined)} wide><div className="portfolio-document">{selected.content}</div>{selected.reflection && <div className="portfolio-reflection"><strong>Mi reflexión</strong><p>{selected.reflection}</p></div>}{selected.evidenceIds.length > 0 && <div className="section-heading"><h2>Evidencias vinculadas</h2></div>}{selected.evidenceIds.map(id => { const attempt = data.attempts.find(a => a.id === id); return attempt && <article className="evidence-card" key={id}><h3>{attempt.statement}</h3><p>Tu respuesta: {attempt.answer}</p><p>{attempt.feedback}</p><p className="history-meta">{dateLabel(attempt.createdAt)} · {attempt.hints} pistas · Evidencia {id.slice(0, 8)}</p></article>; })}</Modal>}
    {deleting && <Modal title="¿Retirar esta entrada del portfolio?" onClose={() => { if (!busy) setDeleting(undefined); }}><p className="modal-intro">Se borrará esta selección. Los intentos del historial se conservarán.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={() => setDeleting(undefined)}>Cancelar</button><button className="button danger" disabled={busy} onClick={async () => { setBusy(true); try { await window.tutor.deletePortfolio(deleting.id); await refresh(); setDeleting(undefined); } catch (failure) { notify(errorMessage(failure), true); } finally { setBusy(false); } }}>Retirar entrada</button></div></Modal>}
  </>;
}
function PortfolioEditor({ data, subject, refresh, notify, onClose }: PageProps & { onClose(): void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [query, setQuery] = useState(''); const [page, setPage] = useState(0); const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const evidence = data.attempts.filter(a => a.subjectId === subject!.id && `${a.statement} ${a.answer} ${a.feedback}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))).slice().reverse();
  const pageCount = Math.max(1, Math.ceil(evidence.length / 30));
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    const input: PortfolioInput = { subjectId: subject!.id, title: String(form.get('title')), kind: String(form.get('kind')) as PortfolioInput['kind'], content: String(form.get('content')), reflection: String(form.get('reflection')), conceptIds: form.getAll('concepts').map(String), evidenceIds: selectedIds };
    try { await window.tutor.savePortfolio(input); await refresh(); onClose(); notify('Entrada guardada en tu portfolio.'); } catch (failure) { setError(errorMessage(failure)); } finally { setBusy(false); }
  }
  return <Modal title="Conservar un trabajo" wide onClose={() => { if (!busy) onClose(); }}><form className="form-stack" onSubmit={submit}><label>Título del trabajo<input autoFocus name="title" required maxLength={120} /></label><label>Tipo de entrada<select name="kind"><option value="work">Trabajo</option><option value="project">Proyecto</option><option value="reflection">Reflexión</option></select></label><label>Contenido del trabajo<textarea name="content" rows={7} required maxLength={50000} /></label><label>Reflexión sobre el trabajo<textarea name="reflection" rows={3} maxLength={10000} placeholder="Qué aprendí, qué mejoraría y qué puedo demostrar…" /></label><CheckReferences name="concepts" legend="Conceptos relacionados" rows={data.concepts.filter(c => c.subjectId === subject!.id).map(c => ({ id: c.id, label: c.name }))} /><fieldset className="prerequisite-options"><legend>Evidencias del historial · {selectedIds.length} seleccionadas</legend><label className="reference-search">Buscar en todos mis ejercicios<input value={query} onChange={event => { setQuery(event.target.value); setPage(0); }} /></label>{evidence.slice(page * 30, (page + 1) * 30).map(attempt => <label key={attempt.id}><input type="checkbox" checked={selectedIds.includes(attempt.id)} disabled={!selectedIds.includes(attempt.id) && selectedIds.length >= 100} onChange={event => setSelectedIds(ids => event.target.checked ? [...ids, attempt.id] : ids.filter(id => id !== attempt.id))} />{dateLabel(attempt.createdAt)} · {attempt.statement.slice(0, 140)}</label>)}{!evidence.length && <p className="bank-help">No hay ejercicios con esa búsqueda.</p>}<div className="education-actions"><button type="button" className="text-button" disabled={page === 0} onClick={() => setPage(page - 1)}>Anteriores</button><span className="bank-help">Página {page + 1} de {pageCount}</span><button type="button" className="text-button" disabled={page + 1 >= pageCount} onClick={() => setPage(page + 1)}>Siguientes</button></div></fieldset>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? <Spinner /> : 'Guardar en portfolio'}</button></div></form></Modal>;
}
