import { useState, type FormEvent } from 'react';
import { ShieldCheck, Download, CheckCircle2, Cpu, HardDrive, LockKeyhole, ArrowDownToLine, Upload, Trash2, Sparkles, Eye, UserRound, FolderLock, Square } from 'lucide-react';
import { Modal, PageTitle, Spinner, errorMessage, type PageProps } from '../ui';

export default function Preferences({ data, subject, refresh, notify }: PageProps) {
  const [busy, setBusy] = useState(false);
  const [backup, setBackup] = useState<'export' | 'import'>();
  const [erase, setErase] = useState(false);
  const [deleteSubject, setDeleteSubject] = useState(false);
  const [confirmation, setConfirmation] = useState('');
  const [backupError, setBackupError] = useState('');
  const [format, setFormat] = useState<'encrypted' | 'json'>('encrypted');
  const model = data.model;
  const ready = ['ready', 'running'].includes(model.state);
  async function saveProfile(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true);
    try { await window.tutor.updateSettings({ name: String(form.get('name')), dailyMinutes: Number(form.get('minutes')) }); await refresh(); notify('Preferencias guardadas.'); }
    catch (error) { notify(errorMessage(error), true); } finally { setBusy(false); }
  }
  async function download() {
    try { await window.tutor.downloadModel(); await refresh(); notify('Tu tutor local está listo. Puedes trabajar sin conexión.'); }
    catch (error) { notify(errorMessage(error), true); await refresh(); }
  }
  async function backupAction(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const password = String(form.get('password') ?? ''); setBusy(true); setBackupError('');
    try {
      if (backup === 'export' && format === 'encrypted' && password !== String(form.get('repeat'))) throw new Error('Las contraseñas no coinciden.');
      const success = backup === 'export' ? await window.tutor.exportData({ format, ...(format === 'encrypted' ? { password } : {}) }) : await window.tutor.importData({ password });
      if (success) { await refresh(); setBackup(undefined); notify(backup === 'export' ? 'Copia guardada en la ubicación que has elegido.' : 'Historial restaurado.'); }
    } catch (error) { setBackupError(errorMessage(error)); } finally { setBusy(false); }
  }
  async function toggle(key: 'largeText' | 'highContrast', value: boolean) {
    try { await window.tutor.updateSettings({ [key]: value }); await refresh(); }
    catch (error) { notify(errorMessage(error), true); }
  }
  return <><PageTitle title="Tu espacio, a tu manera." description="Decide cómo estudiar y cómo proteger tu historial." />
    <section className="privacy-banner"><span><ShieldCheck size={30} /></span><div><h2>Tu aprendizaje permanece contigo.</h2><p>Los materiales, ejercicios y conversaciones se guardan cifrados en este ordenador. La IA procesa las consultas aquí.</p></div><span className="privacy-banner-tag"><CheckCircle2 size={15} /> Sin cuenta · Sin telemetría</span></section>
    <div className="settings-grid"><section className="settings-card model-settings"><div className="settings-card-heading"><span className="feature-icon sage"><Sparkles size={22} /></span><div><h2>Tu tutor local</h2><p>Una descarga inicial. Después, sin conexión.</p></div><span className={`badge ${ready ? 'green' : 'neutral'}`}><span />{ready ? 'Preparado' : model.state === 'downloading' ? 'Descargando' : 'Por activar'}</span></div>
      <div className="model-specs"><div><Cpu size={17} /><span>Modelo</span><strong>{model.modelName}</strong></div><div><HardDrive size={17} /><span>Descarga</span><strong>1,12 GB</strong></div><div><LockKeyhole size={17} /><span>Procesamiento</span><strong>En tu ordenador</strong></div></div>
      <p className="model-description">El motor de IA ya viene incluido. Al activar el tutor se descargará el modelo desde Hugging Face y se comprobará su integridad. Tus apuntes y preguntas permanecen aquí.</p>
      {model.state === 'downloading' ? <div className="download-progress" aria-live="polite"><div><strong>{model.progress}%</strong><span>{(model.downloadedBytes / 1000000000).toFixed(2).replace('.', ',')} de 1,12 GB</span></div><progress value={model.progress} max={100} aria-label="Descarga del modelo" /><p>{model.message}</p><button className="button secondary" onClick={() => { void window.tutor.cancelDownload(); }}><Square size={14} /> Cancelar descarga</button></div> : <div className="model-action"><span className={model.state === 'error' ? 'form-error' : ''}>{model.message}</span>{!ready && <button className="button primary" onClick={() => { void download(); }}><Download size={17} /> Descargar y activar IA local</button>}</div>}
      <p className="subtle-note">Este equipo tiene {model.ramGB} GB de RAM. La velocidad depende del procesador y de las aplicaciones abiertas.</p>
    </section><section className="settings-card"><div className="settings-card-heading"><span className="feature-icon blue"><UserRound size={22} /></span><div><h2>Mi perfil</h2><p>Lo justo para personalizar tu espacio.</p></div></div><form className="form-stack" onSubmit={saveProfile}><label>¿Cómo quieres que te llamemos?<input name="name" defaultValue={data.settings.name} placeholder="Tu nombre o un alias" maxLength={80} /></label><label>Tiempo habitual de estudio<select name="minutes" defaultValue={data.settings.dailyMinutes}>{[10, 20, 30, 45, 60].map(value => <option key={value} value={value}>{value} minutos</option>)}</select></label><button className="button secondary" disabled={busy}>Guardar preferencias</button></form></section>
    <section className="settings-card"><div className="settings-card-heading"><span className="feature-icon amber"><Eye size={22} /></span><div><h2>Lectura cómoda</h2><p>Adapta la interfaz a ti.</p></div></div><label className="toggle-row"><div><strong>Texto más grande</strong><span>Amplía el tamaño de lectura.</span></div><input type="checkbox" checked={data.settings.largeText} onChange={event => { void toggle('largeText', event.target.checked); }} /><span className="toggle" /></label><label className="toggle-row"><div><strong>Más contraste</strong><span>Refuerza textos y bordes.</span></div><input type="checkbox" checked={data.settings.highContrast} onChange={event => { void toggle('highContrast', event.target.checked); }} /><span className="toggle" /></label></section>
    <section className="settings-card"><div className="settings-card-heading"><span className="feature-icon violet"><FolderLock size={22} /></span><div><h2>Mis datos y copias</h2><p>Un historial que puedes llevar contigo.</p></div></div><p className="storage-path">{data.storagePath}</p><div className="data-actions"><button className="button secondary" onClick={() => { setBackupError(''); setFormat('encrypted'); setBackup('export'); }}><ArrowDownToLine size={17} /> Crear una copia</button><button className="button secondary" onClick={() => { setBackupError(''); setBackup('import'); }}><Upload size={17} /> Restaurar una copia</button></div><p className="subtle-note"><LockKeyhole size={14} /> La clave del historial está protegida por tu sesión de Windows. Las copias portables usan una contraseña propia.</p></section>
    <section className="settings-card connections-card"><h2>Conexiones externas</h2><p>La descarga del modelo y las consultas a los cursos de Moodle que conectes requieren Internet. La IA procesa tus materiales en este ordenador. Puedes elegir actualizaciones manuales o automáticas de Moodle con la app abierta.</p><span className="badge neutral"><span />{data.lmsConnections.filter(c => c.hasCredentials).length} cursos conectados</span></section></div>
    <section className="danger-zone"><div><h2>Gestionar el historial</h2><p>Puedes eliminar una asignatura o borrar los datos personales de esta instalación.</p></div><div className="data-actions">{subject && <button className="button secondary danger-text" onClick={() => setDeleteSubject(true)}>Eliminar «{subject.name}»</button>}<button className="button secondary danger-text" onClick={() => { setConfirmation(''); setErase(true); }}><Trash2 size={16} /> Borrar mis datos</button></div></section>
    <p className="version-footer">Tutor Local · Versión 0.13.0 · Diseñado para aprender con privacidad.</p>
    {backup && <Modal title={backup === 'export' ? 'Una copia de tu aprendizaje' : 'Restaurar tu historial'} onClose={() => { if (!busy) setBackup(undefined); }}><form className="form-stack" onSubmit={backupAction}>{backup === 'export' ? <><label>Formato<select value={format} onChange={event => setFormat(event.target.value as 'encrypted' | 'json')}><option value="encrypted">Copia cifrada y portable (.tutor)</option><option value="json">Historial JSON sin cifrar (.json)</option></select></label>{format === 'encrypted' ? <><p className="modal-intro">Esta contraseña protege la copia y permite abrirla en otro ordenador. Necesitarás conservarla para restaurar el historial.</p><label>Contraseña de la copia<input name="password" type="password" minLength={8} maxLength={256} required autoComplete="new-password" placeholder="Al menos 8 caracteres" /></label><label>Repite la contraseña<input name="repeat" type="password" minLength={8} maxLength={256} required autoComplete="new-password" /></label></> : <p className="export-notice"><LockKeyhole size={19} /> El JSON incluye tus materiales, conversaciones y ejercicios en texto legible. Elige una ubicación privada.</p>}</> : <><p className="modal-intro">La copia sustituirá las asignaturas y el historial de esta instalación. Puedes crear antes una copia del estado actual.</p><label>Contraseña de la copia <span className="optional">para archivos .tutor</span><input name="password" type="password" maxLength={256} autoComplete="off" placeholder="Déjala vacía si vas a importar un JSON" /></label></>}{backupError && <p className="form-error" role="alert">{backupError}</p>}<div className="modal-actions"><button className="button secondary" type="button" onClick={() => setBackup(undefined)} disabled={busy}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? <Spinner /> : backup === 'export' ? 'Elegir dónde guardar' : 'Elegir copia y restaurar'}</button></div></form></Modal>}
    {erase && <Modal title="Borrar mis datos personales" onClose={() => setErase(false)}><p className="modal-intro">Se eliminarán todas las asignaturas, materiales, conversaciones, ejercicios y preferencias de esta instalación. Las copias que hayas exportado y el modelo descargado se conservarán.</p><label className="form-stack">Escribe BORRAR para confirmar<input value={confirmation} onChange={event => setConfirmation(event.target.value)} placeholder="BORRAR" /></label><div className="modal-actions"><button className="button secondary" onClick={() => setErase(false)} disabled={busy}>Cancelar</button><button className="button danger" disabled={confirmation !== 'BORRAR' || busy} onClick={async () => { setBusy(true); try { await window.tutor.eraseData(); await refresh(); setErase(false); notify('Datos personales eliminados.'); } catch (error) { notify(errorMessage(error), true); } finally { setBusy(false); } }}>Borrar mis datos</button></div></Modal>}
    {deleteSubject && subject && <Modal title="Eliminar asignatura" onClose={() => setDeleteSubject(false)}><p className="modal-intro">Se eliminarán «{subject.name}» y todos sus materiales, conversaciones y ejercicios de esta instalación. También sus conexiones y los proyectos compartidos en los que haya participado, incluidas sus versiones y copias. Los trabajos originales de las otras asignaturas se conservan.</p><div className="modal-actions"><button className="button secondary" onClick={() => setDeleteSubject(false)}>Cancelar</button><button className="button danger" onClick={async () => { try { await window.tutor.deleteSubject(subject.id); await refresh(); setDeleteSubject(false); notify('Asignatura eliminada.'); } catch (error) { notify(errorMessage(error), true); } }}>Eliminar asignatura</button></div></Modal>}
  </>;
}
