import { useState, type FormEvent } from 'react';
import { FileChartColumn, Plus, Download, Trash2, RefreshCw, ArrowRight, Files } from 'lucide-react';
import type { LearningReport, ReportConcept, ReportInput, ReportKind } from '../../shared/reports';
import type { Attempt } from '../../shared/types';
import { dayKey, addDays } from '../../shared/calendar';
import { Badge, Empty, Modal, PageTitle, SubjectRequired, Spinner, confidenceNames, errorMessage, outcomeName, type PageProps } from '../ui';

const kinds: Record<ReportKind, string> = { weekly: 'Mi semana', unit: 'Fin de unidad', transition: 'Cambio de curso' };
const changes: Record<ReportConcept['change'], string> = { 'first-evidence': 'Primeras evidencias', improved: 'Mejora con ejercicios nuevos', regressed: 'Dificultad con ejercicios nuevos', stable: 'Sin cambio de estado', 'check-again': 'Conviene comprobar el recuerdo' };
function lastWeek() { const now = new Date(), start = addDays(dayKey(now), -((now.getDay() + 6) % 7) - 7); return { startsOn: start, endsOn: addDays(start, 6) }; }

export default function Reports(props: PageProps) {
  const { data, subject, refresh, notify } = props;
  const [kind, setKind] = useState<ReportKind>('weekly'), [selectedId, setSelectedId] = useState('');
  const [editor, setEditor] = useState<ReportInput>(), [deleting, setDeleting] = useState<LearningReport>(), [exporting, setExporting] = useState<LearningReport>();
  const [evidence, setEvidence] = useState<ReportConcept>(), [busy, setBusy] = useState(false), [exportFormat, setExportFormat] = useState<'json' | 'csv' | 'pdf'>('pdf');
  if (!subject) return <SubjectRequired onNewSubject={props.onNewSubject} />;
  const reports = data.learningReports.filter(r => r.subjectId === subject.id && r.kind === kind).slice().reverse();
  const report = reports.find(r => r.id === selectedId) ?? reports[0], preference = data.reportPreferences.find(p => p.subjectId === subject.id);
  async function act(action: () => Promise<unknown>, message: string) { setBusy(true); try { await action(); await refresh(); notify(message); } catch (error) { notify(errorMessage(error), true); } finally { setBusy(false); } }
  function draft(previous?: LearningReport): ReportInput { const earliest = data.attempts.filter(a => a.subjectId === subject!.id).map(a => dayKey(new Date(a.createdAt))).sort()[0] ?? dayKey(new Date(subject!.createdAt)); return previous ? { subjectId: previous.subjectId, kind: previous.kind, startsOn: previous.startsOn, endsOn: previous.endsOn, unitId: previous.unit?.id ?? null, targetCourse: previous.targetCourse, conceptIds: previous.kind === 'transition' ? previous.concepts.map(c => c.conceptId) : [], helpIds: previous.help.map(h => h.reviewId), reflection: previous.reflection, supersedesId: previous.id } : { subjectId: subject!.id, kind, ...(kind === 'transition' ? { startsOn: earliest > dayKey() ? dayKey() : earliest, endsOn: dayKey() } : lastWeek()), unitId: null, targetCourse: '', conceptIds: [], helpIds: [], reflection: '' }; }
  return <>
    <PageTitle eyebrow={subject.name} title="Lo que aprendiste, con sus evidencias." description="Revisa una semana, una unidad o lo que quieres conservar para el próximo curso." action={<button className="button primary" onClick={() => setEditor(draft())}><Plus size={17} /> Crear informe</button>} />
    <div className="report-auto"><div><strong>Resumen semanal automático</strong><p>Con la app abierta, se guardan las semanas cerradas con actividad registrada. Al volver, recupera las pendientes. También puedes preparar otros periodos.</p></div><label><input type="checkbox" checked={preference?.automaticWeekly ?? true} disabled={busy} onChange={event => { const automaticWeekly = event.target.checked; void act(() => window.tutor.configureReports({ subjectId: subject.id, automaticWeekly }), automaticWeekly ? 'Resumen semanal activado.' : 'Resumen semanal desactivado.'); }} /> Generar mi resumen semanal</label></div>
    <div className="tabs">{(Object.keys(kinds) as ReportKind[]).map(k => <button key={k} className={kind === k ? 'selected' : ''} onClick={() => { setKind(k); setSelectedId(''); }}><FileChartColumn size={16} /> {kinds[k]}</button>)}</div>
    {reports.length ? <div className="reports-layout"><aside className="report-list" aria-label="Informes guardados">{reports.map(r => <button key={r.id} className={`report-list-item ${report?.id === r.id ? 'selected' : ''}`} onClick={() => setSelectedId(r.id)}><strong>{r.title}</strong><span>{r.startsOn} a {r.endsOn}</span><small>Versión {r.revision} · {r.origin === 'automatic' ? 'Automático' : 'Preparado por ti'}{data.learningReports.some(n => n.supersedesId === r.id) ? ' · Histórica' : ''}</small></button>)}</aside><div className="report-detail">{report && <>
      <section className="report-heading"><span className="eyebrow">FOTOGRAFÍA GUARDADA · VERSIÓN {report.revision}</span><h2>{report.title}</h2><p>Estado al {report.endsOn}. Creado el {new Date(report.createdAt).toLocaleDateString('es')}. El informe conserva los ejercicios disponibles al prepararlo.</p><div className="report-actions"><button className="button secondary" disabled={busy} onClick={() => setExporting(report)}><Download size={16} /> Exportar informe</button><button className="button secondary" disabled={busy || data.learningReports.some(r => r.supersedesId === report.id)} onClick={() => setEditor(draft(report))}><RefreshCw size={16} /> Crear nueva versión</button><button className="icon-button" aria-label="Eliminar informe y versiones" disabled={busy} onClick={() => setDeleting(report)}><Trash2 size={17} /></button></div></section>
      {report.kind === 'transition' && <p className="report-notice">Has seleccionado {report.concepts.length} {report.concepts.length === 1 ? 'concepto' : 'conceptos'} para {report.targetCourse}. Se conservan sus ejercicios de apoyo y las ayudas elegidas. Comprueba estas estimaciones en el nuevo curso.</p>}
      <div className="report-stats"><div><strong>{report.stats.verified}</strong><span>{report.kind === 'transition' ? 'ejercicios de apoyo' : 'intentos comprobados'}</span></div><div><strong>{report.stats.personal}</strong><span>registros personales</span></div><div><strong>{report.stats.correctWithoutHints}</strong><span>aciertos sin pistas</span></div><div><strong>{report.stats.activeDays}</strong><span>días con ejercicios</span></div></div>
      <div className="report-overview"><div><h3>Qué mejoró</h3><p>{report.concepts.filter(c => c.change === 'improved').map(c => c.name).join(', ') || 'Todavía no hay cambios de estado apoyados en ejercicios nuevos.'}</p>{report.concepts.some(c => c.change === 'first-evidence') && <p>Primeras evidencias: {report.concepts.filter(c => c.change === 'first-evidence').map(c => c.name).join(', ')}.</p>}</div><div><h3>Qué sigue pendiente</h3><p>{report.concepts.filter(c => c.after.status !== 'consolidated').map(c => c.name).join(', ') || 'Las estimaciones de esta selección están consolidadas al cierre. Mantén las comprobaciones en otros días.'}</p></div></div>
      {report.stats.otherActivities > 0 && <details className="report-concept"><summary>Otros registros del periodo: {report.stats.otherActivities}</summary><p>Tarjetas, sesiones, tareas, proyectos o refuerzos registrados. Su finalización no modifica el dominio por sí sola.</p><ul>{report.activityEventIds.map(id => { const event = data.events.find(e => e.id === id); return <li key={id}>{event ? `${new Date(event.createdAt).toLocaleDateString('es')} · ${event.type === 'flashcard.reviewed' ? 'Repaso de tarjeta' : event.type === 'study.completed' ? 'Sesión revisada' : event.type === 'task.completed' ? 'Tarea finalizada' : event.type.startsWith('reinforcement.') ? 'Actividad de refuerzo' : event.type === 'activity.completed' ? 'Actividad de proyecto' : 'Reflexión registrada'}` : 'Registro histórico'} · {id.slice(0, 8)}</li>; })}</ul></details>}
      <h3 className="report-section-title">Conocimientos y próximos pasos</h3>{report.concepts.map(c => <article className="report-concept" key={c.conceptId}><div className="report-concept-heading"><h3>{c.name}</h3><span>Confianza {confidenceNames[c.after.confidence].toLowerCase()}</span></div><div className="report-state-change"><Badge status={c.before.status} /><ArrowRight size={15} aria-label="Pasa a" /><Badge status={c.after.status} /></div><p className="report-change-label">{changes[c.change]}</p><p>{c.after.reason}</p><div className="report-next-step"><strong>Qué practicar después</strong><p>{c.recommendation.reason}</p>{c.prerequisites.length > 0 && <p>Si la dificultad continúa, comprueba también: {c.prerequisites.map(p => p.name).join(', ')}.</p>}</div><div className="report-actions"><button className="button secondary" onClick={() => setEvidence(c)}><Files size={16} /> Ver ejercicios y comparar</button><button className="button secondary" onClick={() => props.navigate('practice', c.conceptId)}>Comprobar ahora <ArrowRight size={15} /></button></div></article>)}
      {report.unit && <section className="report-concept"><h3>Currículo de {report.unit.title}</h3>{report.unit.curriculum.length ? <ul>{report.unit.curriculum.map(c => <li key={c.id}><strong>{c.code}</strong> {c.title}</li>)}</ul> : <p>La unidad no tenía elementos curriculares vinculados al preparar el informe.</p>}</section>}
      {report.help.length > 0 && <section className="report-concept"><h3>Ayudas que elegiste conservar</h3>{report.help.map(h => <div className="report-help" key={h.reviewId}><p><strong>Qué me ayudó:</strong> {h.whatHelped}</p><p><strong>Siguiente paso:</strong> {h.nextStep}</p><small>Reflexión personal · {h.reviewId.slice(0, 8)}</small></div>)}</section>}
      {report.reflection && <section className="report-concept"><h3>Mi reflexión</h3><p className="report-original">{report.reflection}</p></section>}
      <p className="subtle-note">{Math.round(report.stats.exerciseSeconds / 60)} minutos registrados en los ejercicios de esta selección. Las autoevaluaciones y la finalización de tareas o proyectos no demuestran dominio. Este informe orienta el estudio y no es una calificación docente.</p>
    </>}</div></div> : <Empty icon={<FileChartColumn size={29} />} title="Una fotografía para decidir el siguiente paso" action={<button className="button primary" onClick={() => setEditor(draft())}>Preparar {kinds[kind].toLowerCase()}</button>}>Elige un periodo o una unidad. Para cambiar de curso, selecciona los conocimientos y ayudas que quieres conservar.</Empty>}
    {editor && <ReportEditor {...props} initial={editor} onClose={() => setEditor(undefined)} onSaved={r => { setKind(r.kind); setSelectedId(r.id); setEditor(undefined); }} />}
    {evidence && report && <EvidenceComparison concept={evidence} attempts={data.attempts.filter(a => [...evidence.before.evidenceIds, ...evidence.after.evidenceIds].includes(a.id))} onClose={() => setEvidence(undefined)} />}
    {deleting && <Modal title="Eliminar informe y versiones" onClose={() => { if (!busy) setDeleting(undefined); }}><p>Se eliminarán «{deleting.title}» y todas sus versiones de esta instalación. Los ejercicios originales se conservan.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={() => setDeleting(undefined)}>Cancelar</button><button className="button danger" disabled={busy} onClick={() => { void act(async () => { await window.tutor.deleteLearningReport(deleting.id); setDeleting(undefined); }, 'Informe y versiones eliminados.'); }}>Eliminar informe</button></div></Modal>}
    {exporting && <Modal title="Exportar informe" onClose={() => { if (!busy) setExporting(undefined); }}><p>El archivo será legible fuera de la aplicación. Incluye esta selección y sus evidencias; guárdalo donde decidas compartirlo.</p><label className="report-export-label">Formato<select aria-label="Formato" value={exportFormat} onChange={e => setExportFormat(e.target.value as typeof exportFormat)}><option value="pdf">PDF para leer o imprimir</option><option value="json">JSON con evidencias originales</option><option value="csv">CSV para hoja de cálculo</option></select></label><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={() => setExporting(undefined)}>Cancelar</button><button className="button primary" disabled={busy} onClick={() => { setBusy(true); void window.tutor.exportLearningReport({ id: exporting.id, format: exportFormat }).then(saved => { if (saved) { setExporting(undefined); notify('Informe exportado.'); } }).catch(e => notify(errorMessage(e), true)).finally(() => setBusy(false)); }}>{busy ? <Spinner label="Preparando archivo…" /> : 'Guardar archivo'}</button></div></Modal>}
  </>;
}

function ReportEditor(props: PageProps & { initial: ReportInput; onClose(): void; onSaved(report: LearningReport): void }) {
  const { data, subject, initial } = props, units = data.units.filter(u => u.subjectId === subject!.id), concepts = data.concepts.filter(c => c.subjectId === subject!.id);
  const defaultUnit = initial.kind === 'unit' ? initial.unitId ? units.find(u => u.id === initial.unitId) : units[0] : undefined;
  const [form, setForm] = useState<ReportInput>(() => ({ ...initial, unitId: defaultUnit?.id ?? null, startsOn: defaultUnit && !initial.unitId ? defaultUnit.startsOn ?? initial.startsOn : initial.startsOn, endsOn: defaultUnit && !initial.unitId ? defaultUnit.endsOn && defaultUnit.endsOn < dayKey() ? defaultUnit.endsOn : dayKey() : initial.endsOn }));
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const patch = (value: Partial<ReportInput>) => setForm(p => ({ ...p, ...value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const report = await window.tutor.createLearningReport(form); await props.refresh(); props.onSaved(report); props.notify('Informe guardado con sus evidencias.'); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title={initial.supersedesId ? 'Nueva versión del informe' : `Preparar informe: ${kinds[initial.kind]}`} onClose={() => { if (!busy) props.onClose(); }} wide><form className="form-stack" onSubmit={submit}>
    <p className="modal-intro">Se guardará el estado apoyado en ejercicios disponibles al cerrar el periodo. Una nueva versión conserva la anterior.</p>
    {initial.kind === 'unit' && <label>Unidad<select aria-label="Unidad del informe" value={form.unitId ?? ''} required onChange={e => { const unit = units.find(u => u.id === e.target.value)!; patch({ unitId: unit.id, startsOn: unit.startsOn ?? form.startsOn, endsOn: unit.endsOn && unit.endsOn < dayKey() ? unit.endsOn : dayKey() }); }}><option value="" disabled>Elige una unidad</option>{units.map(u => <option key={u.id} value={u.id}>{u.title}</option>)}</select></label>}
    <div className="form-row"><label>{initial.kind === 'weekly' ? 'Lunes de la semana' : 'Inicio del periodo'}<input aria-label="Inicio del informe" type="date" value={form.startsOn} max={dayKey()} required onChange={e => patch({ startsOn: e.target.value, ...(initial.kind === 'weekly' && e.target.value ? { endsOn: addDays(e.target.value, 6) } : {}) })} /></label><label>Fin del periodo<input aria-label="Fin del informe" type="date" value={form.endsOn} max={dayKey()} required readOnly={initial.kind === 'weekly'} onChange={e => patch({ endsOn: e.target.value })} /></label></div>
    {initial.kind === 'weekly' && <p className="subtle-note">El resumen abarca una semana cerrada, de lunes a domingo. Elige una semana anterior a la actual.</p>}
    {initial.kind === 'transition' && <><label>Curso de destino<input aria-label="Curso de destino" value={form.targetCourse ?? ''} onChange={e => patch({ targetCourse: e.target.value })} required maxLength={120} placeholder="Ej. Segundo curso, 2027–2028" /></label><fieldset className="report-selection"><legend>Qué conocimientos quieres conservar</legend>{concepts.map(c => <label key={c.id}><input type="checkbox" checked={form.conceptIds?.includes(c.id) ?? false} onChange={e => patch({ conceptIds: e.target.checked ? [...form.conceptIds ?? [], c.id] : form.conceptIds?.filter(id => id !== c.id) })} />{c.name}<Badge status={data.estimates.find(s => s.conceptId === c.id)!.status} /></label>)}</fieldset></>}
    {data.interventionReviews.some(r => r.subjectId === subject!.id) && <fieldset className="report-selection"><legend>Ayudas útiles que eliges conservar</legend>{data.interventionReviews.filter(r => r.subjectId === subject!.id).map(r => <label key={r.id}><input type="checkbox" checked={form.helpIds?.includes(r.id) ?? false} onChange={e => patch({ helpIds: e.target.checked ? [...form.helpIds ?? [], r.id] : form.helpIds?.filter(id => id !== r.id) })} /><span>{r.whatHelped || 'Mi reflexión de refuerzo'}<small>{new Date(r.createdAt).toLocaleDateString('es')}</small></span></label>)}</fieldset>}
    <label>Mi reflexión<textarea aria-label="Reflexión del informe" value={form.reflection ?? ''} onChange={e => patch({ reflection: e.target.value })} maxLength={4000} rows={3} placeholder="Qué quiero mantener, qué sigue costando y qué comprobaré después…" /></label>
    {error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={props.onClose}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? <Spinner label="Guardando…" /> : 'Guardar informe'}</button></div>
  </form></Modal>;
}
export function EvidenceComparison({ concept, attempts, onClose }: { concept: Pick<ReportConcept, 'name' | 'before' | 'after'>; attempts: Attempt[]; onClose(): void }) {
  const ordered = attempts.slice().sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  const [oldId, setOldId] = useState(ordered[0]?.id ?? ''), [newId, setNewId] = useState(ordered.at(-1)?.id ?? '');
  const old = attempts.find(a => a.id === oldId), recent = attempts.find(a => a.id === newId);
  const card = (a: Attempt | undefined) => a ? <article className="comparison-work"><div><strong>{new Date(a.createdAt).toLocaleDateString('es')}</strong><span>{outcomeName(a.outcome)} · {a.hints} pistas · {a.source === 'verified' ? 'Comprobado' : 'Autoevaluación'}</span></div><h3>{a.statement}</h3><p className="report-original">{a.answer}</p>{a.feedback && <p className="comparison-feedback">{a.feedback}</p>}<small>Evidencia {a.id}</small></article> : <p>Sin ejercicios comprobados en esta selección.</p>;
  return <Modal title={`Ejercicios y comparación: ${concept.name}`} onClose={onClose} wide><div className="report-state-change"><Badge status={concept.before.status} /><ArrowRight size={16} /><Badge status={concept.after.status} /></div><p>Compara tus respuestas originales y las ayudas utilizadas. Las preguntas pueden ser distintas; revisa sus enunciados al comparar.</p>{attempts.length ? <><div className="form-row"><label>Resolución anterior<select aria-label="Resolución anterior" value={oldId} onChange={e => setOldId(e.target.value)}>{ordered.map(a => <option key={a.id} value={a.id}>{a.createdAt.slice(0, 10)} · {a.statement.slice(0, 70)}</option>)}</select></label><label>Resolución posterior<select aria-label="Resolución posterior" value={newId} onChange={e => setNewId(e.target.value)}>{ordered.map(a => <option key={a.id} value={a.id}>{a.createdAt.slice(0, 10)} · {a.statement.slice(0, 70)}</option>)}</select></label></div>{oldId === newId && <p className="subtle-note">Hay una única resolución seleccionada. Elige otra para comparar cuando dispongas de más evidencias.</p>}<div className="report-comparison">{card(old)}{oldId !== newId && card(recent)}</div></> : <p className="inline-placeholder">Todavía no hay ejercicios comprobados que apoyen esta estimación.</p>}<div className="modal-actions"><button className="button secondary" onClick={onClose}>Cerrar</button></div></Modal>;
}
