import { useEffect, useState, type FormEvent } from 'react';
import { ArrowRight, BookOpen, CheckCircle2, Clock3, Pause, Play, Plus, Square, XCircle } from 'lucide-react';
import type { SessionInput, StudySession } from '../../shared/study';
import { sessionElapsed, sessionRemaining } from '../../shared/study';
import { Empty, Modal, PageTitle, Spinner, SubjectRequired, dateLabel, errorMessage, type PageProps } from '../ui';
import { CheckReferences } from './Curriculum';
import { outcomeName } from '../ui';

const statusNames = { running: 'En marcha', paused: 'Pausada', review: 'Revisión pendiente', completed: 'Revisada', cancelled: 'Interrumpida' };
const ratings = { unsure: 'Necesito ayuda', learning: 'Voy avanzando', confident: 'Me siento seguro/a' };
export function useStudyClock() {
  const [now, setNow] = useState(new Date());
  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 500); return () => clearInterval(timer); }, []);
  return now;
}
export function clockLabel(milliseconds: number) { const seconds = Math.ceil(milliseconds / 1000); return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }

export default function Sessions(props: PageProps) {
  const { data, subject, refresh, notify, navigate, onNewSubject } = props;
  const now = useStudyClock();
  const [creating, setCreating] = useState(false); const [selected, setSelected] = useState<StudySession>(); const [cancelling, setCancelling] = useState<StudySession>(); const [busy, setBusy] = useState(false);
  if (!subject) return <SubjectRequired onNewSubject={onNewSubject} />;
  const owned = data.studySessions.filter(s => s.subjectId === subject.id).slice().reverse();
  const pending = owned.find(s => ['running', 'paused', 'review'].includes(s.status));
  const done = owned.filter(s => ['completed', 'cancelled'].includes(s.status));
  const another = data.studySessions.find(s => s.status === 'running' && s.subjectId !== subject.id);
  async function action(work: () => Promise<unknown>) { if (busy) return; setBusy(true); try { await work(); await refresh(); } catch (failure) { notify(errorMessage(failure), true); } finally { setBusy(false); } }
  return <><PageTitle eyebrow={subject.name} title="Un objetivo. Un rato. Un paso más." description="Sesiones de 10, 20 o 30 minutos con una revisión de lo que aprendiste." action={<button className="button primary" disabled={Boolean(pending || another)} onClick={() => setCreating(true)}><Plus size={17} /> Nueva sesión</button>} />
    {another && <p className="subtle-note">Hay una sesión en marcha en {data.subjects.find(s => s.id === another.subjectId)?.name}. Puedes abrirla desde la barra superior y pausarla.</p>}
    {pending ? <div className="study-session-layout"><section className="study-active"><div className="education-heading"><span className="feature-icon sage"><Clock3 size={23} /></span><div><span className="eyebrow">{statusNames[pending.status]}</span><h2>{pending.goal}</h2></div><span className="time-chip">{pending.minutes} min previstos</span></div>{pending.status !== 'review' ? <><strong className="study-large-clock" aria-label="Tiempo restante de sesión">{clockLabel(sessionRemaining(pending, now))}</strong><p className="bank-help">Tiempo en sesión: {clockLabel(sessionElapsed(pending, now))}. El temporizador se pausa al cerrar la app o suspender el equipo.</p><div className="study-session-actions"><button className="button primary" disabled={busy || Boolean(another)} onClick={() => { void action(() => pending.status === 'running' ? window.tutor.pauseSession(pending.id) : window.tutor.resumeSession(pending.id)); }}>{pending.status === 'running' ? <><Pause size={16} /> Pausar sesión</> : <><Play size={16} /> Continuar sesión</>}</button><button className="button secondary" disabled={busy} onClick={() => { void action(() => window.tutor.finishSession(pending.id)); }}><Square size={15} /> Terminar y revisar</button><button className="text-button" onClick={() => navigate('practice', pending.conceptIds[0])}>Ir a practicar <ArrowRight size={15} /></button></div></> : <SessionReviewForm key={pending.id} {...props} session={pending} />}
      <SessionLinks {...props} session={pending} /><div className="study-session-records"><h3>Lo que has realizado durante esta sesión</h3><p>{pending.attemptIds.length} ejercicios · {pending.cardReviewIds.length} repasos de tarjetas</p>{pending.attemptIds.length > 0 && <button className="text-button" onClick={() => setSelected(pending)}>Ver ejercicios y evidencias <ArrowRight size={14} /></button>}</div><button className="text-button danger-text" disabled={busy} onClick={() => setCancelling(pending)}>Interrumpir y conservar lo realizado</button></section><aside className="context-tip"><h3>La revisión ayuda a decidir el siguiente paso.</h3><p>Explica qué aprendiste, qué estrategia funcionó y qué quieres volver a intentar.</p><p>Tu percepción se guarda junto a las evidencias. El tiempo y la autoevaluación no afirman dominio de un concepto.</p></aside></div> : <Empty icon={<Clock3 size={30} />} title="Elige algo concreto que quieras conseguir" action={<button className="button primary" disabled={Boolean(another)} onClick={() => setCreating(true)}>Preparar mi sesión</button>}>Puedes trabajar con apuntes, practicar, repasar tarjetas o preparar una tarea. La sesión conserva su objetivo y sus evidencias.</Empty>}
    <div className="section-heading"><h2>Sesiones anteriores</h2><span>{done.length} guardadas en este ordenador</span></div>{done.length ? <div className="education-list">{done.map(row => <article className="education-card" key={row.id}><div className="education-heading"><div><span className="eyebrow">{statusNames[row.status]} · {dateLabel(row.createdAt)}</span><h2>{row.goal}</h2></div><span className="time-chip">{clockLabel(sessionElapsed(row))} / {row.minutes} min</span></div>{row.review && <p>{row.review.learned}</p>}<p className="bank-help">{row.attemptIds.length} ejercicios · {row.cardReviewIds.length} tarjetas repasadas</p>{row.review && <p className="portfolio-reflection">Próximo paso: {row.review.nextStep}</p>}<button className="text-button" onClick={() => setSelected(row)}><BookOpen size={15} /> Ver sesión y evidencias</button></article>)}</div> : <p className="inline-placeholder">Tus sesiones revisadas e interrumpidas aparecerán aquí.</p>}
    {creating && <SessionEditor {...props} onClose={() => setCreating(false)} />}
    {selected && <SessionDetail {...props} session={selected} onClose={() => setSelected(undefined)} />}
    {cancelling && <Modal title="¿Interrumpir esta sesión?" onClose={() => { if (!busy) setCancelling(undefined); }}><p className="modal-intro">Se conservarán el objetivo, el tiempo confirmado y los ejercicios realizados. Podrás empezar una nueva sesión.</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={() => setCancelling(undefined)}>Volver</button><button className="button danger" disabled={busy} onClick={() => { void action(async () => { await window.tutor.cancelSession(cancelling.id); setCancelling(undefined); }); }}><XCircle size={16} /> Interrumpir sesión</button></div></Modal>}
  </>;
}

export function SessionEditor({ data, subject, refresh, notify, onClose, conceptId, minutes = 20 }: PageProps & { onClose(): void; conceptId?: string; minutes?: StudySession['minutes'] }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    const input: SessionInput = { subjectId: subject!.id, goal: String(form.get('goal')), minutes: Number(form.get('minutes')) as StudySession['minutes'], conceptIds: form.getAll('concepts').map(String), unitId: String(form.get('unit')) || null, taskId: String(form.get('task')) || null, materialIds: form.getAll('materials').map(String) };
    try { await window.tutor.startSession(input); await refresh(); onClose(); notify('Sesión iniciada. Puedes cambiar de pantalla y continuar trabajando.'); } catch (failure) { setError(errorMessage(failure)); } finally { setBusy(false); }
  }
  const concepts = data.concepts.filter(c => c.subjectId === subject!.id);
  return <Modal title="Preparar una sesión de estudio" wide onClose={() => { if (!busy) onClose(); }}><form className="form-stack" onSubmit={submit}><label>Objetivo de esta sesión<input autoFocus name="goal" required maxLength={500} defaultValue={conceptId ? `Practicar ${concepts.find(c => c.id === conceptId)?.name ?? subject!.name}` : ''} placeholder="Ej. Resolver dos problemas y explicar el paso que me cuesta" /></label><label>Duración de la sesión<select name="minutes" aria-label="Duración de la sesión" defaultValue={minutes}>{[10, 20, 30].map(value => <option key={value} value={value}>{value} minutos</option>)}</select></label><div className="form-row"><label>Unidad de la sesión<select name="unit" aria-label="Unidad de la sesión"><option value="">Sin unidad vinculada</option>{data.units.filter(u => u.subjectId === subject!.id).sort((a, b) => a.position - b.position).map(u => <option key={u.id} value={u.id}>{u.title}</option>)}</select></label><label>Tarea de la sesión<select name="task" aria-label="Tarea de la sesión"><option value="">Sin tarea vinculada</option>{data.tasks.filter(t => t.subjectId === subject!.id && t.status === 'pending').map(t => <option key={t.id} value={t.id}>{t.title}</option>)}</select></label></div><CheckReferences name="concepts" legend="Conceptos que quieres trabajar" rows={concepts.map(c => ({ id: c.id, label: c.name }))} selected={conceptId ? [conceptId] : []} /><CheckReferences name="materials" legend="Materiales que vas a utilizar" rows={data.materials.filter(m => m.subjectId === subject!.id).map(m => ({ id: m.id, label: `${m.name} · v${m.version}` }))} /><p className="bank-help">El objetivo y el temporizador se guardan en este ordenador. Al terminar tendrás una revisión breve.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? <Spinner /> : <><Play size={16} /> Iniciar sesión de estudio</>}</button></div></form></Modal>;
}
function SessionReviewForm({ session, refresh, notify }: PageProps & { session: StudySession }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(''); const form = new FormData(event.currentTarget);
    try { await window.tutor.completeSession({ id: session.id, review: { learned: String(form.get('learned')), difficulty: String(form.get('difficulty')), nextStep: String(form.get('next')), selfRating: String(form.get('rating')) as 'unsure' | 'learning' | 'confident' } }); await refresh(); notify('Revisión guardada con las evidencias de esta sesión.'); } catch (failure) { setError(errorMessage(failure)); } finally { setBusy(false); }
  }
  return <form className="form-stack session-review-form" onSubmit={submit}><p className="modal-intro">Has reservado {session.minutes} minutos y registrado {clockLabel(sessionElapsed(session))} en sesión. Dedica un momento a revisar el objetivo.</p><label>¿Qué has aprendido o conseguido?<textarea name="learned" rows={3} required maxLength={4000} placeholder="Cuenta algo que ahora puedes explicar o hacer…" /></label><label>¿Qué te costó y qué estrategia probaste?<textarea name="difficulty" rows={3} maxLength={4000} /></label><label>¿Cuál será tu siguiente paso?<textarea name="next" rows={2} required maxLength={2000} /></label><label>¿Cómo te ves después de esta sesión?<select name="rating" aria-label="Mi percepción después de la sesión" defaultValue="learning">{Object.entries(ratings).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><p className="bank-help">Esta percepción es una autoevaluación. Los ejercicios comprobados siguen sustentando las estimaciones de dominio.</p>{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy ? <Spinner /> : <><CheckCircle2 size={16} /> Guardar revisión de sesión</>}</button></form>;
}
function SessionLinks({ data, session }: PageProps & { session: StudySession }) {
  return <div className="study-session-links">{session.unitTitle && <p>Unidad: {session.unitTitle}{session.unitId ? '' : ' (enlace retirado)'}</p>}{session.taskTitle && <p>Tarea: {session.taskTitle}{session.taskId ? '' : ' (enlace retirado)'}</p>}<div className="education-tags">{session.conceptIds.map(id => <span className="prerequisite-chip" key={id}>{data.concepts.find(c => c.id === id)?.name}</span>)}</div>{session.materials.length > 0 && <p>Materiales utilizados: {session.materials.map(m => `${m.name} · v${m.version}`).join(', ')}</p>}</div>;
}
function SessionDetail(props: PageProps & { session: StudySession; onClose(): void }) {
  const { data, session, onClose } = props;
  return <Modal title={session.goal} onClose={onClose} wide><p className="modal-intro">{statusNames[session.status]} · {dateLabel(session.createdAt)} · {clockLabel(sessionElapsed(session))} en sesión</p><SessionLinks {...props} />{session.review && <section className="portfolio-reflection"><strong>Mi revisión · {ratings[session.review.selfRating]}</strong><p>{session.review.learned}</p>{session.review.difficulty && <p>Dificultad y estrategia: {session.review.difficulty}</p>}<p>Próximo paso: {session.review.nextStep}</p></section>}<h3 className="study-evidence-title">Ejercicios vinculados</h3>{session.attemptIds.map(id => { const attempt = data.attempts.find(a => a.id === id); return attempt && <article className="evidence-card" key={id}><div><strong>{outcomeName(attempt.outcome)}</strong><span>{attempt.source === 'verified' ? 'Comprobado' : 'Autoevaluación'} · {attempt.hints} pistas</span></div><h3>{attempt.statement}</h3><p>Tu respuesta: {attempt.answer}</p><p>{attempt.feedback}</p><p className="history-meta">{dateLabel(attempt.createdAt)} · Evidencia {attempt.id.slice(0, 8)}</p></article>; })}{!session.attemptIds.length && <p className="inline-placeholder">No hay ejercicios vinculados. El tiempo y la reflexión se conservan sin afirmar un aprendizaje comprobado.</p>}{session.cardReviewIds.length > 0 && <><h3 className="study-evidence-title">Repasos de tarjetas</h3>{session.cardReviewIds.map(id => { const review = data.cardReviews.find(r => r.id === id); const revision = review ? data.cardRevisions.find(r => r.cardId === review.cardId && r.revision === review.revision) : null; return review && revision && <article className="evidence-card" key={id}><h3>{revision.front}</h3><p>Versión {review.revision} · {{ again: 'Otra vez', hard: 'Me costó', good: 'Lo recordaba', easy: 'Muy fácil' }[review.rating]} · autoevaluación del recuerdo</p></article>; })}</>}</Modal>;
}

export function SessionTimerCard(props: PageProps & { conceptId: string }) {
  const { data, subject, conceptId, refresh, notify, navigate } = props;
  const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [minutes, setMinutes] = useState<StudySession['minutes']>([10, 20, 30].includes(data.settings.dailyMinutes) ? data.settings.dailyMinutes as StudySession['minutes'] : 20);
  const now = useStudyClock();
  const row = data.studySessions.find(s => s.subjectId === subject!.id && ['running', 'paused', 'review'].includes(s.status));
  const another = data.studySessions.some(s => s.subjectId !== subject!.id && s.status === 'running');
  async function pause() { setBusy(true); try { if (row?.status === 'running') await window.tutor.pauseSession(row.id); else if (row?.status === 'paused') await window.tutor.resumeSession(row.id); await refresh(); } catch (failure) { notify(errorMessage(failure), true); } finally { setBusy(false); } }
  return <><section className="session-card"><span className="feature-icon sage"><Clock3 size={22} /></span><h3>Un rato para aprender</h3><p>{row ? statusNames[row.status] : 'Elige un tiempo y un objetivo pequeño.'}</p>{!row && <div className="session-options">{([10, 20, 30] as const).map(value => <button key={value} className={minutes === value ? 'selected' : ''} onClick={() => setMinutes(value)}>{value} min</button>)}</div>}<strong className="session-clock">{clockLabel(row ? sessionRemaining(row, now) : minutes * 60000)}</strong>{row?.status === 'review' ? <button className="button primary" onClick={() => navigate('sessions')}>Revisar sesión <ArrowRight size={16} /></button> : row ? <><button className="button primary" disabled={busy || another} onClick={() => { void pause(); }}>{row.status === 'running' ? <><Pause size={16} /> Pausar sesión</> : <><Play size={16} /> Continuar sesión</>}</button><button className="text-button" onClick={() => navigate('sessions')}>Ver objetivo y terminar</button></> : <button className="button primary" disabled={another} onClick={() => setEditing(true)}><Play size={16} /> Empezar sesión</button>}<p className="session-objective">{row ? `Objetivo: ${row.goal}` : 'La sesión mantiene su tiempo y su objetivo cuando cambias de pantalla.'}</p></section>{editing && <SessionEditor {...props} conceptId={conceptId} minutes={minutes} onClose={() => setEditing(false)} />}</>;
}
