import assert from 'node:assert/strict';
import { randomBytes, randomUUID } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { createRequire } from 'node:module';
import { startMoodle } from './moodle-test-server.mjs';
const require = createRequire(import.meta.url);
const { Store } = require('../build/electron/store.js'), { Lms } = require('../build/electron/lms.js'), { LmsCredentials } = require('../build/electron/lms-credentials.js'), { retrieve } = require('../build/electron/retrieval.js');
const fixture = await startMoodle();
let store, lms;
try {
  await fixture.action('reset');
  const directory = resolve('.tools/test-data', randomUUID()); await mkdir(directory, { recursive: true }); const key = randomBytes(32);
  store = await Store.open(join(directory, 'history.tutor'), key, resolve('node_modules/sql.js/dist/sql-wasm.wasm'));
  lms = new Lms(store, new LmsCredentials(join(directory, 'credentials.tutor'), key));
  const subject = store.createDemo(); const initial = store.snapshot();
  const passwordDiscovery = await lms.discover({ siteUrl: fixture.siteUrl, username: 'fixturelearner', password: fixture.config.learnerPassword });
  assert.ok(passwordDiscovery.courses.some(c => c.id === fixture.config.courseId));
  const discovery = await lms.discover({ siteUrl: fixture.siteUrl, token: fixture.config.token });
  assert.ok(discovery.courses.some(c => c.id === fixture.config.courseId)); assert.ok(discovery.canReadGrades); assert.ok(discovery.canReadSubmissions);
  const connection = lms.connect({ subjectId: subject.id, discoveryId: discovery.id, courseId: fixture.config.courseId, autoMinutes: 0 });
  const first = await lms.sync(connection.id); assert.equal(first.status, 'success', JSON.stringify(first));
  const imported = store.snapshot(); const resources = imported.lmsItems.filter(i => i.data.kind === 'resource'); const activities = imported.lmsItems.filter(i => i.data.kind === 'activity');
  assert.equal(activities.length, 2); assert.equal(resources.length, 3);
  assert.equal(imported.materials.filter(m => m.lms).length, 3); assert.ok(imported.materials.some(m => m.text.includes('2^(4) = 16')));
  assert.equal(imported.tasks.length, 2); assert.ok(imported.tasks.some(t => t.dueDate === null));
  const task = imported.tasks.find(t => t.lms && imported.lmsItems.find(i => i.id === t.lms.itemId)?.data.moduleId === fixture.config.assignmentModuleId); assert.ok(task); assert.equal(task.status, 'completed');
  assert.ok(activities.some(i => i.data.submission?.text.includes('16 combinaciones'))); assert.ok(imported.lmsItems.some(i => i.data.kind === 'grade' && i.data.raw === 80));
  assert.deepEqual(imported.estimates, initial.estimates); assert.equal(imported.attempts.length, 0);
  const second = await lms.sync(connection.id); assert.equal(second.changes.length, 0, JSON.stringify(second)); assert.equal(store.snapshot().lmsVersions.length, imported.lmsVersions.length);
  store.updateTask({ id: task.id, subjectId: subject.id, title: 'Mi objetivo personal', notes: 'Practicar antes de entregar', dueDate: '2026-11-01', estimatedMinutes: 30, conceptIds: [] });
  const oldResource = imported.lmsItems.find(i => i.data.kind === 'resource' && i.data.moduleId === fixture.config.resourceModuleId); const originalText = imported.materials.find(m => m.id === oldResource.local.materialIds[0]).text;
  await fixture.action('update'); const update = await lms.sync(connection.id); assert.equal(update.status, 'success', JSON.stringify(update)); assert.ok(update.changes.some(c => c.kind === 'updated'));
  const updated = store.snapshot(); assert.equal(updated.tasks.find(t => t.id === task.id).title, 'Mi objetivo personal'); assert.equal(updated.tasks.find(t => t.id === task.id).dueDate, '2026-11-01');
  const newResource = updated.lmsItems.find(i => i.id === oldResource.id); assert.equal(newResource.local.materialIds.length, 2); assert.equal(updated.materials.find(m => m.id === oldResource.local.materialIds[0]).text, originalText);
  assert.ok(updated.lmsItems.some(i => i.data.kind === 'grade' && i.data.raw === 95));
  // Make the existing connection due; exercise the real one-minute scheduler and REST, rather than calling its private method.
  store.saveLmsConnection({ ...store.requireLmsConnection(connection.id), autoMinutes: 15, lastSyncAt: new Date(Date.now() - 16 * 60000).toISOString() });
  console.log('Checking the opt-in background scheduler against real Moodle.');
  const schedulerDeadline = Date.now() + 75000;
  while (!store.snapshot().lmsRuns.some(r => r.trigger === 'automatic') && Date.now() < schedulerDeadline) await new Promise(r => setTimeout(r, 1000));
  assert.equal(store.snapshot().lmsRuns.find(r => r.trigger === 'automatic')?.status, 'success');
  lms.configure({ connectionId: connection.id, autoMinutes: 0, enabled: true });
  assert.equal(retrieve(updated.materials, subject.id, 'dieciséis combinaciones').some(c => c.materialId === oldResource.local.materialIds[0]), false);
  await fixture.action('withdraw'); const withdraw = await lms.sync(connection.id); assert.ok(withdraw.changes.some(c => c.kind === 'withdrawn')); assert.ok(store.snapshot().lmsItems.some(i => !i.active));
  await fixture.action('restrict'); const restricted = await lms.sync(connection.id); assert.equal(restricted.scopes.grades, 'unavailable'); assert.ok(store.snapshot().lmsItems.some(i => i.data.kind === 'grade' && i.data.raw === 95 && i.active));
  const exported = store.exportData(); assert.equal(exported.includes(fixture.config.token), false); assert.equal(exported.includes('learner@example.invalid'), false); const before = store.snapshot(); store.importData(exported); lms.restored(); assert.equal(lms.connections()[0].hasCredentials, false); assert.deepEqual(store.snapshot().lmsItems, before.lmsItems);
  const again = await lms.discover({ siteUrl: fixture.siteUrl, token: fixture.config.token }); lms.connect({ subjectId: subject.id, discoveryId: again.id, courseId: fixture.config.courseId, autoMinutes: 0 });
  fixture.stopWeb(); const offline = await lms.sync(connection.id); assert.equal(offline.status, 'failed'); assert.deepEqual(store.snapshot().lmsItems, before.lmsItems);
  lms.disconnect(connection.id); assert.equal(lms.connections()[0].hasCredentials, false); assert.equal(store.snapshot().lmsItems.length, before.lmsItems.length);
  lms.clear(connection.id); assert.equal(store.snapshot().lmsItems.length, 0); assert.equal(store.snapshot().materials.filter(m => m.lms).length, 0); assert.equal(store.snapshot().tasks.length, 0); assert.equal(store.snapshot().materials.filter(m => !m.lms).length, initial.materials.length);
  await mkdir('test-results', { recursive: true }); await writeFile('test-results/moodle-verification.json', JSON.stringify({ completedAt: new Date().toISOString(), moodleVersion: JSON.parse(await readFile('.tools/moodle-test/fixture.json', 'utf8')).moodleVersion ?? '4.5', realRest: true, passwordLogin: true, automaticTimer: true, importedResources: resources.length, importedActivities: activities.length, checks: ['self-enrolled courses', 'instructions', 'dates including no deadline', 'online submission', 'teacher feedback', 'grades', 'file download', 'duplicate filenames isolated', 'page HTML extraction', 'idempotent synchronization', 'immutable material versions', 'local task overrides', 'withdrawal', 'permission failure preserves grades', 'backup excludes credentials', 'restoration needs reconnection', 'offline preserves cache', 'disconnect preserves data', 'explicit cache deletion', 'grades do not alter mastery'] }, null, 2));
  console.log('Real Moodle connector verification passed.');
} finally { lms?.close(); store?.close(); await fixture.stop(); }
