import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { resolve, join } from 'node:path';
const require = createRequire(import.meta.url);
const packaged = process.argv.includes('--packaged'); const prefix = packaged ? 'packaged-' : '';
const directory = resolve('.tools/study-test', randomUUID()); await mkdir(directory, { recursive: true }); await mkdir('test-results', { recursive: true });
const env = { ...process.env, TUTOR_DATA_DIR: directory, TUTOR_SMOKE: '1' }; delete env.ELECTRON_RUN_AS_NODE;
const launch = () => electron.launch({ executablePath: packaged ? resolve('release/win-unpacked/Tutor Local.exe') : require('electron'), args: packaged ? [] : ['.'], env, timeout: 90000 });
let app = await launch(); const errors = [];
try {
  let window = await app.firstWindow(); window.setDefaultTimeout(45000); window.on('pageerror', error => errors.push(error.message));
  await window.getByRole('button', { name: 'Explorar un ejemplo', exact: true }).click();
  await window.getByRole('heading', { name: 'Un poco de potencias de 2.' }).waitFor();
  await window.getByRole('button', { name: 'Sesiones', exact: true }).click();
  await window.getByRole('button', { name: 'Nueva sesión', exact: true }).click();
  await window.getByLabel('Objetivo de esta sesión').fill('Explicar las combinaciones de cuatro bits');
  await window.getByLabel('Duración de la sesión', { exact: true }).selectOption('10');
  await window.getByLabel('Potencias de 2', { exact: true }).check();
  await window.getByLabel(/Guía de ejemplo.*v1/).check();
  await window.getByRole('button', { name: 'Iniciar sesión de estudio' }).click();
  await window.getByRole('heading', { name: 'Explicar las combinaciones de cuatro bits', exact: true }).waitFor();
  await window.getByRole('button', { name: 'Ir a practicar' }).click();
  await window.getByLabel('Respuesta al ejercicio').fill('32');
  await window.getByRole('button', { name: 'Comprobar respuesta' }).click();
  await window.getByRole('heading', { name: 'Un paso más. Bien resuelto.' }).waitFor();
  await window.getByRole('button', { name: 'Mi plan', exact: true }).click();
  await window.locator('.plan-item').first().getByRole('heading', { name: /Continuar mi sesión/ }).waitFor();
  await window.getByRole('button', { name: 'Abrir la sesión en marcha' }).click();
  await window.screenshot({ path: `test-results/${prefix}study-running.png` });
  const active = (await window.evaluate(() => window.tutor.snapshot())).studySessions[0];
  assert.equal(active.status, 'running'); assert.equal(active.attemptIds.length, 1);
  await app.close(); app = await launch(); window = await app.firstWindow(); window.setDefaultTimeout(45000); window.on('pageerror', error => errors.push(error.message));
  await window.getByRole('button', { name: 'Sesiones', exact: true }).click();
  await window.getByText('Pausada', { exact: true }).waitFor();
  let snapshot = await window.evaluate(() => window.tutor.snapshot());
  assert.equal(snapshot.studySessions[0].goal, active.goal); assert.equal(snapshot.studySessions[0].status, 'paused');
  assert.equal(snapshot.studySessions[0].intervals[0].reason, 'closed');
  assert.deepEqual(snapshot.studySessions[0].attemptIds, active.attemptIds);
  await window.getByRole('button', { name: 'Continuar sesión', exact: true }).click();
  await window.getByRole('button', { name: 'Mis tarjetas', exact: true }).click();
  await window.getByRole('button', { name: 'Crear tarjeta', exact: true }).click();
  await window.getByLabel('Pregunta o idea a recordar').fill('¿Cuántos valores puede representar un bit?');
  await window.getByLabel('Respuesta de referencia').fill('Dos valores: cero y uno.');
  await window.getByRole('button', { name: 'Guardar tarjeta', exact: true }).click();
  await window.getByRole('button', { name: 'Mostrar respuesta' }).click();
  await window.getByRole('button', { name: 'Lo recordaba', exact: true }).click();
  await window.getByRole('button', { name: 'Abrir la sesión en marcha' }).click();
  await window.getByRole('button', { name: 'Terminar y revisar', exact: true }).click();
  await window.getByLabel('¿Qué has aprendido o conseguido?').fill('Puedo explicar por qué cuatro bits representan dieciséis combinaciones.');
  await window.getByLabel('¿Qué te costó y qué estrategia probaste?').fill('Conté las duplicaciones con un dibujo.');
  await window.getByLabel('¿Cuál será tu siguiente paso?').fill('Practicar con seis bits y aplicarlo a una red.');
  await window.getByLabel('Mi percepción después de la sesión', { exact: true }).selectOption('confident');
  await window.screenshot({ path: `test-results/${prefix}study-review.png` });
  await window.getByRole('button', { name: 'Guardar revisión de sesión' }).click();
  await window.getByRole('button', { name: 'Ver sesión y evidencias' }).click();
  await window.locator('.evidence-card').first().waitFor();
  await window.getByText('Conté las duplicaciones con un dibujo.', { exact: false }).waitFor();
  await window.screenshot({ path: `test-results/${prefix}study-evidence.png` });
  await window.getByRole('button', { name: 'Cerrar', exact: true }).click();
  snapshot = await window.evaluate(() => window.tutor.snapshot());
  assert.equal(snapshot.studySessions[0].status, 'completed'); assert.equal(snapshot.studySessions[0].cardReviewIds.length, 1);
  assert.equal(snapshot.attempts.length, 1); assert.equal(snapshot.estimates[0].status, 'progress');
  const path = join(directory, 'study.tutor');
  await app.evaluate(({ dialog }, path) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: path }); dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, path);
  await window.evaluate(() => window.tutor.exportData({ format: 'encrypted', password: 'sesiones-prueba-portable' }));
  assert.equal((await readFile(path)).includes(Buffer.from('Conté las duplicaciones')), false);
  await window.evaluate(() => window.tutor.eraseData()); await window.evaluate(() => window.tutor.importData({ password: 'sesiones-prueba-portable' })); await window.reload();
  assert.deepEqual((await window.evaluate(() => window.tutor.snapshot())).studySessions, snapshot.studySessions);
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setBounds({ width: 960, height: 700 }));
  await window.getByRole('button', { name: 'Sesiones', exact: true }).click();
  await window.screenshot({ path: `test-results/${prefix}study-small.png` });
  assert.equal(await window.evaluate(() => { const main = document.querySelector('.main-content'); return main.scrollWidth <= main.clientWidth + 2; }), true);
  assert.deepEqual(errors, []);
  await writeFile(`test-results/${prefix}study-verification.json`, JSON.stringify({ checkedAt: new Date().toISOString(), packaged, restartPausesTimer: true, goalPreserved: true, attempts: snapshot.studySessions[0].attemptIds.length, cardReviews: snapshot.studySessions[0].cardReviewIds.length, review: true, encryptedRestore: true, smallScreen: true, errors }, null, 2));
  console.log(`Sesiones ${packaged ? 'empaquetadas' : 'de desarrollo'} verificadas: objetivo, navegación, cierre y pausa, reanudación, ejercicios/tarjetas, revisión final, copias y pantalla pequeña.`);
} catch (error) { const page = app.windows()[0]; if (page) await page.screenshot({ path: `test-results/${prefix}study-failure.png` }).catch(() => {}); throw error; }
finally { await app.close(); }
