import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { resolve, join } from 'node:path';
import { createImportFixtures } from './fixtures.mjs';

const require = createRequire(import.meta.url);
const packaged = process.argv.includes('--packaged');
const directory = resolve('.tools/desktop-test', randomUUID());
await mkdir(directory, { recursive: true });
await mkdir('test-results', { recursive: true });
const env = { ...process.env, TUTOR_DATA_DIR: directory, TUTOR_SMOKE: '1' };
delete env.ELECTRON_RUN_AS_NODE;
const launch = () => electron.launch({ executablePath: packaged ? resolve('release/win-unpacked/Tutor Local.exe') : require('electron'), args: packaged ? [] : ['.'], env, timeout: 60000 });
let app = await launch();
try {
  const version = await app.evaluate(({ app }) => app.getVersion());
  assert.equal(version, JSON.parse(await readFile('package.json', 'utf8')).version, 'El ejecutable debe corresponder a la versión que se está verificando.');
  let window = await app.firstWindow();
  const errors = [];
  window.on('pageerror', error => errors.push(error.message));
  await window.getByRole('heading', { name: 'Aprender empieza' }).waitFor();
  await window.screenshot({ path: `test-results/${packaged ? 'packaged-' : ''}welcome.png` });
  await window.getByRole('button', { name: 'Crear mi primera asignatura', exact: true }).click();
  await window.getByLabel('Nombre de la asignatura').fill('Matemáticas');
  await window.getByLabel('Curso', { exact: true }).fill('3.º');
  await window.getByLabel('Nivel académico').fill('ESO');
  await window.getByRole('button', { name: 'Crear asignatura', exact: true }).click();
  await window.getByRole('heading', { name: 'Dale al tutor tus primeros apuntes.' }).waitFor();
  await window.getByRole('button', { name: 'Editar configuración de asignatura' }).click();
  assert.equal(await window.getByLabel('Curso', { exact: true }).inputValue(), '3.º');
  await window.getByLabel('Profesor/a', { exact: false }).fill('Profesora de Matemáticas');
  await window.getByLabel('¿Qué te gustaría conseguir?').fill('Comprender las fracciones');
  await window.screenshot({ path: `test-results/${packaged ? 'packaged-' : ''}subject-settings.png` });
  await window.getByRole('button', { name: 'Guardar configuración', exact: true }).click();
  await window.getByRole('heading', { name: 'Configurar asignatura', exact: true }).waitFor({ state: 'hidden' });
  const configured = await window.evaluate(() => window.tutor.snapshot());
  assert.equal(configured.subjects[0].course, '3.º'); assert.equal(configured.subjects[0].level, 'ESO');
  assert.equal(configured.subjects[0].teacher, 'Profesora de Matemáticas');
  await window.getByRole('button', { name: 'Materiales', exact: true }).click();
  await window.getByRole('button', { name: 'Escribir apuntes', exact: true }).click();
  await window.getByLabel('Título', { exact: true }).fill('Fracciones');
  await window.getByLabel('Contenido', { exact: true }).fill('Una fracción representa partes iguales de un todo. <script>alert("no ejecutar")</script>');
  await window.getByRole('button', { name: 'Guardar apuntes', exact: true }).click();
  await window.getByRole('heading', { name: 'Fracciones', exact: true }).waitFor();
  await window.getByRole('button', { name: 'Leer material' }).click();
  await window.getByText('Una fracción representa partes iguales', { exact: false }).last().waitFor();
  await window.getByRole('button', { name: 'Cerrar', exact: true }).click();
  const fixtures = await createImportFixtures(directory);
  await app.evaluate(({ dialog }, paths) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: paths }); }, [fixtures.pdf, fixtures.docx]);
  const imported = await window.evaluate(async () => { const data = await window.tutor.snapshot(); return window.tutor.importMaterials(data.subjects[0].id); });
  assert.equal(imported.imported, 2, JSON.stringify(imported));
  await window.evaluate(() => window.tutor.createDemo());
  await window.reload();
  await window.locator('.subject-item').filter({ hasText: 'Redes locales' }).click();
  await window.screenshot({ path: `test-results/${packaged ? 'packaged-' : ''}dashboard.png` });
  await window.getByRole('button', { name: 'Practicar', exact: true }).click();
  await window.getByLabel('Respuesta al ejercicio').fill('32');
  await window.getByRole('button', { name: 'Comprobar respuesta' }).click();
  await window.getByRole('heading', { name: 'Un paso más. Bien resuelto.' }).waitFor();
  await window.getByRole('button', { name: 'Probar otro ejercicio' }).click();
  await window.getByRole('button', { name: 'Necesito una pista' }).click();
  await window.getByLabel('Respuesta al ejercicio').fill('65');
  await window.getByRole('button', { name: 'Comprobar respuesta' }).click();
  await window.getByRole('heading', { name: 'Aquí hay una oportunidad de aprender.' }).waitFor();
  await window.getByRole('button', { name: 'Probar otro ejercicio' }).click();
  await window.getByLabel('Respuesta al ejercicio').fill('6');
  await window.getByRole('button', { name: 'Comprobar respuesta' }).click();
  await window.getByRole('heading', { name: 'Aquí hay una oportunidad de aprender.' }).waitFor();
  await window.getByRole('button', { name: 'Mi aprendizaje', exact: true }).click();
  await window.getByText('Necesita refuerzo', { exact: true }).waitFor();
  await window.screenshot({ path: `test-results/${packaged ? 'packaged-' : ''}progress.png` });
  await window.getByRole('button', { name: 'Ver el porqué' }).first().click();
  await window.getByRole('heading', { name: 'Evidencias · Potencias de 2' }).waitFor();
  assert.equal(await window.locator('.evidence-card').count(), 3);
  await window.getByRole('button', { name: 'Cerrar', exact: true }).click();
  await window.getByRole('button', { name: 'Mi tutor', exact: true }).click();
  await window.getByRole('button', { name: 'Preparar tutor' }).waitFor();
  assert.equal(await window.getByRole('button', { name: 'Enviar pregunta' }).isDisabled(), true);
  const isolation = await window.evaluate(async () => {
    const snapshot = await window.tutor.snapshot();
    const other = snapshot.subjects.find(s => s.name === 'Matemáticas');
    const concept = snapshot.concepts.find(c => c.name === 'Potencias de 2');
    try { await window.tutor.createConcept({ subjectId: other.id, name: 'Intento inválido', description: '', prerequisiteIds: [concept.id] }); return false; }
    catch { return true; }
  });
  assert.equal(isolation, true);
  assert.equal(await window.evaluate(() => typeof window.require), 'undefined');
  const backupPath = join(directory, 'portable.tutor');
  await app.evaluate(({ dialog }, backupPath) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: backupPath }); }, backupPath);
  await window.evaluate(() => window.tutor.exportData({ format: 'encrypted', password: 'prueba-portable-segura' }));
  const encrypted = await readFile(backupPath); assert.equal(encrypted.includes(Buffer.from('Una fracción')), false);
  await window.evaluate(() => window.tutor.eraseData());
  assert.equal((await window.evaluate(() => window.tutor.snapshot())).subjects.length, 0);
  await app.evaluate(({ dialog }, backupPath) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [backupPath] }); }, backupPath);
  await window.evaluate(() => window.tutor.importData({ password: 'prueba-portable-segura' }));
  assert.equal((await window.evaluate(() => window.tutor.snapshot())).attempts.length, 3);
  await window.getByRole('button', { name: 'Ajustes', exact: true }).click();
  await window.screenshot({ path: `test-results/${packaged ? 'packaged-' : ''}settings.png` });
  assert.deepEqual(errors, []);
  await app.close();
  app = await launch(); window = await app.firstWindow();
  window.on('pageerror', error => errors.push(error.message));
  await window.getByRole('heading', { name: 'Este es tu espacio.' }).waitFor();
  const restored = await window.evaluate(() => window.tutor.snapshot());
  assert.equal(restored.subjects.length, 2); assert.equal(restored.materials.length, 4); assert.equal(restored.attempts.length, 3);
  assert.equal(restored.subjects.find(subject => subject.name === 'Matemáticas').course, '3.º');
  assert.equal(restored.subjects.find(subject => subject.name === 'Matemáticas').goals, 'Comprender las fracciones');
  assert.deepEqual(errors, []);
  await writeFile(`test-results/${packaged ? 'packaged-' : ''}desktop-verification.json`, JSON.stringify({ checkedAt: new Date().toISOString(), packaged, version, separateCourseAndLevel: true, editableSubjectSettings: true, localPdfAndDocxImport: true, subjectIsolation: true, practiceAndEvidence: true, encryptedRestoreAndRestart: true, errors }, null, 2));
  console.log(`Prueba de escritorio ${packaged ? 'empaquetado' : 'desarrollo'} superada: creación, materiales, práctica, evidencias, aislamiento, copias y persistencia.`);
} finally { await app.close(); }
