import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { resolve, join } from 'node:path';
const require = createRequire(import.meta.url);
const packaged = process.argv.includes('--packaged'); const prefix = packaged ? 'packaged-' : '';
const directory = resolve('.tools/rubrics-test', randomUUID()); await mkdir(directory, { recursive: true }); await mkdir('test-results', { recursive: true });
const env = { ...process.env, TUTOR_DATA_DIR: directory, TUTOR_SMOKE: '1' }; delete env.ELECTRON_RUN_AS_NODE;
const launch = () => electron.launch({ executablePath: packaged ? resolve('release/win-unpacked/Tutor Local.exe') : require('electron'), args: packaged ? [] : ['.'], env, timeout: 90000 });
let app = await launch(); const errors = [];
const text = 'Cada bit puede valer 0 o 1. Cuatro bits permiten 2 × 2 × 2 × 2 = 16 combinaciones. Los cuatro factores de dos corresponden a los cuatro bits.';
try {
  let window = await app.firstWindow(); window.setDefaultTimeout(45000); window.on('pageerror', error => errors.push(error.message));
  await window.getByRole('button', { name: 'Explorar un ejemplo', exact: true }).click();
  await window.getByRole('heading', { name: 'Un poco de potencias de 2.' }).waitFor();
  const portfolio = await window.evaluate(async text => {
    const data = await window.tutor.snapshot();
    return window.tutor.savePortfolio({ subjectId: data.subjects[0].id, title: 'Explicación de cuatro bits', kind: 'project', content: text, reflection: '', conceptIds: [data.concepts[0].id], evidenceIds: [] });
  }, text);
  await window.reload(); await window.getByRole('button', { name: 'Rúbricas', exact: true }).click();
  await window.getByRole('button', { name: 'Nueva rúbrica', exact: true }).click();
  await window.getByLabel('Título de la rúbrica', { exact: true }).fill('Explicar un cálculo de redes');
  await window.getByLabel('Finalidad de la rúbrica', { exact: true }).fill('Justificar el número de combinaciones y explicarlo con claridad.');
  await window.getByLabel('Nombre del criterio 1', { exact: true }).fill('Cálculo justificado');
  await window.getByLabel('Nombre del criterio 2', { exact: true }).fill('Explicación clara');
  await window.getByRole('button', { name: 'Guardar rúbrica', exact: true }).click();
  await window.getByRole('heading', { name: 'Explicar un cálculo de redes', exact: true }).waitFor();
  await window.getByRole('button', { name: 'Ver criterios', exact: true }).click();
  assert.equal(await window.locator('.rubric-grid tbody tr').count(), 2);
  await window.screenshot({ path: `test-results/${prefix}rubric-grid.png` });
  await window.getByRole('button', { name: 'Cerrar', exact: true }).click();
  await window.getByRole('button', { name: 'Revisar un trabajo', exact: true }).click();
  await window.getByLabel('Tomar un trabajo del historial', { exact: true }).selectOption(`portfolio:${portfolio.id}`);
  assert.equal(await window.getByLabel('Trabajo del alumno', { exact: true }).inputValue(), text);
  await window.getByLabel('Enunciado o instrucciones', { exact: true }).fill('¿Cuántas combinaciones permiten cuatro bits? Justifica cada factor.');
  await window.getByRole('button', { name: 'Guardar entrega', exact: true }).click();
  await window.locator('.rubric-workbench').waitFor();
  console.log('Rúbrica creada y entrega del portfolio conservada.');
  await window.getByRole('button', { name: 'Revisar criterio a criterio', exact: true }).click();
  const beforeReview = await window.evaluate(() => window.tutor.snapshot()); const rubric = beforeReview.rubrics[0];
  await window.getByLabel('Nivel para el criterio 1', { exact: true }).selectOption(rubric.levels[2].id);
  await window.getByLabel('Nivel para el criterio 2', { exact: true }).selectOption(rubric.levels[2].id);
  await window.getByLabel('Feedback para el criterio 1', { exact: true }).fill('El cálculo utiliza cuatro factores de dos y llega a 16.');
  await window.getByLabel('Feedback para el criterio 2', { exact: true }).fill('Se explica qué representa cada factor.');
  await window.getByLabel('Siguiente paso para el criterio 1', { exact: true }).fill('Comprobar las combinaciones de cinco bits.');
  await window.getByLabel('Fragmento del trabajo para el criterio 1', { exact: true }).fill('Un fragmento inventado');
  await window.getByRole('button', { name: 'Vincular fragmento 1', exact: true }).click();
  await window.getByRole('alert').filter({ hasText: 'no aparece exactamente' }).waitFor();
  await window.getByLabel('Fragmento del trabajo para el criterio 1', { exact: true }).fill('2 × 2 × 2 × 2 = 16');
  await window.getByRole('button', { name: 'Vincular fragmento 1', exact: true }).click();
  await window.getByLabel('Fragmento del trabajo para el criterio 2', { exact: true }).fill('Los cuatro factores de dos corresponden a los cuatro bits.');
  await window.getByRole('button', { name: 'Vincular fragmento 2', exact: true }).click();
  await window.getByLabel('Qué he aprendido al revisar', { exact: true }).fill('Cada bit añade un factor de dos.');
  await window.getByLabel('Qué voy a cambiar en mi siguiente intento', { exact: true }).fill('Explicar también un caso con cinco bits.');
  await window.getByRole('button', { name: 'Guardar mi revisión', exact: true }).click();
  await window.locator('.rubric-result-card').first().waitFor();
  console.log('Revisión personal con citas literales conservada.');
  let snapshot = await window.evaluate(() => window.tutor.snapshot()); const submission = snapshot.rubricSubmissions[0]; const firstReview = snapshot.rubricReviews[0];
  assert.equal(firstReview.origin, 'self'); assert.equal(firstReview.results.length, 2);
  assert.equal(snapshot.attempts.length, 0); assert.ok(snapshot.estimates.every(estimate => estimate.status === 'unseen'));
  assert.equal(submission.source.id, portfolio.id); assert.equal(submission.kind, 'project');
  await window.getByRole('button', { name: 'Localizar fragmento de Cálculo justificado', exact: true }).click();
  assert.equal(await window.locator('.rubric-original mark').innerText(), '2 × 2 × 2 × 2 = 16');
  await window.screenshot({ path: `test-results/${prefix}rubric-evidence.png` });
  await window.getByRole('button', { name: 'Cerrar', exact: true }).click();
  await window.getByRole('button', { name: 'Editar rúbrica Explicar un cálculo de redes', exact: true }).click();
  await window.getByLabel('Título de la rúbrica', { exact: true }).fill('Criterios revisados de redes');
  await window.getByLabel('Nombre del nivel 3', { exact: true }).fill('Completo');
  await window.getByRole('button', { name: 'Guardar rúbrica', exact: true }).click();
  await window.getByRole('heading', { name: 'Criterios revisados de redes', exact: true }).waitFor();
  await window.getByRole('button', { name: 'Ver rúbrica original', exact: true }).click();
  await window.getByRole('heading', { name: 'Explicar un cálculo de redes · versión 1', exact: true }).waitFor();
  assert.equal(await window.getByRole('columnheader', { name: 'Logrado', exact: true }).count(), 1);
  await window.getByRole('button', { name: 'Cerrar', exact: true }).click();
  await window.getByRole('button', { name: 'Revisar criterio a criterio', exact: true }).click();
  await window.getByLabel('Feedback para el criterio 1', { exact: true }).fill('Puedo explicar por qué hay un factor por bit.');
  await window.getByRole('button', { name: 'Guardar mi revisión', exact: true }).click();
  snapshot = await window.evaluate(() => window.tutor.snapshot());
  assert.equal(snapshot.rubricReviews.length, 2); assert.equal(snapshot.rubricReviews[1].supersedesId, firstReview.id);
  assert.deepEqual(snapshot.rubricReviews[0], firstReview); assert.equal(snapshot.rubricSubmissions[0].rubricRevision, 1);
  console.log('Versiones de rúbrica y revisiones anteriores conservadas.');
  await window.screenshot({ path: `test-results/${prefix}rubric-review.png` });
  const exam = await window.evaluate(async () => { const data = await window.tutor.snapshot(); return window.tutor.startMockExam({ subjectId: data.subjects[0].id, title: 'Comprobar bloqueo de rúbricas', unitId: null, conceptIds: [data.concepts[0].id], maxDifficulty: 1, minutes: 10, questionCount: 1 }); });
  const hidden = await window.evaluate(() => window.tutor.snapshot());
  for (const field of ['rubrics', 'rubricVersions', 'rubricSubmissions', 'rubricReviews']) assert.equal(hidden[field].length, 0);
  const blocked = await window.evaluate(async id => { try { await window.tutor.proposeRubricReview(id); return false; } catch (error) { return /terminar el simulacro/.test(String(error)); } }, submission.id); assert.equal(blocked, true);
  await window.evaluate(id => window.tutor.cancelMockExam(id), exam.id);
  const backupPath = join(directory, 'rubrics.tutor');
  await app.evaluate(({ dialog }, path) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: path }); dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, backupPath);
  await window.evaluate(() => window.tutor.exportData({ format: 'encrypted', password: 'rubricas-prueba-portable' }));
  assert.equal((await readFile(backupPath)).includes(Buffer.from(text)), false);
  const beforeBackup = await window.evaluate(() => window.tutor.snapshot());
  await window.evaluate(() => window.tutor.eraseData()); await window.evaluate(() => window.tutor.importData({ password: 'rubricas-prueba-portable' }));
  await app.close(); app = await launch(); window = await app.firstWindow(); window.setDefaultTimeout(45000); window.on('pageerror', error => errors.push(error.message));
  await window.getByRole('button', { name: 'Rúbricas', exact: true }).click();
  snapshot = await window.evaluate(() => window.tutor.snapshot());
  assert.deepEqual(snapshot.rubricReviews, beforeBackup.rubricReviews); assert.deepEqual(snapshot.rubricSubmissions, beforeBackup.rubricSubmissions);
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setBounds({ width: 960, height: 700 }));
  await window.locator('.rubric-workbench').waitFor();
  assert.equal(await window.evaluate(() => { const main = document.querySelector('.main-content'); return main.scrollWidth <= main.clientWidth + 2; }), true);
  await window.screenshot({ path: `test-results/${prefix}rubric-small.png` });
  await window.getByRole('button', { name: 'Eliminar rúbrica Criterios revisados de redes', exact: true }).click();
  await window.getByRole('button', { name: 'Eliminar rúbrica y entregas', exact: true }).click();
  await window.getByRole('heading', { name: 'Empieza por los criterios', exact: true }).waitFor();
  const removed = await window.evaluate(() => window.tutor.snapshot());
  for (const field of ['rubrics', 'rubricVersions', 'rubricSubmissions', 'rubricReviews']) assert.equal(removed[field].length, 0);
  assert.equal(removed.portfolio.length, 1); assert.deepEqual(errors, []);
  await writeFile(`test-results/${prefix}rubrics-verification.json`, JSON.stringify({ checkedAt: new Date().toISOString(), packaged, criteria: firstReview.results.length, levels: rubric.levels.length, portfolioSource: true, literalQuotes: true, rejectedInventedQuote: true, versionedRubric: true, immutableReviews: true, noMasteryFromSelfReview: true, blockedDuringMock: true, encryptedRestoreAndRestart: true, smallScreen: true, deletion: true, errors }, null, 2));
  console.log(`Rúbricas ${packaged ? 'empaquetadas' : 'de desarrollo'} verificadas: criterios, descriptores, entrega del portfolio, citas, versiones, revisiones, aislamiento de simulacro, copias, reinicio y borrado.`);
} catch (error) { const page = app.windows()[0]; if (page) await page.screenshot({ path: `test-results/${prefix}rubrics-failure.png` }).catch(() => {}); throw error; }
finally { await app.close(); }
