import { useEffect, useState } from 'react';
import type { ConceptTimeline } from '../shared/goals';
import { dayKey, addDays } from '../shared/calendar';
import { Badge, Spinner, confidenceNames, errorMessage, type PageProps } from './ui';
import { OriginalEvidence } from './pages/Goals';

export default function GoalTimeline(props: PageProps) {
  const concepts = props.data.concepts.filter(c => c.subjectId === props.subject!.id);
  const [conceptId, setConceptId] = useState(concepts.find(c => c.id === props.practiceConceptId)?.id ?? concepts[0]?.id ?? ''), [startsOn, setStartsOn] = useState(addDays(dayKey(), -29)), [endsOn, setEndsOn] = useState(dayKey());
  const [timeline, setTimeline] = useState<ConceptTimeline>(), [selected, setSelected] = useState(0), [evidence, setEvidence] = useState<string[]>(), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  useEffect(() => { if (!conceptId) return; let live = true; setLoading(true); setError(''); void window.tutor.conceptTimeline({ conceptId, startsOn, endsOn }).then(t => { if (live) { setTimeline(t); setSelected(t.points.length - 1); } }).catch(e => { if (live) { setTimeline(undefined); setError(errorMessage(e)); } }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [conceptId, startsOn, endsOn, props.data.attempts]);
  const point = timeline?.points[selected], labels = { consolidated: 'Consolidado', progress: 'En progreso', reinforce: 'Necesita refuerzo', unseen: 'Sin evidencias' }, ys = { consolidated: 32, progress: 85, reinforce: 138, unseen: 191 };
  const x = (date: string) => 173 + Math.max(0, Math.min(1, (Date.parse(date + 'T12:00:00Z') - Date.parse(startsOn + 'T12:00:00Z')) / Math.max(86400000, Date.parse(endsOn + 'T12:00:00Z') - Date.parse(startsOn + 'T12:00:00Z')))) * 635;
  const path = timeline?.points.map((p, i) => i === 0 ? `M${x(p.date)},${ys[p.estimate.status]}` : `H${x(p.date)}V${ys[p.estimate.status]}`).join(' ');
  return <section className="timeline-panel"><div className="timeline-controls"><label>Concepto<select aria-label="Concepto de la evolución" value={conceptId} onChange={e => setConceptId(e.target.value)}>{concepts.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Periodo<select aria-label="Periodo de la evolución" defaultValue="30" onChange={e => { setStartsOn(addDays(dayKey(), 1 - Number(e.target.value))); setEndsOn(dayKey()); }}><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option><option value="365">Último año</option></select></label><label>Inicio<input aria-label="Inicio de la evolución" type="date" value={startsOn} max={endsOn} onChange={e => setStartsOn(e.target.value)} /></label><label>Fin<input aria-label="Fin de la evolución" type="date" value={endsOn} min={startsOn} max={dayKey()} onChange={e => setEndsOn(e.target.value)} /></label></div>
    <p>Reconstrucción con los ejercicios comprobados del historial actual. Cada punto muestra estado, confianza y trabajos de apoyo. Los informes guardados conservan sus fotografías originales.</p>{loading ? <Spinner label="Reconstruyendo la evolución…" /> : error ? <p className="form-error" role="alert">{error}</p> : timeline && <><svg className="learning-timeline" viewBox="0 0 840 240" role="img" aria-label="Evolución del estado estimado, sin nota numérica"><title>Evolución del estado estimado</title>{Object.entries(ys).map(([state, y]) => <g key={state}><text x="4" y={y + 4}>{labels[state as keyof typeof labels]}</text><line x1="173" x2="808" y1={y} y2={y} /></g>)}<path d={path} className="timeline-path" />{timeline.points.map((p, i) => <circle key={p.at} cx={x(p.date)} cy={ys[p.estimate.status]} r={i === selected ? 6 : 4} className={`timeline-point ${p.estimate.confidence}`} onClick={() => setSelected(i)} aria-hidden="true" />)}<text x="173" y="226">{startsOn}</text><text x="808" y="226" textAnchor="end">{endsOn}</text></svg><p className="subtle-note">La línea conecta estados registrados; los intervalos sin ejercicios no prueban aprendizaje ni olvido. Zona horaria: {timeline.timezone}.</p><div className="timeline-date-list" aria-label="Fechas de la evolución">{timeline.points.map((p, i) => <button key={p.at} className={selected === i ? 'selected' : ''} onClick={() => setSelected(i)}><strong>{i === 0 ? 'Antes del periodo' : p.newEvidenceIds.length ? p.date : 'Al cierre del periodo'}</strong><span>{labels[p.estimate.status]} · Confianza {confidenceNames[p.estimate.confidence].toLowerCase()}</span></button>)}</div>{point && <article className="timeline-selected"><div className="goal-section-head"><h3>{point.date} · {selected === 0 ? 'Estado previo' : 'Estado reconstruido'}</h3><Badge status={point.estimate.status} /></div><p>{point.estimate.reason}</p><p>Confianza {confidenceNames[point.estimate.confidence].toLowerCase()}. {point.newEvidenceIds.length} ejercicios nuevos en este punto.</p><div className="goal-actions"><button className="button secondary" onClick={() => setEvidence(point.estimate.evidenceIds)}>Ver ejercicios de la estimación</button>{point.newEvidenceIds.length > 0 && <button className="button secondary" onClick={() => setEvidence(point.newEvidenceIds)}>Ver intentos de este día</button>}</div></article>}</>}{!concepts.length && <p>Añade conceptos para consultar su evolución.</p>}{evidence && <OriginalEvidence ids={evidence} props={props} onClose={() => setEvidence(undefined)} />}
  </section>;
}
